### ISSUE TITLE
is it possible to polyfill /dev/urandom on windows

### ISSUE THREAD

**Issue by codehz** [jart/cosmopolitan#1001]
Some applications **and libraries** (just search /dev/urandom in github) are HARD COEDED to use /dev/urandom for random source, but currently cosmopolitan doesn't provide random device in nt platform

**Comment by jart** [comment]
Yes we could do this. How does @ahgamut feel about it? The only real concern to doing this is that `getrandom()` is a pretty heavy dependency for our `read()` function to pull in. We'd also have to implement this carefully, since `getrandom()` depends on `read()`. How hard would it be to simply patch the projects that need it? They *should* change to use the much better `getrandom()` API.

**Comment by jart** [comment]
Actually, now that I think about it, we're only talking about Windows code, so `sys_read_nt()` could implement support in a very lightweight way, since it'd only need to depend on `RtlGenRandom()`. Accepted.

**Comment by ahgamut** [comment]
For the projects I've compiled in https://github.com/ahgamut/superconfigure most of them usually have a build configuration where I can specifically choose to use `getrandom` (or `SYS_getrandom`) over other sources of randomness. 

My preference would be to select `getrandom` in the build config or even patch the source code to use `getrandom` and provide a `#pragma message` there (see https://github.com/ahgamut/superconfigure/blob/main/lib/openssl-1.1.1u/minimal.diff for example). 

@codehz can you provide examples of software where `"/dev/urandom"` is opened, but there is no build option to use `getrandom` and/or the usage is not patchable to use `getrandom`?

**Comment by codehz** [comment]
@ahgamut 
Like, command line usage?
Many tutorial use `dd if=/dev/urandom of=xxx` to generate random file as test input. if it is possible in windows, it would be very useful (Yes, you can definitely fix this by patching dd itself, but if it is possible to patch cosmopolitan without too much effort, why not just patch this...
