### ISSUE TITLE
After download and unzip latest release (3.1.3), some files have been recognized as infected

### ISSUE THREAD

**Issue by dominikj111** [jart/cosmopolitan#1003]
I'm on MacOS Sonoma 14.1.2 with cloud based Microsoft Defender, where definitions are auto-updated.
The recognized threats are `Trojan:Win32/Phonzy.B!ml` or `Trojan:Win32/Wacatac.F!ml`.

I can't just ignore those reports and from the system security perspective, this is a problem.

**Comment by jart** [comment]
Looking into it. Can you give me the sha256sum of your cosmocc-3.1.3.zip real quick?

**Comment by dominikj111** [comment]
This is exactly what I expected! Thank you
