### ISSUE TITLE
execve() should polyfill #! on windows

### ISSUE THREAD

**Issue by mwisnicki** [jart/cosmopolitan#1010]
Copied from https://github.com/bellard/quickjs/issues/197:

```
#!/bin/qjs
console.log("Hello");
```

It doesn't work when invoked from bash as script:

```
$ ./test.qjs
./test.qjs: line 2: syntax error near unexpected token `"Hello"'
./test.qjs: line 2: `console.log("Hello");'
$ qjs test.qjs
Hello
```

The same works with native build.

Running on Windows 11. Problem might me broader than qjs but I haven't checked.

**Comment by jart** [comment]
What shell are you using? Cosmopolitan bash?

**Comment by mwisnicki** [comment]
Yes

**Comment by jart** [comment]
@mrdomino Does adding a feature to execve() sound interesting to you? It's the other side of the coin compared to APE Loader.

**Comment by mrdomino** [comment]
Sure!

**Comment by mrdomino** [comment]
Sorry for not responding sooner; I received one spam notification from a Github issue I was subscribed to a week ago, and since then ProtonMail has apparently been marking all of my Github notifications as spam.

**Comment by mrdomino** [comment]
Haven't forgotten about this, just have a bunch of other priorities.

**Comment by mrdomino** [comment]
Is there anything left to do on this?

I unfortunately do not have a windows VM at the moment.
