### ISSUE TITLE
__sys_execve() on linux clobbers argv[0] for ape binaries

### ISSUE THREAD

**Issue by mrdomino** [jart/cosmopolitan#1014]
The symptom is that the `execve` `argv[0]` tests in `test/libc/calls/getprogramexecutablename_test.c` fail against the newest ape loader, but only on code paths where the loader is involved. `MODE=tinylinux`, tests pass; `MODE=tiny`, tests fail.

It seems like the reason this is happening is that Linux's `execve` is taking the interpreter script path. Quoth `execve(2)`:
```
       If  the  pathname argument of execve() specifies an interpreter script, then in‐
       terpreter will be invoked with the following arguments:

           interpreter [optional-arg] pathname arg...

       where pathname is the pathname of the file specified as the  first  argument  of
       execve(),  and arg...  is the series of words pointed to by the argv argument of
       execve(), starting at argv[1].  Note that there is no way  to  get  the  argv[0]
       that was passed to the execve() call.
```

If parity with the non-ape case is desired, then it seems like the way forward is to modify `libc/proc/execve-sysv.c` to move the `IsApeFile` check up above the kernel `__sys_execve`. If that is undesirable, then the `argv[0]` tests can be disabled or removed.

**Comment by jart** [comment]
Cosmo's execve() implementation is intended to be optimistic. The `IsApeFile()` check is extremely costly. What does perfect similarity in behavior offer or make possible that wasn't possible before? Could you also illuminate real a specific example of what `argv[0]` looks like when it changes?

**Comment by mrdomino** [comment]
E.g.:
```c
execve("bin/bash", (char *[]){"-bash", 0}, (char *[]){0});
```
Normal C binary, `argv[0] == "-bash"`. cosmo binary, `argv[0] == "bin/bash"`.

So, it makes it possible to use cosmopolitan binaries as shells without assimilation.

As discussed in Discord, the costly check is not worth it vs just using assimilation, so we will keep `sys_execve` as-is.
