### ISSUE TITLE
.xdc .love .jar .apk .docx shenigans

### ISSUE THREAD

**Issue by zarutian** [jart/cosmopolitan#1028]
I have not looked in detail in the repo but after reading [αcτµαlly pδrταblε εxεcµταblε](https://justine.lol/ape.html) it looks to me the .zip portion of such makes it so an ape can support being:

* [webxdc](https://webxdc.org/) chat app extension
* [Löve2d](https://love2d.org/) game
* Java JAR file
* Android APK file
* docx document

and probably more .zip base formats that do not collide with the above.
My question is, how far can we take this?

If there is an issue that tracks this already I apologize and kindly ask for a link to it.

(btw I had been looking for an executable format to host an forth vm with image for a while. And this fits the bill nearly completely.)

**Comment by TPS** [comment]
#1113 is the closest discussion for this

**Comment by jart** [comment]
We can take it as far as your imagination can go! If it's possible, you *must* build it. Then tell us about it once you do. We love hearing about the cool things people are building with APE and Cosmo.
