### ISSUE TITLE
Error launching emacs

### ISSUE THREAD

**Issue by ejuarezg** [jart/cosmopolitan#1040]
Hi, when launching emacs (v3.1.3 of cosmos), I get the following error:

```
Warning: arch-independent data dir '/zip/usr/share/emacs/28.2/etc/': No such file or directory
Warning: Lisp directory '/zip/usr/share/emacs/28.2/lisp': No such file or directory
Error: /zip/usr/share/emacs/28.2/etc/charsets: No such file or directory
Emacs will not function correctly without the character map files.
Please check your installation!
```

I'm not sure what's wrong.

**Comment by ahgamut** [comment]
Can you try again with the nightly binary at https://cosmo.zip/pub/cosmos/bin/emacs ?

The error is with the APE Zip store, which has seen some updates recently.

**Comment by ejuarezg** [comment]
Thank you, the nightly version no longer shows the error.

**Comment by mrdomino** [comment]
Sounds like this has been resolved?
