### ISSUE TITLE
Should GST actually be PST?

### ISSUE THREAD

**Issue by jmcgover** [jart/cosmopolitan#1049]
Should `GST` be `PST` here? It's configured to have the same offset as `PST` (UTC-08:00).

https://github.com/jart/cosmopolitan/blob/9801f2d1db19c8dc4a80da4562c5365592b70ead/tool/net/help.txt#L4609

[AFAIK](https://en.wikipedia.org/wiki/List_of_time_zone_abbreviations), `GST` is [Gulf Standard Time](https://en.wikipedia.org/wiki/UTC%2B04:00), which is UTC+04:00.

`strftime` seems to output the abbreviated time zone (e.g. via the `%Z` specifier) as `PST` as well. 

Screenshot below made using `history` and `HISTTIMEFORMAT` (all shown).

![screenshot 1704164329](https://github.com/jart/cosmopolitan/assets/6337380/85822444-e5fd-4e40-a72e-0d7f1d2b4103)

**Comment by michaellenaghan** [comment]
See #869

**Comment by mrdomino** [comment]
Should be fixed as of b0df6c1fce30086bb2cefdd0079392fc2ad80edd.
