### ISSUE TITLE
[redbean] Log Rotate

### ISSUE THREAD

**Issue by Propagram** [jart/cosmopolitan#1054]
Hi!

I'm setting up my server using Redbean and have a question about how to handle the log file. I want to rotate it periodically without shutting down the server.

I tried manually deleting the log and sending a reload signal, but the program doesn't recreate the file. The `ProgramLogPath` function can only be called in the context of `.init.lua.`

However, in the documentation, I only found a section about how Redbean handles logs when they take up too much space:

```
ProgramLogPath(bool)
Same as the -L flag if called from .init.lua for setting the log file path on the local file system. It's created if it doesn't exist. This is called before de-escalating the user / group id. The file is opened in append-only mode.
If the disk runs out of space, then redbean will truncate the log file if it has access to change the log file after daemonizing.
```

I cannot afford to wait until the server runs out of space and rely on Redbean to perform the truncate as described, as there are other critical tasks in progress.

Is there a way to send a signal to Redbean to delete the log or provide a function to perform this task? Alternatively, is there a way to set a maximum size for the log to automatically truncate?

Thanks

**Comment by pkulchenko** [comment]
> I tried manually deleting the log and sending a reload signal, but the program doesn't recreate the file. 

@Propagram, have you tried truncating the file (using [unix.truncate](https://redbean.dev/#unix.truncate) instead of deleting it? The logging doesn't re-open the file if it's deleted, but it should continue writing after truncation, as the descriptor will stay the same.

> Is there a way to send a signal to Redbean to delete the log or provide a function to perform this task? Alternatively, is there a way to set a maximum size for the log to automatically truncate?

I don't think there is, but assuming the truncation works, you can set up [OnServerHeartbeat](https://redbean.dev/#OnServerHeartbeat) hook to periodically check for the log size and truncate it as needed.

**Comment by Propagram** [comment]
Using the unix.truncate() function, the log was successfully rotated.

```lua
-- .init.lua

local fm = require "fullmoon"
fm.setSchedule("0 0 * * *", function() --daily
  local ok,err = unix.truncate("my_log.log", 0)
  if not ok then
    Log(kLogError, tostring(err))
  end
end)
fm.run()
```

This solves my issue. Thank you!

**Comment by Propagram** [comment]
For those who want to know how to perform log rotation on Ubuntu for Redbean, follow these steps:

In this example, let's save the logs in the folder: `/root/logs/`, and Redbean needs to have write permissions in this folder.

1. Create a logrotate configuration file:

```
nano /etc/logrotate.d/redbean
```

with the following content:

 ```
/root/logs/*.log {
        daily
        rotate 14
        copytruncate
}
```

`rotate 14` means that only the 14 most recent logs will be stored. Adjust the value as needed. The rotation will be performed automatically every day by Ubuntu.
The `copytruncate` setting is mandatory.

2. In Redbean, specify the Log path in the `.init.lua` file:

```lua
ProgramLogPath('/root/logs/example.log')
```
