### ISSUE TITLE
Add C++ exception support

### ISSUE THREAD

**Issue by jart** [jart/cosmopolitan#1065]
Cosmopolitan's latest cosmocc toolchain build supports SJLJ style exceptions. We now have libunwind thanks to #1053. Let's finish the task and bring `-fexceptions` support to cosmocc.

**Comment by trungnt2910** [comment]
With #1069 and #1063 applied in the mentioned order, LLVM's `libcxxabi`'s [test suite](https://github.com/trungnt2910/cosmopolitan/tree/a18926e05ee4d35c7cc791bba3c0edba55b4e4cb/third_party/libcxxabi/test) for exception handling and RTTI is [running well](https://github.com/trungnt2910/cosmopolitan/actions/runs/7443982833/job/20249660501) on cosmo. The only failing tests are some related to GCC compiler bugs and `thread_local_destruction_order` (casued by #1073).

After this, the only thing blocking C++ exception support is `cosmocc` [hard blockking](https://github.com/jart/cosmopolitan/blob/cafea9a0a5664829f58538aa26f90f1afa6a3ef5/tool/cosmocc/bin/cosmocc#L158) `-fexceptions`.
