### ISSUE TITLE
How can I avoid running tests all the time ?

### ISSUE THREAD

**Issue by mulle-nat** [jart/cosmopolitan#1068]
When I am building cosmopolitan as a dependency in a sandbox the test "pledge_test.com" fails, which is probably expected as it wants to reach "outside". But that leads to the question, how can I skip all tests in a build ? As a dependency I might wipe and rebuild cosmopolitan a few times a day, so rerunning tests gets real tedious... I tried, but I can't figure it out from `Makefile` and `config.mk`. 

Here is the failed test (runs OK outside of lljail):

```
consumed 390,601µs wall time
ballooned to 4,608kb in size
needed 138,517us cpu (13% kernel)
caused 2,707 page faults (100% memcpy)
94 context switches (68% consensual)
performed 0 read and 15,312 write i/o operations

   390,601⏰    138,517⏳   4,608k  15,312iop o//test/libc/calls/pledge_test.com
shm_open(bouncer): Permission denied

`make MODE= -j64 o//test/libc/calls/shm_open_test.com.runs` exited with 1:
o//test/libc/calls/shm_open_test.com
consumed 640µs wall time
needed 684us cpu (0% kernel)
caused 34 page faults (100% memcpy)
3 context switches (66% consensual)
```

**Comment by jart** [comment]
Just build the things you need. For example,

```
tool/cosmocc/package.sh
```

Will only build the subset of targets required to create the cosmocc toolchain folder. Some of things it runs are `make toolchain` which creates the toolchain artifacts for x86-64.

If you're doing mono repo development, you can build any individual package or hierarchy of packages. For example:

```
make -j8 o//libc/str
```

Will build all the .c files in the `LIBC_STR` package. If you wanted to build all libc packages (and not run any tests) you could say:

```
make -j8 o//libc
```

**Comment by jart** [comment]
It's also possible to build individual artifacts. For example, one package that's designed to have the fewest library dependencies is `tool/hello/` which only depends on `LIBC_RUNTIME` and `LIBC_CALLS`. If I `rm -rf o` and say:

```
make -j16 m=tiny o/tiny/tool/hello/hello.com
```

Then it builds that hello world program in 9 seconds, whereas on this computer it would take me ~70 seconds to build everything by running `make -j16`.

**Comment by mulle-nat** [comment]
OK so piecing one and one together, if I want only the libc library with all the goodies from mode "dbg", i go: 

``` bash
make -j16 m=dbg o//libc`
```
So I tried this, but got a new error:

``` bash
`make MODE=dbg -j64 o/dbg/third_party/bash/builtins_ulimit.o` exited with 1:
cosmocc/3.2/bin/x86_64-linux-cosmo-gcc -Wall -Werror -frecord-gcc-switches -fno-optimize-sibling-calls -mno-omit-leaf-frame-pointer -fno-schedule-insns2 -DSYSDEBUG -O0 -fno-inline -fpatchable-function-entry=18,16 -fno-pie -g -Wa,-W -Wa,-I. -Wa,--noexecstack -D_COSMO_SOURCE -DMODE="dbg" -nostdinc -iquote. -isystem libc/isystem -DMODE_DBG -D__SANITIZE_ADDRESS__ -D__SANITIZE_UNDEFINED__ -DFTRACE -DHAVE_CONFIG_H -DSHELL -DPACKAGE="bash" -DLOCALEDIR="/zip/usr/share/locale" -DCONF_HOSTTYPE="unknown" -DCONF_OSTYPE="linux-cosmo" -DCONF_MACHTYPE="unknown-pc-unknown-cosmo" -DCONF_VENDOR="pc" -include libc/integral/normalize.inc -msse3 -fno-math-errno -fno-ident -fno-common -fno-gnu-unique -fstrict-aliasing -fstrict-overflow -fno-semantic-interposition -fno-dwarf2-cfi-asm -fno-unwind-tables -fno-asynchronous-unwind-tables -mno-tls-direct-seg-refs -std=gnu2x -Wno-unused-but-set-variable -Wno-discarded-qualifiers -Wno-maybe-uninitialized -Wno-pointer-to-int-cast -Wno-stringop-truncation -Wno-format-zero-length -Wno-format-overflow -Wno-char-subscripts -Wno-nonnull-compare -Wno-unused-variable -Wno-missing-braces -Wno-unused-label -Wno-unused-value -Wno-parentheses -fportcosmo -fno-inline-functions-called-once -c -o o/dbg/third_party/bash/builtins_ulimit.o third_party/bash/builtins_ulimit.c -fdiagnostics-color=always -fsanitize=address -fsanitize=undefined -fno-data-sections -D__SANITIZE_UNDEFINED__ -mno-red-zone -D__MNO_RED_ZONE__ -fno-omit-frame-pointer -D__FNO_OMIT_FRAME_POINTER__
consumed 132,901µs wall time
ballooned to 31,232kb in size
needed 132,606us cpu (6% kernel)
caused 3,803 page faults (100% memcpy)
13 context switches (23% consensual)
performed 0 read and 432 write i/o operations

./ulimit.def: In function ‘set_limit’:
./ulimit.def:634:1: error: control reaches end of non-void function [-Werror=return-type]
./ulimit.def: At top level:
cc1: note: rewrote 2 switch statements
cc1: note: modified 19 initializations
cc1: all warnings being treated as errors
```
Kinda weird, that it didn't happen before. (This is outside of sandboxing)

**Comment by jart** [comment]
Did you pull my recent charge? I noticed that too while I was fixing this issue, and I fixed that too. Enjoy!

**Comment by jart** [comment]
Also I do not believe that `make -j16 m=dbg o/dbg/libc` triggered `o/dbg/third_party/bash` to build. You're pulling my leg. That's not possible and it would be a GPL violation if it were the case. If you can actually demonstrate that we're not respecting the GPL license then I want to know immediately, so I can fix things.

**Comment by mulle-nat** [comment]
It was late and I seemingly forgot to properly reinstall the script, so it didn't actually run "o//libc" but still the whole thing, which produces the error.  I understood "o//libc" to be some kind of actually usable shortcut, but now I know it isn't and that I had to to explicitly say "o/dbg/libc". I think I will have one more issue coming up soon, but it looks good now ;)

**Comment by mulle-nat** [comment]
To conclude, here is what I ended up doing:

``` sh
cores=64
mode="dbg"  # tiny 

make -j ${cores} m="${mode}" \
                 "o/cosmocc.h.txt" \
                 "o/cosmopolitan.h" \
                 "o/${mode}/ape/ape.lds" \
                 "o/${mode}/libc/crt/crt.o" \
                 "o/${mode}/ape/ape.elf" \
                 "o/${mode}/ape/ape.macho" \
                 "o/${mode}/ape/ape.o" \
                 "o/${mode}/ape/ape-copy-self.o" \
                 "o/${mode}/ape/ape-no-modify-self.o" \
                 "o/${mode}/cosmopolitan.a" \
                 "o/${mode}/libc"

   cp "libc/README.md" "o/${mode}"

   mkdir -p "o/${mode}/include"

   cp -R libc/isystem/* "o/${mode}/include/"
   cp -R libc/integral  "o/${mode}/include/libc/"
```

(basically taken from `tool/cosmocc/package.sh`)
