### ISSUE TITLE
`thread_local` variables destructors are not called when the program exits

### ISSUE THREAD

**Issue by trungnt2910** [jart/cosmopolitan#1073]
## Minimally reproducible example

```cpp
#include <stdio.h>

class Foo
{
  public:
    Foo() { printf("Constructing Foo...\n"); }
    ~Foo() { printf("Destructing Foo...\n"); }
};

int main()
{
  thread_local Foo foo;

  return 0;
}
```

## Expected output
```
Constructing Foo...
Destructing Foo...
```

## Output
```
Constructing Foo...
```

## Notes
- When newly-spawned threads exit normally, the `thread_local` destructors are still called for these threads.
- A larger test case for this is from the `libcxxabi` test suite: [thread_local_destruction_order.pass.cpp](https://github.com/llvm/llvm-project/blob/llvmorg-17.0.6/libcxxabi/test/thread_local_destruction_order.pass.cpp). These two variables never get destroyed:
```cpp
  thread_local OrderChecker fn_thread_local{4};
  thread_local CreatesThreadLocalInDestructor<3> creates_tl;
```

**Comment by jart** [comment]
Fixed in https://github.com/jart/cosmopolitan/commit/81ce2e4cbc5b2dcbe44e58bcf68be49434085ea8.
