### ISSUE TITLE
Compiling GNU tools or sqlite3?

### ISSUE THREAD

**Issue by jgranduel** [jart/cosmopolitan#1079]
Hi, 

I'm exploring cosmopolitan and `cosmocc`.

I tried to compile tools relying on `configure` and `make` on my own (I'm not a C developer, so my remarks might be naive). As a first test (maybe not the easiest?), I tried to compile `gawk-5.3` (the [https://sourceforge.net/projects/ezwinports/](https://sourceforge.net/projects/ezwinports/)  version doesnt woked out on my Win-10 machine).

I test on WSL-2, Ubuntu-20.04.
```
$ ./configure CC=cosmocc
$ make

cosmocc -g -O2 -DNDEBUG -g -O2 -DNDEBUG -no-pie -no-pie -o gawk array.o awkgram.o builtin.o cint_array.o command.o debug.o eval.o ext.o field.o floatcomp.o gawkapi.o gawkmisc.o int_array.o io.o main.o mpfr.o msg.o node.o profile.o re.o replace.o str_array.o symbol.o version.o support/libsupport.a      -no-pie
cosmocc: fatal error: support/libsupport.a: linker input missing concomitant support/.aarch64/libsupport.a file
compilation terminated.
```

Is it supposed to compile? what other options should be used?

I tried with sqlite3 with the amalgamation distrib:
```
$ cosmocc shell.c  sqlite3.c -o sqlite3
cc1: note: rewrote 2 switch statements
```
It worked on WSL but I got a severe trojan alert on Windows by Windows Defender !! I think it's a false positive, but is there a way to prevent it that you know about?

Thanks!

**Comment by jart** [comment]
Try the instructions from the blog post https://justine.lol/cosmo3/#install

```sh
export CC="cosmocc -I/opt/cosmos/include -L/opt/cosmos/lib"
export CXX="cosmoc++ -I/opt/cosmos/include -L/opt/cosmos/lib"
export PKG_CONFIG="pkg-config --with-path=/opt/cosmos/lib/pkgconfig"
export INSTALL="cosmoinstall"
export AR="cosmoar"
./configure --prefix=/opt/cosmos
make -j
make install
```

**Comment by jgranduel** [comment]
Thanks!

It might be obvious but where do `/opt/cosmos/include` and `/opt/cosmos/lib` folders comme from the configuration line `export CC="cosmocc -I/opt/cosmos/include -L/opt/cosmos/lib`? 

I had naively copied your snippet before posting the current issue.  These folders are not in cosmos, is `include` folder the one in cosmocc? I cannot find them so far, 🤷.

Could you make some precision on the blog or README, please?

So much thanks in advance.
