### ISSUE TITLE
Compile shared libraries?

### ISSUE THREAD

**Issue by Kreijstal** [jart/cosmopolitan#1081]
Is it possible to compile shared libraries that other cosmo projects or c projects can depend on? Compile once, depend everywhere?

**Comment by jart** [comment]
In order for that to be possible, someone would need to pick a file format (e.g. so, dylib, dll) and write a cross-platform dynamic loader for it. To date, no one's done that yet. Cosmopolitan has only so far focused on making executables portable. However Cosmopolitan does provide a `cosmo_dlopen()` function for loading dynamic libraries provided by your distro/os.
