### ISSUE TITLE
Loading native lua modules with redbean

### ISSUE THREAD

**Issue by Frityet** [jart/cosmopolitan#1082]
I am trying to use redbean as a web server, but I also have native lua modules installed (through luarocks). I do not want to zip up into a single executable, but I need to be able to `require` `.so`s, how could I do this? 

P.S: Thank you so much for this project, its a total life saver

**Comment by pkulchenko** [comment]
It's not going to be possible at the moment (at least not on all supported systems). Dynamic Lua modules depend on Lua library, as they have to be able to make Lua API calls.

If you need to load something like luasocket (which is a popular dependency), then it may be easier to mock luasocket API using unix.* modules, which I and others have already done. Let me know if you need some pointers for that.

**Comment by Frityet** [comment]
> It's not going to be possible at the moment (at least not on all supported systems). Dynamic Lua modules depend on the Lua library/library, as they have to be able to make Lua API calls, so those methods need to be exported from the static executable (and/or have a proxy dynamic library available to forward those calls).
> 
> If you need to load something like luasocket (which is a popular dependency), then it may be easier to mock luasocket API using unix.* modules, which I and others have already done. Let me know if you need some pointers for that.

right, makes sense. Is it possible to build redbean shared then?

**Comment by pkulchenko** [comment]
> Is it possible to build redbean shared then?

What do you mean by this? You can always build redbean statically and include additional Lua modules into your configuration (similar to how it's done for lsqlite, unix.*, argon2, re.*, and other modules). Dynamic loading of Lua modules is going to be problematic with the current setup.

**Comment by Frityet** [comment]
> > Is it possible to build redbean shared then?
> 
> What do you mean by this? You can always build redbean statically and include additional Lua modules into your configuration (similar to how it's done for lsqlite, unix._, argon2, re._, and other modules). Dynamic loading of Lua modules is going to be problematic with the current setup.

ah sorry, I mean like, build redbean by shared linking lua, so I can `require` .sos

**Comment by pkulchenko** [comment]
No, I don't think it's going to be possible right now, but you should be able to build statically (with all Lua libraries and their dependencies included in one executable).

**Comment by Frityet** [comment]
damn alright, thanks!

**Comment by jperon** [comment]
> it may be easier to mock luasocket API using unix.* modules

@pkulchenko May you please give indications or examples for that? I’m looking for a way to use redbean as a ftp client.

**Comment by pkulchenko** [comment]
@jperon, sure, you can use something like this: https://github.com/pkulchenko/ZeroBranePackage/blob/master/redbean.lua#L90-L133. This has been tested with several different applications (including a luasocket-based debugger) without issues. It can definitely be further extended to cover additional functions.
