### ISSUE TITLE
sscanf %n miscounts 

### ISSUE THREAD

**Issue by mulle-nat** [jart/cosmopolitan#1094]
Here's the source:

``` c
#include <stdio.h>


int  main( int argc, char *argv[])
{
   int           rc;
   unsigned int  a, b, c, d, port, len;

   rc = sscanf( argv[ 1],
                "%u.%u.%u.%u:%u%n",
                &a,
                &b,
                &c,
                &d,
                &port,
                &len);
   printf( "%d: %u.%u.%u.%u:%u (%u)\n", rc, a, b, c, d, port, len);
   return( rc == 5);
}
```

and here's what I am seeing:

``` sh
$ /opt/cosmopolitan/3.2/bin/cosmocc -o sscanf.exe src/main.c 
$ ./sscanf.exe 1.2.3.4:1848
5: 1.2.3.4:1848 (11)
$ gcc -o sscanf2.exe src/main.c 
$ ./sscanf2.exe 1.2.3.4:1848
5: 1.2.3.4:1848 (12)
```

By manual counting 12 would indeed be expected.

*Conceivably I could make pull request for this stuff, if that is desired, but these are mostly just one-liners fixes IMO*

**Comment by jart** [comment]
Thanks for reporting. Looks like a simple fix. You're encouraged to send PRs (see [CONTRIBUTING.md](https://github.com/jart/cosmopolitan/blob/master/CONTRIBUTING.md)). I can take care of this one for you. My fix will be pushed presently. Please take a look and let me know if it works for you.

**Comment by jart** [comment]
Looks like there's a lot of `clang-format` noise in the diff. All I changed was basically this:

```c
        if (c != -1) {
          *n_ptr = consumed - 1;  // minus lookahead
        } else {
          *n_ptr = consumed;
        }
```
