### ISSUE TITLE
Redbean 2.2 performance benchmarking is unexpectedly out of line with claims

### ISSUE THREAD

**Issue by bjconlan** [jart/cosmopolitan#1110]
When running the `wrk` tests on fedora 38 against redbean-demo-2.2 ([inline with those on redbean.dev](https://redbean.dev/#benchmark)) I'm seeing:
```
Running 10s test @ http://127.0.0.1:8080/tool/net/demo/index.html
  10000 threads and 10000 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency   205.24ms  210.46ms   2.00s    87.11%
    Req/Sec     8.35     13.97     1.50k    95.83%
  Latency Distribution
     50%  200.19ms
     75%  280.04ms
     90%  457.48ms
     99%  900.33ms
  749564 requests in 10.94s, 596.89MB read
  Socket errors: connect 0, read 0, write 0, timeout 14
Requests/sec:  68544.81
Transfer/sec:     54.58MB
```

While redbean-demo-2.0 is much better with
```
Running 10s test @ http://127.0.0.1:8080/tool/net/demo/index.html
  10000 threads and 10000 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     4.29ms   28.28ms   2.00s    99.76%
    Req/Sec   298.08    303.22    32.01k    93.21%
  Latency Distribution
     50%    2.17ms
     75%    5.10ms
     90%    8.33ms
     99%   15.50ms
  6574032 requests in 10.95s, 5.11GB read
  Socket errors: connect 0, read 5, write 0, timeout 113
Requests/sec: 600449.21
Transfer/sec:    478.15MB
```

Again this is perhaps unwanted noise at this point (more of an fyi) which may need to be addressed in future releases.

**Comment by bjconlan** [comment]
@xet7 I'm using the precompiled redbean-demo assets for each release which don't look to be built nightly (assuming this as https://cosmo.zip/pub/cosmos/bin/redbean-demo doesn't seem to resolve).

I agree with your sentiments regarding benchmarking. I realise these are simply provided as "line in the sand" metrics in this case but an almost 10x performance difference I thought would be worth reporting. (While I am naive to the underling linux/systemd processes, I tried to be as indifferent as possible when replicating the benchmark; (ie. simply ran these one after the other with `ulimit -Sn 1048576` set  which is the hard limit specified by `ulimit -Hn` I wasn't performing any real process monitoring at the time but I did run these tests multiple times and the results are approximately the same (for each version) on each run)

**Comment by jart** [comment]
1. What make and model is your CPU?
2. Please benchmark a static page using redbean.com to benchmark the core web server. The redbean-demo.com examples adds a lot of stuff to the HTTP serving path, such as a `OnHttpRequest()` handler which locks a mutex to show how the shared memory feature works. Acquiring a shared memory lock to do hit counting goes quite fast compared to using database disk writes, but it slows redbean down considerably compared to what's benchmarked by the website's claims.
