### ISSUE TITLE
Fake virus warning Trojan:Win32/Wacatac.B!ml using Redbean at Windows 11 arm64

### ISSUE THREAD

**Issue by xet7** [jart/cosmopolitan#1114]
Hi,
I did get today this warning at Windows 11 arm64 running at Azure, with this Redbean nightly based executeable https://github.com/wekan/wekanstudio/releases/tag/0.01 . So I did restore executeable to run it.

<img width="1759" alt="win11arm-fake-warning" src="https://github.com/jart/cosmopolitan/assets/15545/122db5d9-8421-4326-9188-009b2e701655">

This did happen at Windows 11 arm64. Not at Windows 11 x86_64.

**Comment by jart** [comment]
As mentioned on the https://cosmo.zip/ website, I can only provide Windows Defender support for versioned release binaries. To hold you over until the next release, here's a redbean prerelease binary at the latest revision that's been properly reported: [redbean-38bcea.zip](https://github.com/jart/cosmopolitan/files/14394869/redbean-38bcea.zip)
