### ISSUE TITLE
cosmoc++: fatal error: -pie flag not supported

### ISSUE THREAD

**Issue by yangjiwei-source** [jart/cosmopolitan#1126]
hello world program test, cosmoc++ -o hello main.cpp -pie
cosmoc++: fatal error: -pie flag not supported

some program set -pie，cosmoc++ can't compile

**Comment by jart** [comment]
Cosmo doesn't support PIE. What did you expect to see happen? Do you actually need it? Would you want us to ignore the flag?

**Comment by yangjiwei-source** [comment]
Build error, no further progress, can you ignore it?

**Comment by jart** [comment]
Sure. It'll be incorporated in the next release. You can run `tool/cosmocc/package.sh` in the meantime.
