### ISSUE TITLE
git fails to run on Linux with the error `this ape program lacks  support`

### ISSUE THREAD

**Issue by supriyo-biswas** [jart/cosmopolitan#1132]
I'm trying to run git from https://cosmo.zip/pub/cosmos/zip/git.zip, and I'm facing an error in doing so, and running git causes the error `./bin/git: this ape program lacks  support`.

Investigating with `sh -x`, I see the following output, even though `uname -m` returns `x86_64` by itself.

```
+ MZqFpD=

@
+ command -v bin/git
+ o=bin/git
+ [ x != x--assimilate ]
+ type ape
+ t=/root/.ape-1.9
+ [ x != x--assimilate ]
+ [ -x /root/.ape-1.9 ]
+ /bin/uname -m
+ m=
+ [ ! -d /Applications ]
+ [ x = x--assimilate ]
+ [ x = x--assimilate ]
+ [ ! -d /Applications ]
+ [  = x86_64 ]
+ [  = amd64 ]
+ [  = aarch64 ]
+ [  = arm64 ]
+ echo bin/git: this ape program lacks  support
bin/git: this ape program lacks  support
+ exit 127
```

Taking a peek at the `bin/git` file itself, I found the following snippet:

```
m="$(/bin/uname -m >/dev/null)" || m="$(/usr/bin/uname -m)"
if [ ! -d /Applications ]; then
if [ x"$1" = x--assimilate ]; then
if [ "$m" = x86_64 ] || [ "$m" = amd64 ]; then
...
```

Shouldn't the first assignment to `m` just be `/bin/uname -m`? Otherwise, it'll throw away the output and fail to execute the correct embedded loader.

Thank you in advance.

**Comment by mrdomino** [comment]
Looks like git.zip is kinda old (dates to November 2023.) A more recent shell preamble says `m="$(uname -m 2>/dev/null)"` instead, so the omitted 2 looks like just a mistake.

Seems like just cutting a new release should fix it, but I'm not sure how that is done. @ahgamut?

**Comment by ahgamut** [comment]
I had removed `git.zip` from the nightly build a while back for some reason I don't remember, I have added it back.
