### ISSUE TITLE
possible to support ios / android? just curious

### ISSUE THREAD

**Issue by ouvaa** [jart/cosmopolitan#1146]
https://github.com/jart/cosmopolitan/discussions/1113

**Comment by TPS** [comment]
Originally #1028

**Comment by jart** [comment]
cosmocc binaries support running on Android since 78d3b86ec74012e0a2b5e2d2778077b0ab44e4f8 back in July. Enjoy!

iOS support currently isn't on the roadmap. If anyone knows how to make that happen, let us know!
