### ISSUE TITLE
does not support armv7l?

### ISSUE THREAD

**Issue by imxcstar** [jart/cosmopolitan#1155]
I compiled a hello.c using cosmopcc and run it on an embedded development board. The prompt was: this ape program lacks armv7l support

**Comment by G4Vi** [comment]
Unfortunately I don't think cosmocc is useful for your use case. We only support x86_64 and arm64/aarch64 architectures.

**Comment by jart** [comment]
We wrote blink so you can run your cosmo binaries on platforms like armv7: https://github.com/jart/blink It's not native, but it flips the bit from impossible to possible for all these other platforms. Enjoy!
