### ISSUE TITLE
Update NIX package

### ISSUE THREAD

**Issue by Rucadi** [jart/cosmopolitan#1165]
I'm just playing around with cosmopolitan, for that, one of the easiest ways for me to install any software is to use nix.

However, the latest supported version on nixpkgs seems quite old
https://search.nixos.org/packages?channel=unstable&show=cosmocc

Being in the moment of writing this the 2.2 version.

I would appreciate if this package is given some love and updated to the latest version :)

**Comment by mrdomino** [comment]
This is not currently planned; further discussion on [redbean discord](https://discord.gg/jRGTa2pQ) in #nix.
