### ISSUE TITLE
Python binary is packaged without certificates

### ISSUE THREAD

**Issue by supriyo-biswas** [jart/cosmopolitan#1186]
The python binary available at https://cosmo.zip/pub/cosmos/bin/python does not have the proper certificates bundled in it, as a result trying to make HTTPS requests through the binary does not succeed:

```
$ ./python -c '__import__("urllib.request").request.urlopen("https://www.google.com")' 
Traceback (most recent call last):
  File "Lib/urllib/request.py", line 1348, in do_open
  File "Lib/http/client.py", line 1286, in request
  File "Lib/http/client.py", line 1332, in _send_request
  File "Lib/http/client.py", line 1281, in endheaders
  File "Lib/http/client.py", line 1041, in _send_output
  File "Lib/http/client.py", line 979, in send
  File "Lib/http/client.py", line 1458, in connect
  File "Lib/ssl.py", line 517, in wrap_socket
  File "Lib/ssl.py", line 1075, in _create
  File "Lib/ssl.py", line 1346, in do_handshake
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] unknown error: unable to get local issuer certificate (_ssl.c:1002)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "Lib/urllib/request.py", line 216, in urlopen
  File "Lib/urllib/request.py", line 519, in open
  File "Lib/urllib/request.py", line 536, in _open
  File "Lib/urllib/request.py", line 496, in _call_chain
  File "Lib/urllib/request.py", line 1391, in https_open
  File "Lib/urllib/request.py", line 1351, in do_open
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] unknown error: unable to get local issuer certificate (_ssl.c:1002)>
```

Adding `--strace` shows that the issue is with the certificate not being found in the executable's ZIP:

```
SYS   2637   2637         25'068'560 openat(AT_FDCWD, "/zip/ssl/cert.pem", O_RDONLY) → -1 ENOENT
```

To fix the issue, a certificate from https://github.com/certifi/python-certifi/raw/master/certifi/cacert.pem can be added as part of the compilation process.

**Comment by mrdomino** [comment]
That's annoying, we include the certificates from usr/share/ssl in the binary. I wonder why it is trying to use that file instead.

**Comment by supriyo-biswas** [comment]
@mrdomino about that, the certificates in `usr/share/ssl` should be removed since they are the constituent certificates used by programs like `update-ca-certificates` to build the final `cert.pem` bundle, but that workflow is only triggered when someone adds a new cert to the `usr/share/ssl` directory. Thus, they serve no purpose.

`$PREFIX/ssl/cert.pem` may be simply an OpenSSL default.

**Comment by supriyo-biswas** [comment]
Additionally, could we get a Python binary that doesn't have the other stuff like `rich`, `datasette`, `uvicorn` and the likes?

I'd like to see a Python binary that just has the built-in modules since that's more compact and suited for distribution. Of course, the project ships `datasette` as a seperate binary, and its dependencies should be shipped only in that binary.

Thanks again for looking at this issue!

**Comment by ahgamut** [comment]
This should be fixed with the recent update: https://github.com/ahgamut/superconfigure/releases/tag/z0.0.41
It required specifying the correct `--sysconfdir` when building Python. 

> Additionally, could we get a Python binary that doesn't have the other stuff like rich, datasette, uvicorn and the likes?

A build of Python 3.12.3 with just the stdlib (and `pip`) is now available at https://github.com/ahgamut/superconfigure/releases/download/z0.0.41/lang.zip. The nightly testing binaries has also been updated.
