### ISSUE TITLE
Compiling `htop` with Cosmopolitan - `ncurses` Not Found

### ISSUE THREAD

**Issue by juanrunzio** [jart/cosmopolitan#1264]
### Description

Following the instructions in the [Cosmopolitan Getting Started guide](https://github.com/jart/cosmopolitan?tab=readme-ov-file#getting-started) we are attempting to compile `htop` using Cosmopolitan but have encountered difficulties. We are using Docker to isolate the build environment and ensure consistency in installations, file locations, and environment variables and have successfully compiled `bc`, but with `htop` we are unable to locate `ncurses`.

### Steps to Reproduce

1. We use the following `Dockerfile` to set up the build environment:

```dockerfile
# syntax = docker/dockerfile:1.3-labs
FROM archlinux AS buildtime
RUN --mount=type=cache,target=/var/cache/pacman/pkg,sharing=locked \
    pacman -Sy --noconfirm \
        base-devel \
        wget \
        unzip
RUN mkdir /cosmocc \
 && cd /cosmocc \
 && wget https://cosmo.zip/pub/cosmocc/cosmocc.zip \
 && unzip cosmocc.zip \
 && rm -f cosmocc.zip
# This ARG will not persist in the final image:
ARG COSMOCC="/cosmocc"
ARG COSMOARGS="-I${COSMOCC}/include -L${COSMOCC}/lib"
# This ENV will persist in the final image:
ENV PATH="${PATH}:${COSMOCC}/bin"
ENV CC="cosmocc ${COSMOARGS}"
ENV CXX="cosmoc++ ${COSMOARGS}"
ENV INSTALL="cosmoinstall"
ENV AR="cosmoar"
RUN ln -s "${COSMOCC}/bin/ape-x86_64.elf" "/usr/bin/ape"
WORKDIR /repo
```

2. For `bc`, we successfully use the following commands:

```bash
docker buildx build --target buildtime -t bc_buildtime .
docker run --user=$(id --user) --rm -v $(pwd):/repo -w /repo bc_buildtime:latest ./configure.sh -g
docker run --user=$(id --user) --rm -v $(pwd):/repo -w /repo bc_buildtime:latest make -j$(nproc)
docker run --user=$(id --user) --rm -v $(pwd):/repo -w /repo -it bc_buildtime:latest /usr/bin/ape ./bin/bc
```

3. For `htop`, we attempted a similar approach with additional configurations:

```bash
docker run --rm --user=$(id --user) -v .:/repo -w /repo \
  -v ~/src/cosmopolitan/o/third_party/ncurses:/cosmos/lib/ncurses \
  -v ~/src/cosmopolitan/third_party/ncurses:/cosmos/include/ncurses \
  cosmocc_buildtime:latest ./configure --prefix=/cosmos --disable-dependency-tracking \
  --disable-utempter --disable-systemd --enable-static
```
Current outcome:
```bash
...
checking for sd_bus_open_system in -lsystemd... no
checking for doupdate in -lncurses6... no
checking for doupdate in -lncurses... no
checking for doupdate in -lcurses... no
configure: error: can not find required curses/ncurses library
```

But the compilation process for `htop` fails as it cannot find `ncurses`.

- How can we properly include and link `ncurses` when compiling `htop` with Cosmopolitan?Are there any specific steps or configurations we need to add to our Docker setup to ensure `ncurses` is found during the compilation process?
- Do you have any recommendations for modifying our approach to successfully compile `htop`?

Thank you for your assistance in resolving this issue.

**Comment by jart** [comment]
Trust me you don't want to compile htop with cosmocc. That's a tool that's extremely tied into OS specifics. There's no way to make it a portable APE binary without rewriting the thing. Even then you'd have to write all the monitoring code for OS by hand. Cosmopolitan doesn't abstract that. It only gives you POSIX APIs across platforms. The things you need to do htop aren't POSIX.

**Comment by juanrunzio** [comment]
Thank you for your quick response. I understand that `htop` may not be the ideal candidate for a portable APE binary due to its OS specific dependencies. However, I'm still keen to learn how to handle dependencies like `ncurses` when working with Cosmopolitan.

Could you provide some guidance on how to properly include and link external libraries, such as `ncurses`, when compiling with `cosmocc`? Understanding this process would be helpful for future projects.

**Comment by jart** [comment]
See https://github.com/ahgamut/superconfigure/ which is the repo we use to build cosmos software. Read its docs. It talks about how you want to do things like set up a magic folder named `/zip/` on your hard drive, install qemu-aarch64 to binfmt_misc, etc. I have scripts I've used to build Emacs too that I've written, which calls for ncurses. In this case what I'd do is build it with the cosmocc cross compiler manually, using scripts like:

```sh
#!/bin/bash
set -ex

ARCH=${1:-x86_64}
export COSMO=${COSMO:-/opt/cosmo}
export COSMOS=${COSMOS:-/opt/cosmos/$ARCH}
export AS=$(command -v $ARCH-unknown-cosmo-as) || exit
export CC="$(command -v $ARCH-unknown-cosmo-cc) -L$COSMOS/lib" || exit
export CXX="$(command -v $ARCH-unknown-cosmo-c++) -L$COSMOS/lib" || exit
export CPPFLAGS="-I$COSMOS/include"
export AR=$(command -v $ARCH-unknown-cosmo-ar) || exit
export STRIP=$(command -v $ARCH-unknown-cosmo-strip) || exit
export INSTALL=$(command -v $ARCH-unknown-cosmo-install) || exit
export OBJCOPY=$(command -v $ARCH-unknown-cosmo-objcopy) || exit
export OBJDUMP=$(command -v $ARCH-unknown-cosmo-objdump) || exit
export ADDR2LINE=$(command -v $ARCH-unknown-cosmo-addr2line) || exit
export PKG_CONFIG="pkg-config --with-path=$COSMOS/lib/pkgconfig"

if [ $ARCH = aarch64 ]; then
  export PATH="/opt/cosmos/aarch64/uname.aarch64.elf:$PATH"
fi

export COSMOPOLITAN_DISABLE_ZIPOS=1

cd ~/vendor/ncurses-6.5
./configure --prefix=$COSMOS --sysconfdir=/zip --datarootdir=/zip/share --exec-prefix=/zip/$ARCH --host=$ARCH-pc-linux-musl --build=$ARCH-pc-linux-musl --disable-shared
make uninstall || true
make clean
make -j
make install

# ...
```

Which is important, because ncurses has all these data files that you're going to need to put in your executable after you've run `apelink`. You didn't pick an easy project to start with if you're new to cosmocc. You can see the result if you check out:

```
wget https://cosmo.zip/pub/cosmos/bin/emacs
unzip -vl emacs
chmod +x emacs
./emacs
```
