### ISSUE TITLE
Bug: `pigz` decompression does not work

### ISSUE THREAD

**Issue by mattyclarkson** [jart/cosmopolitan#1277]
### What happened?

`pigz` decompress after `cosmo-3.2.4` does not work anymore

```
$ uname -srmo
Linux 6.8.1-arch1-1 x86_64 GNU/Linux
$ wget https://cosmo.zip/pub/cosmos
/v/3.7.1/bin/ape-x86_64.elf
$ wget https://cosmo.zip/pub/cosmos/v/3.7.1/bin/pigz -O pigz-3.7.1
$ wget https://cosmo.zip/pub/cosmos/v/3.2.4/bin/pigz -O pigz-3.2.4
$ chmod u+x ape-x86_64.elf
$ echo "Hello, world" | gzip | ./ape-x86_64.elf ./pigz-3.2.4 -d
Hello, world
$ echo "Hello, world" | gzip | ./ape-x86_64.elf ./pigz-3.7.1 -d
pigz-3.7.1: abort: internal error
```

The captured `strace`/`ftrace` logs for each command:
- [ftrace-3.2.4.log](https://github.com/user-attachments/files/16837942/ftrace-3.2.4.log)
- [strace-3.2.4.log](https://github.com/user-attachments/files/16837944/strace-3.2.4.log)
- [ftrace-3.7.1.log](https://github.com/user-attachments/files/16837943/ftrace-3.7.1.log)
- [strace-3.7.1.log](https://github.com/user-attachments/files/16837945/strace-3.7.1.log)

### Version

cosmos 3.7.1

### What operating system are you seeing the problem on?

Linux

**Comment by mattyclarkson** [comment]
Duplicate of ahgamut/superconfigure#38. Shall I close this in favour of that one?

**Comment by jart** [comment]
Yes it's an issue with superconfigure.
