### ISSUE TITLE
Bug: Can't use object created with cosmo-clang to link against objects compiled with cosmoc++

### ISSUE THREAD

**Issue by Rucadi** [jart/cosmopolitan#1317]
### What happened?

I wanted to use cosmo-clang to compile C23-compliant code, in this case, I have a header:

```
#pragma once

#ifdef __cplusplus
extern "C" {
#endif
extern const char style_css[];
#ifdef __cplusplus
}	// extern "C"
#endif
```

and the c file:
```
#include "embedded_data.h"
const char style_css[] = {
        #embed "style.css"
};
```

I needed this compiled with clang, since GCC won't support the #embed directive until GCC15.

After compiling it with cosmo-clang from the latest package release:
`cosmo-clang embedded_data.c -c`

I tried to compile-and-link an executable using cosmoc++, which uses GCC14, resulting in this error:

```
cosmoc++ main.cpp static/embedded_data.o 
cosmoc++: fatal error: static/embedded_data.o: linker input missing concomitant static/.aarch64/embedded_data.o file
compilation terminated.
```

Since I saw that the "cosmo-clang" existed, I assumed it was to use, is this supported? Or I'm not supposed to mix cosmo-clang with cosmoc++?

### Version

 14.1.0

### What operating system are you seeing the problem on?

Linux

**Comment by jart** [comment]
Use `cosmocc -mclang`. The `cosmo-clang` program is an implementation detail. I think I'm going to move that to a different folder so people don't think to use it, because this is the second time that confused someone.
