### ISSUE TITLE
commandv on Windows: doesn't search without `.exe` (docs say it should)

### ISSUE THREAD

**Issue by andrei-markeev** [jart/cosmopolitan#1330]
### What happened?

It seems that the the logic for .exe / .com automatic suffixing was removed in https://github.com/jart/cosmopolitan/commit/c88f95a8925ef1d56daa471a1d14f189695eaac8, however, it was never updated in the docs.

> We automatically suffix .com and .exe for all platforms when path searching. 

(https://github.com/jart/cosmopolitan/blob/master/tool/net/help.txt#L2880)

This is honestly very confusing. I was convinced `commandv` doesn't work on Windows at all and doing some work arounds until I accidentally spotted that it actually works if you provide the extension.

I thought to create an MR with help update, but then I noticed this comment in https://github.com/jart/cosmopolitan/commit/a6baba1b07355df93cf5a808acd1b7da2b3725e8:

> The WIN32 CreateProcess() function does not require an .exe or .com
suffix in order to spawn an executable.

So I am a bit confused, maybe it's a bug and the suffixing should be reintroduced after all?

### Version

redbean 3.0.0

### What operating system are you seeing the problem on?

Windows

### Relevant log output

```shell
>: unix.commandv('wsl')
nil     "commandv() failed: No such file or directory"
>: unix.commandv('calc')
nil     "commandv() failed: No such file or directory"
>: unix.commandv('wsl.exe')
"/C/WINDOWS/system32/wsl.exe"
>: unix.commandv('calc.exe')
"/C/WINDOWS/system32/calc.exe"
```

**Comment by jart** [comment]
We used to do the auto-suffixing, but the performance / complexity tradeoff ended up not being acceptable. Usually on Windows we're running programs from cosmos, which don't have the .exe or .com suffixes anymore. You should be able to write a wrapper easily that emulates the old behavior.
