### ISSUE TITLE
errno constants not usable in switch-case

### ISSUE THREAD

**Issue by ahgamut** [jart/cosmopolitan#134]
When using a switch statement, constants that are part of `errno.h` (`ENOENT`, `EACCES` etc.) are not available as case labels at compile-time.

Minimal example:

```c
#include <errno.h>
#include <stdio.h>
#include <string.h>
#include <fcntl.h>

int main(void) {
    int res = 0;
    errno = 0;
    res = open("./nonexist.txt", O_RDONLY);
    printf("res = %d, errno == ENOENT? %s\n", res, (errno == ENOENT ? "yes" : "no")); // this is OK
    switch (errno) {
        case ENOENT: // this causes a compilation error
            printf("custom message: file doesn't exist!\n");
            // do something
            break;
        default:
            printf("\n");
    }
    return 0;
}
```

The following compilation error is raised when attempting to compile with cosmopolitan libc.

```
hello.c: In function ‘main’:
hello.c:12:9: error: case label does not reduce to an integer constant
         case ENOENT:
         ^~~~
```

**Comment by jart** [comment]
Code that uses `switch` on system constants needs to be updated to use `if` statements. That's unavoidable unfortunately. It's the one major breakage we needed to make in terms of compatibility. The tradeoff is explained in the APE blog post:

> That one thing aside, if it's this easy, why has no one done this before? The best answer I can tell is it requires an minor ABI change, where C preprocessor macros relating to system interfaces need to be symbolic. This is barely an issue, except in cases like switch(errno){case EINVAL:...}. If we feel comfortable bending the rules, then the GNU Linker can easily be configured to generate at linktime all the PE/Darwin data structures we need, without any special toolchains. https://justine.lol/ape.html

**Comment by ahgamut** [comment]
@jart seems like we can avoid most of it after all :slightly_smiling_face:
