### ISSUE TITLE
Is there any possibility to build a cosmopolitan go runtime?

### ISSUE THREAD

**Issue by diyism** [jart/cosmopolitan#140]
I knew that golang has bootstrapped itself without relying on libc anymore.

But is there any possible way to build a cosmopolitan go runtime just like cosmoplitan libc?
For example, the Singularity project, it's far more convenient than docker, it's based on golang and c
(ref: https://github.com/hpcng/singularity/issues/5892)
(Just a rude and ignorant question)

**Comment by jart** [comment]
It's a perfectly reasonable question. Go started off not relying on platform C libraries. They ended up changing their policies a few years ago to start using them, after Apple broke every Go binary. It would totally be possible for Go to either use Cosmopolitan, or for Go to simply do what Cosmopolitan does. In order for that to happen, they'd likely need to change their policies.

Here's what I recommend doing. Reach out to the Go team and let them know you want to see Cosmopolitan support happen! If Go team wants it, then I'll be here to support them each step along the way.

I'm going to close out this question. Thanks for asking it! If there's any action items I'll reopen it.

**Comment by borancar** [comment]
@jart, it seems there's some movement with the proposal now "added to the active column of the proposals project
and will now be reviewed at the weekly proposal review meetings.". There are some questions to address from Russ Cox: https://github.com/golang/go/issues/51900#issuecomment-1218327470

Wondering if you could help answering those?

**Comment by jart** [comment]
@borancar Done. See https://github.com/golang/go/issues/51900#issuecomment-1220348434

**Comment by borancar** [comment]
> @borancar Done. See [golang/go#51900 (comment)](https://github.com/golang/go/issues/51900#issuecomment-1220348434)

Spectacular, thank you!
