### ISSUE TITLE
redbean incorrect parses http header range directive

### ISSUE THREAD

**Issue by mutr** [jart/cosmopolitan#144]
HTML5 video not working in redbean.
When browser request for video/audio at the first time it will send initial request with headers like this:
```
Host:localhost
Range:bytes=0-
```
Range header bytes=0- means browser is asking server to return till whatever it can return ie. no end position is specified.
The server must return `206 Partial Content` response, `Content-Length: <file size>` in header and full file content.

But redbean returns `Content-Length: 1` and only one first byte of the file.

Example: [bunny.zip](https://github.com/jart/cosmopolitan/files/6246764/bunny.zip)

**Comment by jart** [comment]
Yep. I spotted that last night. I'll be uploading a fix soon. Thanks for reporting this, and for using redbean!

**Comment by jart** [comment]
New release uploaded to https://justine.lol/redbean/index.html

**Comment by mutr** [comment]
Thank you. Working perfect.

**Comment by mutr** [comment]
Thank you. Working perfect.
