### ISSUE TITLE
Prebuilt example binaries

### ISSUE THREAD

**Issue by niutech** [jart/cosmopolitan#145]
First of all, congratulations on your fantastic project! I am attaching a bundle of prebuilt binaries.zip [edit: link removed by jart] of example APE programs from the Cosmopolitan repository. Would you like to publish it as an asset in the releases, so that users could easily test APE binaries without installing build tools and compiling them?

**Comment by jart** [comment]
Please don't post binaries on this issue tracker. There are plenty of APE binaries already available on https://justine.lol. But that's just a subset of the 443 binaries total that get compiled each time you run `make` on this project. Many of those programs, such as `o//examples/echo.com` are too trivial to be worth distributing. Some of them like `o//examples/unbourne.com` aren't fully fleshed out. Others, such as `build/bootstrap/ar.com` might be worthy of being elevated to their own project page on my website.

Out of curiosity, what's the use case for having prebuilt binaries for these one-off examples? Anyone who wants to build them, need only run:

```
git clone https://github.com/jart/cosmopolitan
cd cosmopolitan
make -j8 o//examples
```

Also note that each time I publish a binary on the website, I go to the trouble of upvoting it on the VirusTotal service. There's currently no automation in place for doing that.
