### ISSUE TITLE
help with 'macOS cannot verify that this app is free from malware'

### ISSUE THREAD

**Issue by markhdavid** [jart/cosmopolitan#147]
This seems like a never-ending battle, but I just tried downloading a cosmopolitan file (redbean.com), then did `chmod +x redbean.com`, then tried to run. MacOS 10.15.7 just puts up an alert:
``` 
"redbean.com" cannot be opened because the developer cannot be verified.
macOS cannot verify that this app is free from malware.
```
I tried the workaround of right-clicking and then doing open, but it says
```
There is no application set to open the document “redbean-now.com”.
```
It seems this has gotten harder, but perhaps I missed the latest advice. Can someone point to any solution or workaround?

**Comment by niutech** [comment]
According to [this article](https://support.apple.com/guide/mac-help/open-a-mac-app-from-an-unidentified-developer-mh40616/mac), you have to click with Control key and choose Open. You should also go to System Preferences > Security & Privacy  >General > Allow apps...., as said in [this article](https://support.apple.com/en-us/HT202491). Also check that the file has executable permission: `chmod a+x redbean-now.com`.

**Comment by jart** [comment]
Did you follow the install instructions recommended on the website? 

```sh
curl https://justine.lol/redbean/redbean-latest.com >redbean.com
curl https://justine.lol/redbean/redbean-latest.com.dbg >redbean.com.dbg
chmod +x redbean.com
./redbean -v
bash -c './redbean.com -v'  # zsh/fish workaround (we upstreamed patches!)
```

Right now what you can do to verify that a binary came from me, is to check the VirusTotal service, and look for an upvote from `howishexeasier`. That's the closest thing we have to multi-platform portable code-signing. I don't have much knowledge about the restrictions that XNU uses, but the curl command above might help.

**Comment by markhdavid** [comment]
Instructions almost work: you have to use `./redbean.com` or `./redbean.com.dbg` on the 4th line. Thanks.

**Comment by jart** [comment]
Thanks for pointing that out. I've updated the website!
