### ISSUE TITLE
Compiling other libraries into a redbean?

### ISSUE THREAD

**Issue by SahAssar** [jart/cosmopolitan#164]
Hey, hope it's okay to ask for general help here, and not just features/bugs. If not let me know and I won't do it again :)

This is a pretty long description but the tldr is "I'm trying to make mapping applications in redbean. How do I bring in C libraries into a redbean build?"

---

I have a project I'm using redbean for which bundles mapping vector tiles, a SQLite DB for address search and maplibre to allow for building truly portable maps. What I'm trying to solve is that while there exists packaged maps using stuff like .mbtiles those always require more software to display and almost never include searchable data. The goal is to provide portable offline maps, of the whole planet (will probably be 80GB) or smaller reigons (european countries would be 100MB - 3GB) that one can just download and run on any desktop or easily stick on a server.

I used https://github.com/phiresky/sql.js-httpvfs to be able to load a address search db without loading the whole file into the browser (though I'm hoping at some point to compile sqlite into redbean instead) and getting tiles/frontend files in was of course easy.

Now I'm looking to implement routing support and https://www.routino.org/ seemed small enough (both size-wise and dependency-wise) to be able to embed within redbean. I think that if I get it compiled and bundled I can write the needed logic to call it from lua.

The routino router seems to not have too many dependencies but I'm not sure how feasible it is since I'm very new to C (mostly just done JS/Lua/PHP/Go before).

```
ldd ../bin/router
	linux-vdso.so.1 (0x00007ffefcdb3000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f57d39dc000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f57d39ba000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f57d37d0000)
```

One obstacle seems to be that routino expects to load files from the filesystem while I'd like to bundle the files within the redbean bundle, but I'm guessing I can change that (EDIT: just saw the comment about the `zip:` filename prefix in another issue, that's awesome!). I got it compiled to wasm with emscripten, but it does not seem to work with emscriptens createLazyFile interface so if I go that route I need to load the full routing index into the browser which is not optimal.

Does this sound feasible at all? Is there any guidance or links you can point me to for where to start on this? I have basically zero experience with C programming besides tweaking variables and recompiling existing projects with their existing toolchains.

Thanks for reading and for cosmopolitan, APE and redbean!

**Comment by jart** [comment]
We're working on SQLite and will have that soon. You can add Routino by cloning the Cosmopolitan monorepo and adding it to third party, using the same convention other code in the codebase uses. I can't assist with that because Routino is AGPL so you wouldn't be able to upstream that into this repo. However Cosmopolitan is still permissive and you are 100% encouraged to make it your own. It's designed to be forked. Both by corporations who want confidentiality and by free software enthusiasts who want copyleft.
