### ISSUE TITLE
Method for Detecting Platform

### ISSUE THREAD

**Issue by gudenau** [jart/cosmopolitan#165]
It would be great if you could add a simple `getPlatform` function call to this.

I know it's not quite in the spirit of the project, but for some use cases where the behavior of applications you would want to ingrate with are so different between platforms it would be nice to be able to do a quick check instead of trying all the possibilities. One example would be different builds of a program for Windows and Linux might store files in different locations and with different names entirety and a way to be able to pick the correct one without probing will lead to faster run times and cleaner code.

**Comment by jart** [comment]
Try these functions, which do platform detection at both compile-time and run-time:

https://github.com/jart/cosmopolitan/blob/4577f7fe11e5d8ef0a50ffeac438f1235b5265b3/libc/dce.h#L78-L85

Plus these functions which do platform detection at compile-time only:

https://github.com/jart/cosmopolitan/blob/4577f7fe11e5d8ef0a50ffeac438f1235b5265b3/libc/dce.h#L66-L75

**Comment by gudenau** [comment]
I swear I looked for those before I asked, sorry about that.

**Comment by jart** [comment]
You asked a good question. Cosmopolitan's approach to dispatching is something I love talking about: https://twitter.com/JustineTunney/status/1390790381365698562 It's a unconventional shift from the status quo. So the more I can help developers know what that means, the more successful this project is going to be. 

Another thing I'm particularly proud of is Cosmopolitan's CPUID dispatching code.

https://github.com/jart/cosmopolitan/blob/4577f7fe11e5d8ef0a50ffeac438f1235b5265b3/libc/nexgen32e/x86feature.h#L10 

Which is supported by this global initializer:

https://github.com/jart/cosmopolitan/blob/4577f7fe11e5d8ef0a50ffeac438f1235b5265b3/libc/nexgen32e/kcpuids.S#L34-L84

Having excellent support for modern hardware while maintaining backwards compatibility with old cpus is something that's deeply important to me.  I view microarchitecture portability as equally important as operating system portability. Having the fast dispatching is why, for example, the redbean web server can compute crc32 52x faster if your cpu is westmere or better:

https://github.com/jart/cosmopolitan/blob/4577f7fe11e5d8ef0a50ffeac438f1235b5265b3/libc/str/crc32z.c#L44-L49

All thanks to a simple elegant macro hack.
