### ISSUE TITLE
Any recommendations on launching via double-clicking archive?

### ISSUE THREAD

**Issue by austinrivas** [jart/cosmopolitan#177]
Hello,

I'm pretty interested in using redbean to develop some simple apps for myself that I might distribute to some friends and family.

Have you done any experimentation on launching the ape from anywhere besides the command line?

**Comment by jart** [comment]
You can call the `LaunchBrowser()` function from your `.init.lua` file so that when you double-click it automatically opens up the browser. See https://justine.lol/redbean/#LaunchBrowser

**Comment by austinrivas** [comment]
> You can call the `LaunchBrowser()` function from your `.init.lua` file so that when you double-click it automatically opens up the browser. See https://justine.lol/redbean/#LaunchBrowser

awsesome, thanks @jart
