### ISSUE TITLE
tcc support

### ISSUE THREAD

**Issue by ihsanturk** [jart/cosmopolitan#178]
I tried to compile the hello world program with [tcc](https://bellard.org/tcc) but it does not support some
parameters. I don't know what they stands for and am sure they are important but 
I removed them (`-no-pie` `-pg` `-Wl,--gc-sections` `-Wl,-T,ape.lds`) to see 
what happens, so the command has become
```patch
diff --git a/run b/run
--- a/run
+++ b/run
@@ -8,10 +8,10 @@ printf %s '
 ' >hello.c
 
# run gcc compiler in freestanding mode
-gcc -g -Os -static -fno-pie -no-pie -mno-red-zone -nostdlib -nostdinc \
-  -fno-omit-frame-pointer -pg -mnop-mcount \
-  -o hello.com.dbg hello.c -Wl,--gc-sections -fuse-ld=bfd \
-  -Wl,-T,ape.lds -include cosmopolitan.h crt.o ape.o cosmopolitan.a
+tcc -g -Os -static -fno-pie -mno-red-zone -nostdlib -nostdinc \
+  -fno-omit-frame-pointer -mnop-mcount \
+  -o hello.com.dbg hello.c -fuse-ld=bfd \
+  -include cosmopolitan.h crt.o ape.o cosmopolitan.a
objcopy -SO binary hello.com.dbg hello.com
 
# NOTE: scp it to windows/mac/etc. *before* you run it!

# ~40kb static binary (can be ~16kb w/ MODE=tiny)
./hello.com
```

but now I am getting
```
In file included from hello.c:1:
In file included from <command line>:1:
cosmopolitan.h:134: warning: __PTRDIFF_TYPE__ redefined
In file included from hello.c:1:
In file included from <command line>:1:
cosmopolitan.h:135: warning: __SIZE_TYPE__ redefined
In file included from hello.c:1:
In file included from <command line>:1:
cosmopolitan.h:5148: error: invalid type
./run: line 15: objcopy: command not found
./run: line 20: ./hello.com: No such file or directory
```
I wonder whether or not there are any plans to support tcc? Thank you for the
great work.

**Comment by jart** [comment]
There currently aren't any plans to support TCC. Why? Because chibicc is more recent, fills the same niche, and is so much better. Check out https://github.com/jart/cosmopolitan/tree/master/third_party/chibicc It's still rough around the edges but it's able to build actually portable executables. It's also able to build most of this repository. Although there's still a few bits of code that are still incompatible. Highly recommend checking it out.

**Comment by themanyone** [comment]
Currently looking into whether tcc will support this, since public development has been coming along at git://repo.or.cz/tinycc.git and tcc now supports some C11 features.
