### ISSUE TITLE
Can't build on PopOS 20.10 (x86_64)

### ISSUE THREAD

**Issue by rhdxmr** [jart/cosmopolitan#18]
I did not touch anything but just run `make`

current master branch points to de09bec215675e9b0beb722df89c6f794da74f3f

> ❯ make
> OBJCOPY        o//test/libc/calls/hefty/spawnve_test.com
> error:test/libc/calls/hefty/spawnve_test.c:55: spawnve_testExit()
>         ASSERT_NE(-1, (pid = spawnlp(0, NULL, CMD, CMD, ARG, "exit 42", NULL)))
>                 need -1 (or 0xffffffffffffffffffffffffffffffff) ≠
>                  got -1 (or 0xffffffffffffffffffffffffffffffff)
>         ENOMEM/err=12/errno:12/GetLastError:0
>         o//test/libc/calls/hefty/spawnve_test.com
> 1 / 4 tests failed
> make: *** [build/rules.mk:76: o//test/libc/calls/hefty/spawnve_test.com.runs] Error 1

**Comment by tankf33der** [comment]
Duplicate of #14

**Comment by jart** [comment]
Thanks @tankf33der! Please follow the other issue for updates.
