### ISSUE TITLE
Cannot edit or add files on Windows 10

### ISSUE THREAD

**Issue by acailly** [jart/cosmopolitan#184]
Here is what I tried:

- open with 7zip, add a comment in `.init.lua`, save: error saying the file is read only
- open with native windows zip browser, open `.init.lua` : cannot edit the file (I suppose it is because it is read only)

- open with 7zip, add a new text file : error saying "not implemented"
- open with native windows zip browser, add a new text file: error saying the zip folder is not valid or damaged

I downloaded the bare executable and the demo executable today, the behavior is the same.

I didn't find another issue like that, so I suppose this is a problem with my env, but cannot think of what it is 😄

**Comment by jart** [comment]
Try using PKZIP. I'm not sure if 7zip supports generalized self-extracting archives. You can also use the ZIP editor that's built-in to Windows 10. I would recommend filing an upstream issue with the 7zip authors, who aren't correctly handling the ZIP standard.

**Comment by acailly** [comment]
When I said "native windows zip browser" I was refering to the ZIP editor that's built-in to Windows 10 you mentioned 🙂
I will try PKZIP and post results here

**Comment by acailly** [comment]
Tried with Winzip trial version:
- Edit `.init.lua`: it crashed
- Add a file: it crashed too

Tried with PKZip trial version:
- Edit `.init.lua`: it worked 🎉 
- Add a file: it worked 🎉

So, to wrap up:
- ZIP editor that's built-in to Windows 10: fail ❌ 
- 7zip: fail ❌ 
- WinZip: fail ❌ 
- PKZip: success ✔️

**Comment by acailly** [comment]
Tried with PeaZip ❌:  
- Edit `.init.lua`: error telling some input files cannot be read
- Add a file: same erro

**Comment by jart** [comment]
If the Zip editor that's part of Windows failed then it probably has something to do with Windows Defender. There's been conflicting reports about its unpredictable behavior, which quite possibly may be influencing some of the other software. Although in the case of 7zip its implementation of the ZIP standard is most likely incorrect and incomplete. Thank you for reporting that PeaZip also has an incorrect implementation. From what I've heard, WinRAR is also incorrect.

The only ZIP file editors where we've witnessed consistently perfect behavior are PKZIP and InfoZip. PKZIP is worth the money. InfoZip is free and equally as good, but it's limited to just a command-line interface.

**Comment by niutech** [comment]
Try using [WiZ](https://sourceforge.net/projects/infozip/files/WiZ/5.03/) for Windows, it should work fine.
