### ISSUE TITLE
little typo in usage doc on justine.lol/redbean/

### ISSUE THREAD

**Issue by acailly** [jart/cosmopolitan#186]
Hi,

Thanks for this tool. After some difficulties on Windows (#184) and after executing the binfmt_misc tuning one-line command from #2 on Ubuntu, I managed to edit the file with Info Zip (the native Gui zip browser on ubuntu didn't work) :tada: 

That's cool :smiley: 

So when I tried the usage doc on https://justine.lol/redbean/ website, I noticed a little typo :

```
echo 'Write("<b>hello</b>")' >hello.lua
zip redbean.com hello.lua

printf 'GET /index.lua\n\n' | nc 127.0.0.1 8080
<b>hello</b>
```

I think the printf should be `printf 'GET /hello.lua\n\n' | nc 127.0.0.1 8080`

Continuing my journey :boat:

**Comment by jart** [comment]
Thanks for bringing that to my attention. Fixed!
