### ISSUE TITLE
How to build cosmopolitan from source in Alpine container?

### ISSUE THREAD

**Issue by mskyttner** [jart/cosmopolitan#190]
I tried building cosmopolitan from source in an Alpine container but ran into some issues... also when attempting to build from the tarball. Looking for hints or suggestions. I might have too many or too few system libs, does the error 127 indicate a missing file (?) and what about the segfault exit 139?

With this multistage Dockerfile in the repo root directory, I tried:

```bash
docker build -t cosmopolitan .
```

```Dockerfile
FROM alpine AS builder

RUN apk update -qq && apk upgrade && apk add --no-cache \
	build-base \
	cmake clang clang-dev make gcc g++ libc-dev linux-headers \
	bash \
	unzip \
	curl

WORKDIR /build

# first attempt: build from files in repo root
COPY . cosmopolitan 

# error: Segmentation fault (core dumped)/clang.sh
# clang 9 EXITED WITH 139: test/libc/release/clang.sh -Wno-unused-command-line-argument -Wno-incompatiblepointer-types-discards-qualifiers -no-canonical-prefixes -fdiagnostics-color=always

# second attempt: build from tarball
#RUN curl -o cosmo.tgz "https://justine.lol/cosmopolitan/cosmopolitan-1.0.tar.gz" && \
#	tar xf cosmo.tgz && \
#	rm cosmo.tgz

# error: make: *** [tool/net/net.mk:81: o//tool/net/redbean.com] Error 127

# command to build using all but one cpu
RUN N_CPU=$((`nproc --all`-1)) && \
	echo "Number of CPUs: $N_CPU" && \
	cd cosmopolitan && \
	make -j$N_CPU V=0

RUN find o -type f -name "*.com" -exec cp {} /tmp/dist \;


# in second stage, just copy over the resulting .com files
FROM alpine

# probably not needed?
#RUN apk update -qq && apk add --no-cache libstdc++

WORKDIR /usr/local/bin
COPY --from=builder /tmp/dist .
RUN chmod +x *

WORKDIR /data
VOLUME ["/data"]
EXPOSE 8080

CMD ["redbean.com -vv"]
```

**Comment by jart** [comment]
Try changing the build command from `make` to `make o//tool/net/redbean.com` so that it only builds redbean. The only Alpine packages you should need to install are:

- make
- zip (todo #189) 

Does the `make` command really fail if clang isn't installed? Because that isn't the intended behavior. That test script is supposed to no-op if the clang command isn't found.

**Comment by mskyttner** [comment]
Thanks for the hints!

I tried to do a fork which added [a simplified Dockerfile](https://github.com/mskyttner/cosmopolitan/blob/master/Dockerfile) and a [yaml file with a GitHub Action](https://github.com/mskyttner/cosmopolitan/blob/master/.github/workflows/push-cosmo.yml#L44-L46) to build on push to GitHub Container Registry for "pushlies", the forked repo has these artifacts [here](https://github.com/users/mskyttner/packages/container/package/cosmopolitan). The resulting images have the Alpine Linux OS and adds .coms (redbean, sqlite3 from the build) and gets listed to be about 10 Mb large in total. I tried it with a local sqlite db which worked well (perhaps a bit slow on the first run?). Archs are linux/386, linux/amd64, linux/arm64, linux/ppc64le.

The default command in this container is to run redbean. I tried using the -D switch for serving a /data directory, and attempted to run it with an index.html placed in this directory but I didn't get it to display properly. This is what I tried:

```bash
echo "hello" > index.html
docker run --rm -it -p 8080:8080 -v $(pwd):/data ghcr.io/mskyttner/cosmopolitan
firefox http://localhost:8080/index.html
```

What am I missing here? Looking to have a way of live-editing files in a directory and have these served by redbean....

The build went ok so thanks for the hints and I guess this ticket could be closed?

**Comment by jart** [comment]
The only arch you should be using is linux/amd64.

redbean should work in your container. I don't use Docker so I can't help you troubleshoot. If you can identify a bug on our end  I'll fix it.

One thing you can do to get even better performance is use the following build command:

```
make MODE=rel o/rel/third_party/sqlite/sqlite.com
```
If you want even more performance, at the cost of microarchitectural portability (because this config uses `-march=native`) then:

```
make MODE=opt o/opt/third_party/sqlite/sqlite.com
```

Please note if you copy the `opt` mode binary to another machine, you're very likely to run into a `SIGILL` illegal instruction crash.

**Comment by mskyttner** [comment]
Thanks! It builds from source (the redbean + sqlite3 parts) in approx 3 minutes in an Alpine Linux container for linux/amd64 on the GitHub Actions runner. Resulting binaries work well and run both inside the container (and outside when extracted to the host). So no troubleshooting needed. 

I'll look more into how to use the redbean -D option properly, I was hoping to be able to mount the content directory served from the host into the container when running redbean to watch live changes as I edit .lua files or .html files on the host, but I'm not sure if the content directory need to be inside the zip already when redbean starts. But that is another thing for me to try out and not a bug. So please close this one :) and thanks for the help!

**Comment by jart** [comment]
Enjoy redbean!

Please note the `-D DIR` staging directory option currently does not do file listings. You have to go directly to the file paths. The listing page only shows what's in the ZIP. But if you use `-D` then the files in there will be overlaid on top of it.
