### ISSUE TITLE
Running DDL and DML commands from sqlite3.com fails with "Error: disk I/O error" (Windows)

### ISSUE THREAD

**Issue by pkulchenko** [jart/cosmopolitan#193]
@jart, I compiled sqlite3.com on win10 in WSL, but when I attempt any DDL or DML command (like `CREATE TABLE test (id INTEGER PRIMARY KEY, content);`), I get "Error: disk I/O error":

```
>sqlite3.com test.db
-- warning: cannot find home directory; cannot read ~/.sqliterc
SQLite version 3.35.5 2021-04-19 18:32:05
Enter ".help" for usage hints.
sqlite> CREATE TABLE test (id INTEGER PRIMARY KEY, content);
Error: disk I/O error
```

`test.db` file is created, but it is always zero size. I also tried running the same command from redbean and got the same error.

Reading from the db works (if I create the file elsewhere), but anything that initiates writing, triggers the error.

Is there something I can do to troubleshoot it further?

**Comment by pkulchenko** [comment]
One more data point: seems to be happening on Windows. I re-run the same binary inside WSL and it properly created and updated the DB file.

**Comment by jart** [comment]
Could you give it a try now?

**Comment by pkulchenko** [comment]
@jart, yes, works now from both sqlite3 and redbean. And the message about the home directory is gone too (fixed by your second commit). Thanks!
