### ISSUE TITLE
Add some way to use Pthread

### ISSUE THREAD

**Issue by Keithcat1** [jart/cosmopolitan#201]
A lot of the things I have tried to compile lately (CGO Go, Rust, Nim, libc++ and Miniaudio) all require various Pthread function.
I'm also not sure how to manually set up Pthread headers and libs because C code requires various C headers like <stdlib.h>. I provide these by just creating empty header files, but I'm not sure which ones from Pthread I should use and which ones Cosmopolitan provides.
It would be nice if Cosmopolitan came with a Pthread static library, either as a part of the Cosmopolitan project or a version of Pthread that doesn't link to any libraries such as dl.

**Comment by jart** [comment]
You can use the `-isystem libc/isystem` flag for compatibility with traditional header layouts. See https://github.com/jart/cosmopolitan/tree/master/libc/isystem

pthreads isn't something we have the resources to do right now. Every operating system does it in a totally different way. I recommend using fork if possible. mmap + map_shared can be used to share memory between processes. I have no personal need of threads. Software that depends on pthreads will sadly need to wait before it can benefit from APE.
