### ISSUE TITLE
Documentation for αcτµαlly pδrταblε εxεcµταblε requirements & docker too

### ISSUE THREAD

**Issue by kissgyorgy** [jart/cosmopolitan#202]
Hello!

This is probably my favorite project of all time!  
I love it and I want to run redbean on multiple environments, for example, NixOS, Docker scratch container and WSL2.

Problems we faced so far:
- cannot create necessary files on NixOS
- when starting in WSL2, actually the Windows binary is recognized first 😃
  so it will run on Windows when started directly (without the bash trick)
- Starting from Docker scratch container gives no error message, just fails

As there is not too much room for very nice error messages in a couple of kilobytes 😄, it would be nice to have some kind of documentation about requirements for APE executables, like under what circumstances, what is the absolute minimum to have on a system to be able to run them, like "it must be able to overwrite itself on Linux" or "shell must be available" something like these.

**Comment by jart** [comment]
> Starting from Docker scratch container gives no error message, just fails

Why is that happening? As far as I know Docker works fine.

**Comment by kissgyorgy** [comment]
> Why is that happening? As far as I know Docker works fine.

The "scratch" container doesn't have any files, not even a shell, nor a filesystem, so the extraction tricks don't work.
Here is a minimal Dockerfile to reproduce:
```
FROM alpine:latest AS build

RUN apk add --update curl
RUN curl -O https://justine.lol/redbean/redbean-1.3.com.dbg
RUN chmod +x /redbean-1.3.com.dbg


FROM scratch

COPY --from=build /redbean-1.3.com.dbg /redbean.com
CMD ["/redbean.com", "-vv"]
```

After building with
```
$ docker build -t redbean-scratch .
```

And trying to start with
```
docker run --rm -it -p 8080:8080 redbean-scratch
```

The output is:
```
libc/zipos/find.c:31:ZIP_CFILE_MAGIC(zipos->map + c) == kZipCfileHdrMagic
6ffffffffa10 0000004be560 UNKNOWN
6ffffffffa20 0000004d8ee7 UNKNOWN
6ffffffffaf0 0000004cc10a UNKNOWN
6ffffffffb40 0000004cbe55 UNKNOWN
6ffffffffb70 0000004dc45a UNKNOWN
6ffffffffc80 0000004dc2b9 UNKNOWN
6ffffffffd60 0000004c9997 UNKNOWN
6ffffffffed0 0000004ca1cc UNKNOWN
6ffffffffee0 0000004cadc5 UNKNOWN
6fffffffff00 0000004cae77 UNKNOWN
6fffffffff20 00000040b072 UNKNOWN
6fffffffff80 000000416c34 UNKNOWN
6fffffffffc0 00000041740f UNKNOWN
6fffffffffe0 0000004018e4 UNKNOWN
7ffca7a15760 000000401174 UNKNOWN
```

I have no idea what that means 😃 

Running redbean sure works fine from something like alpine, which has a full filesystem and busybox, but I want to go absolute minimum with redbean 😄

**Comment by pkulchenko** [comment]
> when starting in WSL2, actually the Windows binary is recognized first, so it will run on Windows when started directly (without the bash trick)

Hm, somehow I though the opposite was happening: after running redbean under WSL2, I couldn't run it on another Windows box (without WSL), as it already patched itself. I'll have to double-check on this.

> Running redbean sure works fine from something like alpine, which has a full filesystem and busybox, but I want to go absolute minimum with redbean

You can probably store "self-patched" file for your platform and then run it instead of the "original" file retrieved from justine.lol.

> Knowing the minimum requirements would make it possible to build such a container.

I remember seeing something similar (the minimal Windows version require, Thompson shell version, etc.), but can't find it at the moment. Maybe I'm imagining it...

**Comment by jart** [comment]
I concur with @pkulchenko about normalizing the executable as ELF before putting it in the docker scratch container. However redbean is a little special as far as APE binaries go. It's the only one that currently restores the MZ header after startup. Here's how you can work around that.

1. Delete the `.ape` file from inside the zip.
2. Run `./redbean.com -h` to normalize the executable. If `.ape` isn't present then it can't restore the header.

Voila. redbean.com is now an ELF binary, and you should be able to use it as the init process of a container with no filesystem! This would make an excellent blog post. Someone else just wrote a similar blog post where they sought to create the tiniest docker container for HTTP serving: https://lipanski.com/posts/smallest-docker-image-static-website If we did this then it would be so much tinier. You'd likely just need the kernel binary and redbean.com.

As for the requirements of file system, the ape.S bootloader only uses shell builtins. So the only file that you should technically need is /bin/sh assuming that's either Almquist Shell or Bash, which are guaranteed to work.

**Comment by jart** [comment]
Here's my handy printf replacement for extremely low level code for things like bootloader or, this, where zero runtime support is available.

```c
void Putc(unsigned char c) {
  uint32_t wrote;
  WriteFile(GetStdHandle(kNtStdErrorHandle), &c, 1, &wrote, 0);
}

void Printf(const char *fmt, ...) {
  int i;
  char c;
  unsigned u;
  va_list va;
  const char *s;
  unsigned long d;
  va_start(va, fmt);
  for (;;) {
    switch ((c = *fmt++)) {
      case '\0':
        va_end(va);
        return;
      case '%':
        switch ((c = *fmt++)) {
          case 's':
            for (s = va_arg(va, const char *); s && *s; ++s) {
              Putc(*s);
            }
            break;
          case 'd':
            d = va_arg(va, unsigned long);
            for (i = 16; i--;) {
              u = (d >> (i * 4)) & 0xf;
              if (u < 10) {
                c = '0' + u;
              } else {
                u -= 10;
                c = 'a' + u;
              }
              Putc(c);
            }
            break;
          default:
            Putc(c);
            break;
        }
        break;
      default:
        Putc(c);
        break;
    }
  }
}
```

I added that to ForkIo like this:

```c
static noinline textwindows noasan void ForkIo(int64_t h, void *buf, size_t n,
                                               bool32 (*f)(), const char *s) {
  char *p;
  size_t i;
  uint32_t x;
  for (p = buf, i = 0; i < n; i += x) {
    Printf("%s %d\n", s, n - i);
    if (!f(h, p + i, n - i, &x, NULL)) {
      Printf("%s failed %d\n", s, GetLastError());
      break;
    }
  }
}
```

Then the strangest thing happened. redbean successfully served the request but couldn't read from the zip.

![image](https://user-images.githubusercontent.com/49262/124350604-557b4f80-dbaa-11eb-8e3c-6e09a84d5d27.png)

So we're making progress.

```
_mmi.i = 000000000000000b
WriteFile 0000000000000040
WriteFile 0000000000000008
WriteFile 0000000000000018
WriteFile 0000000000010000
ReadFile 0000000000000040
ReadFile 0000000000000008
ReadFile 0000000000000018
ReadFile 0000000000010000
ReadFile 00000000000WriteFile 0000000000000018
00018
WReadFile 0000000000000018
riteFile 0000000000000018
WriteFile 0000000000010000
ReadFile 0000000000010000
ReWriteFile 0000000000000018
adFile 0000000000000018
WriteFile 0000000000010000
ReadFile 0000000000010000
ReadFile 0000000000000018
WriteFile 0000000000000018
WriteFile 0000000000010000
ReadFile 0000000000010000
ReaWriteFile 00000d00000000018
File 0000000000000018
WriteFile 0000000000010000
ReadFile 0000000000010000
ReadFile W0000000000000018
riteFile 0000000000000018
WReadFile 00000000riteFile 0000000000010000
00010000
ReadFilWriteFilee 0000000000000018
 0000000000000018
WriteFile 0000000000000018
ReadFile 0000000000000018
WriteFile 0000000000170000
ReadFile 0000000000170000
WriteFile failed 000000000ReadFile failed 00000000000003e6
ReadFile 00000000000000018
0003e6
WriteFile 0000000000000018
WriteFile 0000000000020000
ReadFile 0000000000020000
ReadFile 0000000000000018
WriteFile 0000000000000018
WReadFile 0000000000120000
riteFile 0000000000120000
WriteFile 0000000000049000
ReadFile 0000000000049000
````

I'm going to keep poking at this and update the printf replacement to do line buffering.

**Comment by kissgyorgy** [comment]
This is great! 

With this, the image works and it's just 1.15MB:

```
FROM alpine:latest AS build

ARG VERSION=1.3

RUN apk add --update curl zip bash
RUN curl https://justine.lol/redbean/redbean-${VERSION}.com -o redbean.com
RUN chmod +x redbean.com

# This will normalize the binary to ELF
RUN zip -d redbean.com .ape
RUN ls -la /redbean.com
RUN zip -sf redbean.com
RUN bash /redbean.com -h


FROM scratch

COPY --from=build /redbean.com /
CMD ["/redbean.com", "-vv"]
```

**Comment by jart** [comment]
Hey @lipanski we created a Docker image that's nearly 10x smaller than the one you blogged about here: https://lipanski.com/posts/smallest-docker-image-static-website

@kissgyorgy You could reduce it from 1.1mb to 0.3mb if you use https://justine.lol/redbean/redbean-original-1.4.com which doesn't have SSL/SQLite/Lua. That would be a more apples-to-apples comparison with thttpd.

**Comment by lipanski** [comment]
> Hey @lipanski we created a Docker image that's nearly 10x smaller than the one you blogged about here: https://lipanski.com/posts/smallest-docker-image-static-website

@jart nice 👏  I was actually inspired by redbean when I wrote the article, but back then I had some issues compiling it on Linux so I opted for thttpd.

**Comment by jart** [comment]
@lipanski This repository is designed to compile without fail on any Linux distro. Could you share what went wrong? Maybe it was the binfmt_misc issue? Also do you have any feedback on our release binaries?

**Comment by kissgyorgy** [comment]
> @kissgyorgy You could reduce it from 1.1mb to 0.3mb if you use https://justine.lol/redbean/redbean-original-1.4.com which doesn't have SSL/SQLite/Lua. That would be a more apples-to-apples comparison with thttpd.

Indeed 😃 
```
$ docker images redbean
REPOSITORY   TAG       IMAGE ID       CREATED          SIZE
redbean      latest    b0ff3418ce1c   41 seconds ago   302kB
```

**Comment by jart** [comment]
Awesome work @kissgyorgy. 302kb is an impressive Docker container.

I read @lipanski's [blog post](https://lipanski.com/posts/smallest-docker-image-static-website) again and I must have missed the section where he built thttpd statically with Musl Libc, which resulted in the container size being 186kb. So it turns out I was wrong earlier about being 10x smaller. We can't write a blog post of our own if we're not setting a new record for the tiniest container. So how can we beat that? 

I wrote a7bd4ed9 which lets us produce a 150kb static binary of redbean. 

```
m=tinylinux
make -j8 MODE=$m o/$m/tool/net/redbean-original.com
ls -hal o/$m/tool/net/redbean-original.com
```

It's available online at the URL https://justine.lol/redbean/redbean-original-tinylinux-1.4.com

This is an ELF binary since MODE=tinylinux redefines the SUPPORT_VECTOR which causes the APE bootloader to generate the perfect optimal binary for Linux. See https://justine.lol/cosmopolitan/howfat.html for an explanation of how that works.

Could you try the new binary and confirm that it ends up being smaller? I'm assuming we can safely remove the earlier workaround too, so simpler code!

**Comment by kissgyorgy** [comment]
I made a GitHub repository with Dockerfiles from this thread: https://github.com/kissgyorgy/redbean-docker  
And published an ONBUILD image to Docker Hub, which can be used by others to build tiny images: https://hub.docker.com/r/kissgyorgy/redbean-onbuild

**Comment by coderofsalvation** [comment]
Awesome. Can somebody add 'docker' in the title of this issue?
I was looking for this, but this issue is a bit hidden away from searchengines right now.

**Comment by kissgyorgy** [comment]
> Can somebody add 'docker' in the title of this issue?

This is meant to be a request for documentation about runtime requirements in general, not specifically for Docker only.

**Comment by jart** [comment]
As you wish w.r.t. docker in the title. We should actually have an HTML page devoted to Docker under https://justine.lol/cosmopolitan/tutorials.html Would anyone be interested in writing one? If so I'll post it on the website. You could potentially send it to us as markdown in a docs folder. Then I can take care of turning it into HTML for you.

**Comment by jart** [comment]
The runtime requirements for Actually Portable Executable binaries should be `/bin/sh` and nothing more. Anything more than that is a bug that should be reported. As for compiling Cosmopolitan from source, I want the only requirements for that to be the core Alpine package and GNU make. If the build needs any more that, it's a bug that should be reported.

**Comment by kissgyorgy** [comment]
> The runtime requirements for Actually Portable Executable binaries should be `/bin/sh` and nothing more.

Then this ticket can be closed.

**Comment by kissgyorgy** [comment]
[docker.md](https://github.com/jart/cosmopolitan/files/7531590/docker.md)

I made the Docker tutorial. Feel free to change anything or contact me if you need anything.

I put references to my Docker image and git repo, but if you don't want to include those, feel free to remove them.
