### ISSUE TITLE
new.sh package issues when adding cosmo as a submodule 

### ISSUE THREAD

**Issue by mundusnine** [jart/cosmopolitan#203]
So the best way of having reproducible builds of projects is to add the libraries it uses as subprojects/submodules

Here are some issues that arise when using cosmo and the new.sh project generator
command used: `cd cosmopolitan && examples/package/new.sh ../projectname`
file structure: 
```
|---Project(usually the git root)
    |---cosmopolitan(the submodule)
        |--- projectname(see issue 2)
    |---projectname
```
 - [ ] The defines generated will have the .. in the name i.e. `#ifndef COSMOPOLITAN_.._PROJECTNAME_LIB_MYPRINT_H_` 
 - [ ]  The build folder wont be gitignored like the o folder as the command will be o//..//projectname as it creates it in the cosmo root

**Comment by jart** [comment]
Cosmopolitan was designed to assume a single root directory. That's what enables it to compile so fast. If you want to incorporate the Cosmopolitan codebase and its Makefile config into your project, then you have to fork the repo and put your package in a subdirectory. It can't be used as a git submodule.

The alternative is to use the amalgamated release binaries. You can drop the cosmopolitan.a and cosmopolitan.h rollups into a subdirectory and then bring your own build system / repository structure.

Could you help us understand more about what you want and are hoping to achieve? Having multiple roots isn't something I'm willing to reconsider. However there might be other things I can do to make you happy. For example, many of the folders like `dsp`, `examples`, `tool`, `build`, etc. could be consolidated under `libc/`. That would boost the signal to noise ratio of your own work if you forked this repo for a separate project. Let me know what you think.

**Comment by mundusnine** [comment]
Hey ! Thanks for the fast response.

`Cosmopolitan was designed to assume a single root directory. That's what enables it to compile so fast. If you want to incorporate the Cosmopolitan codebase and its Makefile config into your project, then you have to fork the repo and put your package in a subdirectory. It can't be used as a git submodule.`

Actually we can, but I get you don't want to support that workflow which is fine. Btw, with the new.sh, after the generation is done I just fixed the defines and everything was fine. I was proposing this just so that the new.sh script would support it for users quality of life, but again it isn't in your perspective desirable to have cosmo as a submodule for speed reasons. I don't know if this a gcc or gnumake issue but using another build system, having multiple submodules hasn't impacted compilation performance in any significant manner.

`The alternative is to use the amalgamated release binaries. You can drop the cosmopolitan.a and cosmopolitan.h rollups into a subdirectory and then bring your own build system / repository structure.`

Yes but for debugging, having everything in the source directory is best imho.

`Having multiple roots isn't something I'm willing to reconsider.`
This makes me confused... I am not asking cosmo to have multiple roots. I was just saying that when using cosmo as a git submodule, that the new.sh support the project it creates have a path one directory up. In theory, it already supports it but it had some bugs like the define generation with `..` which aren't valid c define chars and that the project gets built to the cosmo root instead of being built in the o/ folder.
