### ISSUE TITLE
Request: LuaFileSystem for redbean

### ISSUE THREAD

**Issue by username-computer** [jart/cosmopolitan#215]
I see a lot of potential in [redbean]. I really keep this project on my radar.  
Using the browser as GUI and Lua as the dynamic language in combination with HTML, CSS and Javascript, really flexible.  
But at the moment there is something missing, something to see and traverse the computers filesystem.  
  
[Lua][lua_io] on itself is lacking in that department, but the cross-platform third-party library [LuaFileSystem] fixes this.

First I tried building LuaFileSystem so I had a `.so` file and placing it in the [`/.lua`][dotlua] directory so [`require`][lua_require] could find it. This obviously failed.  
I have read the closed and open issues and  found: [using shared libraries #137][closed_issue].
Now I understand that conflicts may arise when using shared libraries in combo with [Cosmopolitan].
Still, I think it would be a great addition if somehow the [LuaFileSystem] library could be included with [redbean].

If I could help with some things in relation to this issue, please give me some directions.  
Thanks and keep up the good work :v::bowtie:

[dotlua]: https://redbean.dev/#dotlua "/.lua/..."
[sqlite]: https://redbean.dev/#lsqlite3 "lsqlite3 module"
[redbean]: https://redbean.dev/ "single-file distributable web server"
[Cosmopolitan]: https://github.com/jart/cosmopolitan "build-once run-anywhere c library" 
[lua_require]: https://www.lua.org/manual/5.1/manual.html#pdf-require "require (modname)"
[lua_io]: https://www.lua.org/manual/5.1/manual.html#5.7 "Input and Output Facilities"
[closed_issue]: https://github.com/jart/cosmopolitan/issues/137 "using shared libraries #137"
[LuaFileSystem]: https://keplerproject.github.io/luafilesystem/ "File System Library for the Lua Programming Language"

**Comment by mundusnine** [comment]
This would be trivial to implement as cosmopolitan libc implements the C API to access the filesystem. 

You have two possible solutions:

1. You copy the files from the LuaFilesystem into a third_party folder in cosmo libc and change the includes in the LuaFilesystem c files to use cosmo's libc(fopen,fwrite etc.)
2.  You make it from scratch and learn how to code in C. A good starting point would be to use [new.sh](https://github.com/jart/cosmopolitan/blob/master/examples/package/new.sh) to generate the cruft(gnumake file and add deps etc.)

**Comment by pkulchenko** [comment]
@username-computer, it's not too difficult to add LFS (for example, see #185 that added lsqlite support), but I think @jart is striving to keep the code small and simple, so the functions in LFS will likely duplicate those already available in cosmopolitan (or those that should/will be available), so it's not likely to be accepted.

As @mundusnine described, you should still be able to add it yourself though, if you want to, as it's just one file, so the changes will be very similar to those in #185.

Another option is to identify those functions you really need ([out of those that LFS provides](https://github.com/keplerproject/luafilesystem/blob/master/src/lfs.c#L8-L20)) and check which ones may already be available in cosmopolitan and which ones may need to be added. For example, lstat, fcntl (lock/unlock), mkdir/rmdir/opendir, chmod/chown, and some other functions are already available, but not exposed to the Lua code, so it may be sufficiently simple to add them. Others like chdir() and currentdir() may not be applicable to redbean.

**Comment by pkulchenko** [comment]
@username-computer, something like this should work: https://github.com/pkulchenko/cosmopolitan/tree/redbean-lua-lfs. This would include lfs into redbean and allow the code like `print(require("lfs").attributes("redbean.com").size)` to execute. I've only superficially tested it, but those methods I tried worked.

I'm not proposing to merge this, as I suspect @jart has other ways of implementing the same functionality, but it's available if you need it.

**Comment by username-computer** [comment]
Thank you @pkulchenko.
I cloned your branche and checked out the [ee68aed] commit.
When I tried to build it failed (to build).
It's probably on my end (lack of knowledge), but the [ee68aed] commit showed me how to edit the project to add [LuaFileSystem] extension.
So I cloned the [cosmopolitan], added and edited the files, then build it with `make -j8 -O o//tool/net/redbean.com`
This worked.  

I added `lfs = require("lfs")` to the `.init.lua` file so `lfs` is usable in every other .lua file.
Ran some simple checks on Linux and Win10 and on both the most useful of the [functions] work.
Of the bunch I checked lfs.touch and lfs.link didn't work on Win10, I quess that is expected.  

Very cool.
As @mundusnine has posted, [libc] contains many of the functions are already.
It only needs some composition, a Lua wrapper for [redbean] and off you go.
But for me, I never worked with C so the learning curve is steep.  

Thanks.

[ee68aed]: https://github.com/pkulchenko/cosmopolitan/commit/ee68aed4a4011fb68117e9fa64569cfd3591e4eb
[LuaFileSystem]: https://keplerproject.github.io/luafilesystem/
[cosmopolitan]: https://github.com/jart/cosmopolitan
[functions]: https://keplerproject.github.io/luafilesystem/manual.html#reference
[libc]: https://github.com/jart/cosmopolitan/tree/master/libc
[redbean]: https://redbean.dev/

**Comment by sneusse** [comment]
Hi, late to the party but I had a similar issue (wanted to use penlight) and went this route to mock the methods needed by pl.path/pl.dir:



```lua

-- LFS mock to work with redbean
local lfs = {}

lfs.dir = unix.opendir
lfs.mkdir = unix.mkdir
lfs.rmdir = unix.rmdir

lfs.attributes = function(path_, attr, follow_symlink)
    local st = unix.stat(path_)
    if not st then
        return nil, "No such entity", 2
    end
    local data = {
        size = st:size(),
        uid = st:uid(),
        gid = st:gid(),
        ino = st:ino(),
        modification = st:mtim(),
        access = st:atim(),
        change = st:ctim(),
        dev = st:dev(),
        permissions = "rwxrwxrwx", -- i'm lazy
    }
    if path.islink(path_) then
        data.mode = "link"
    elseif path.isdir(path_) then
        data.mode = "directory"
    else
        data.mode = "file"
    end

    if attr then
        return assert(data[attr])
    end
-- 
    return data
end

lfs.currentdir = function()
    return unix.getcwd()
end

lfs.chdir = function(d)
    return unix.chdir(d)
end

lfs.link_attrib = function(path_, attr, follow_symlink)
    -- i'm lazy
    return lfs.attributes(path_, attr, follow_symlink)
end

return lfs


```
