### ISSUE TITLE
Question: How to add SQLite FTS5 to redbean 

### ISSUE THREAD

**Issue by Gundolf68** [jart/cosmopolitan#216]
It seems that the FTS5 Extension is not included in the current redbean-1.4.com. 
How can I build redbean with it?

**Comment by pkulchenko** [comment]
@Gundolf68, you'll have to add [SQLITE_ENABLE_FTS5](https://github.com/jart/cosmopolitan/blob/master/third_party/sqlite3/sqlite3.mk#L150) defines to the `THIRD_PARTY_SQLITE3_A_OBJS` section (for example, [after line 119](https://github.com/jart/cosmopolitan/blob/master/third_party/sqlite3/sqlite3.mk#L119)) and compile redbean. That should be enough as far as I can tell.

**Comment by Gundolf68** [comment]
Works! Thank you very much.
