### ISSUE TITLE
redbean startup hooks

### ISSUE THREAD

**Issue by username-computer** [jart/cosmopolitan#224]
Hello,

_Summary_: 
I tried the startup [hooks] redbean provides and it did not work.

_Steps i took_:
I was reading what was new and thought the new hooks are pretty awesome.
So i pulled the latest commit and checked out master: [533f3d1].
Build a new redbean and added the hooks `OnServerStart` and `OnServerStop` to the `.init.lua` file.
(I expect the hooks are like `OnHttpRequest` in the redbean-demo.)
Zipped in the file and started the fresh redbean.
I checked the log and saw the following message: `OnServerStart: attempt to call a nil value`
Not what i expected.

The code of the `.init.lua` file
```lua
function OnServerStart()
  print('OnServerStop')
end

function OnServerStop()
  print('OnServerStop')
end
```

_Maybe related to the cause_:
I went and checked out the commit where the hooks got introduced: [8c4cce0]
threw away the `/o/*` directory and build a new redbean.
Added the same `.init.lua` file and started the redbean.
This time redbean became unresponsive, cpu went to 100% and I needed to kill the process because `ctrl + c` would not work.
Used the same redbean on Windows, but the outcome was the same.

So I went and searched what the first commit was that made the redbean keep working with the `.init.lua` file.
Turns out [64d87d4] was that commit.

I really didn't see why renaming functions and adding a version would _fix_ things.
But there was also a change in the [SetDefaults] function
I checked out the [533f3d1] commit and I changed the line
`ProgramBrand(gc(xasprintf("%s/%hhd.%hhd", REDBEAN, VERSION>>020, VERSION>>010)));` [line](https://github.com/jart/cosmopolitan/blob/64d87d4e5aa0e6142a71b45be34ec5c016168d9c/tool/net/redbean.c#L964)
back to
`ProgramBrand(REDBEAN "/1.4");` [line](https://github.com/jart/cosmopolitan/blob/0b317523a0875d83d650ce8a7b288e3b3500fbba/tool/net/redbean.c#L963)
Build the redbean again and inserted the `.init.lua` file.
This broke the redbean again just like before the [64d87d4] commit.
Again, i don't see why.

😊👍
If needed i can provide a log.
But by the time of writing this, the hooks `OnServerStart` and `OnServerStop` doesn't work.
I have not tried `OnWorkerStart` and `OnWorkerStop`.

[hooks]: https://github.com/jart/cosmopolitan/blob/8c4cce043c05813279a7522aa293c2196e6bbd64/tool/net/help.txt#L335 "/tool/net/help.tx"
[8c4cce0]: https://github.com/jart/cosmopolitan/commit/8c4cce043c05813279a7522aa293c2196e6bbd64 "8c4cce0 introduced new hooks"
[533f3d1]: https://github.com/jart/cosmopolitan/commit/533f3d1ef1dce17634640e00b9dab89f16041d39 "533f3d1 latest commit on typing this"
[64d87d4]: https://github.com/jart/cosmopolitan/commit/64d87d4e5aa0e6142a71b45be34ec5c016168d9c "commit when redbean kept working"
[SetDefaults]: https://github.com/jart/cosmopolitan/blob/64d87d4e5aa0e6142a71b45be34ec5c016168d9c/tool/net/redbean.c#L963

**Comment by pkulchenko** [comment]
Indeed; I submitted #225 that should fix this issue. Thank you for the report!

**Comment by username-computer** [comment]
Yes, the fix you submitted solves the issue.
I've tried `OnServerStart`, `OnServerStop`, `OnWorkerStart` and `OnWorkerStop`.
All those seem to work as expected on my end.

Thanks.

**Comment by jart** [comment]
Thanks for the report. I'll cut a new release once @pkulchenko's fix is in, along with a few others. I'll update this issue when that happens.
