### ISSUE TITLE
Log level Fatal is actually fatal.

### ISSUE THREAD

**Issue by w13b3** [jart/cosmopolitan#231]
Logging with the fatal level stopped the redbean process i've had running.
So i tried to find the cause but it turns out it is intended.

In the file [vflogf.c] there is an if-statement that checks for the level [`kLogFatal`] which eventually calls [`__die`].
While I think it is fitting and somewhat funny, I also think it is implicit and it should be mentioned in the [documentation].

My question: Is stopping the process intended when logging at fatal level?

[`kLogFatal`]: https://github.com/jart/cosmopolitan/blob/master/libc/log/log.h#L13 "kLogFatal"
[vflogf.c]: https://github.com/jart/cosmopolitan/blob/master/libc/log/vflogf.c "vflogf.c"
[`__die`]: https://github.com/jart/cosmopolitan/blob/master/libc/log/vflogf.c#L120 "__die"
[documentation]: https://github.com/jart/cosmopolitan/blob/master/tool/net/help.txt#L1105 "help.txt"

**Comment by jart** [comment]
That is working as intended. I'll update the doc. If you encounter any fatal warnings that don't seem crash report worthy, let me know and I'll fix them.
