### ISSUE TITLE
redbean crashes with SIGSEGV under AWS Lambda

### ISSUE THREAD

**Issue by rhencke** [jart/cosmopolitan#233]
When attempting to run [a redbean executable with the .ape header removed](https://github.com/kissgyorgy/redbean-docker) in AWS Lambda via Docker image, redbean will crash with a SIGSEGV:

```
Segmentation fault      (core dumped) redbean.com -vvvmbagD .
```

The core dump yields the following backtrace:
```
#0  __oncrash_sigsegv () at libc/log/oncrashthunks.S:57
#1  <signal handler called>
#2  OpenExecutable () at libc/runtime/openexecutable.S:172
#3  0x000000000040f802 in RestoreApe () at tool/net/redbean.c:5579
#4  0x000000000041b6d3 in RedBean (argc=argc@entry=3, argv=0x7fc07c5e5000, argv@entry=0x7fff6b268ec8) at tool/net/redbean.c:5674
#5  0x000000000041bc02 in main (argc=3, argv=0x7fff6b268ec8) at tool/net/redbean.c:5751
```

It appears that the remapping of the executable as O_RDWR doesn't (currently) work under AWS Lambda.

**Comment by jart** [comment]
Interesting. If anyone manages to discover more specific details of why Lambda has this behavior, please let us know! It could be a kernel config option that's off by default. It could also potentially be a custom hardening they've performed.
