### ISSUE TITLE
Compile error on CentOS7

### ISSUE THREAD

**Issue by zhengshuxin** [jart/cosmopolitan#24]
Thanks for your job, but I got a compiling error as below:
ZIPOBJ         o//libc/stubs/xnu.S.zip.o
OBJECTIFY.S    o//libc/stubs/onarithmeticoverflow.o
OBJECTIFY.S    o//libc/stubs/errno.o
libc/stubs/errno.S: Assembler messages:
libc/stubs/errno.S:36: Error: invalid character '"' before operand 1

gcc 9: compile failed:o/third_party/gcc/bin/x86_64-linux-musl-gcc -msse3 -mno-red-zone -fno-math-errno -fno-trapping-math -fno-fp-int-builtin-inexact -fno-ident -fno-common -fno-gnu-unique -fstrict-aliasing -fstrict-overflow -fno-omit-frame-pointer -fno-semantic-interposition -mno-omit-leaf-frame-pointer -Wall -Werror -fdebug-prefix-map=/data/zsx/download/lib/cosmopolitan= -frecord-gcc-switches -pg -D__PG__ -Og -g -gdescribe-dies -DIMAGE_BASE_VIRTUAL=0x400000 -nostdinc -iquote . -include libc/integral/normalize.inc -Wa,-W -Wa,-I. -Wa,--noexecstack -c -o o//libc/stubs/errno.o libc/stubs/errno.S -no-canonical-prefixes -fdiagnostics-color=always
make: *** No rule to make target `o//libc/stubs/errno.o', needed by `o//libc/stubs/stubs.a.pkg'.  Stop.

How to fix it?
Thanks.
--zsx

**Comment by jart** [comment]
What are your environment variables? Are you customizing the build in some way?

**Comment by zhengshuxin** [comment]
My environment is: 
CentOS Linux release 7.7.1908 (Core)
gcc version 4.8.5 20150623 (Red Hat 4.8.5-28) (GCC)

**Comment by jart** [comment]
Could you run the following command for me?

```sh
env | grep CC\|AS
```

If you're overriding those variables, could you unset them and retry the build?

Please confirm if it works.

**Comment by zhengshuxin** [comment]
Nothing got after I run "env | grep CC\|AS" in my environment, is something wrong?

**Comment by jart** [comment]
Could you share the full output of `env`? Be sure to scrub it for any sensitive information.

**Comment by zhengshuxin** [comment]
Can the cosmopolitan be compiled on CentOS7 ?  The full env shown below may give no help: 
LC_PAPER=en_US.UTF-8
GOHOSTARCH=amd64
LC_ADDRESS=en_US.UTF-8
LC_MONETARY=en_US.UTF-8
HOSTNAME=xxxx
SHELL=/bin/bash
TERM=linux
HISTSIZE=1000
LC_NUMERIC=en_US.UTF-8
LC_ALL=
SVN_EDITOR=vim
USER=root
LC_TELEPHONE=en_US.UTF-8
VIRTUAL_ENV=/
MAIL=/var/spool/mail/root
PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/bin
LC_MESSAGES=en_US.UTF-8
LC_IDENTIFICATION=en_US.UTF-8
LC_COLLATE=en_US.UTF-8
EDITOR=vim
LANG=en_US.UTF-8
LC_MEASUREMENT=en_US.UTF-8
LESSCHARSET=latin1
SHLVL=1
HOME=/root
LC_CTYPE=en_US.UTF-8
LC_TIME=en_US.UTF-8
LC_NAME=en_US.UTF-8
_=/bin/env

**Comment by jart** [comment]
I just setup a CentOS7 VM and noticed an `error: ar failed` issue which is now resolved. Cosmopolitan now builds fine on RHEL7 and all tests pass. I even removed the Ragel dependency so you literally don't need to install any packages above the minimum install in order to build the entire Cosmopolitan codebase. I wasn't able to reproduce the specific error you encountered. Give this a try:

```
cd cosmopolitan
git pull
rm -rf o
make -j12
```

Thanks for the report.

**Comment by zhengshuxin** [comment]
Thank you very much. I pulled and tried again, and got the below error:
OBJECTIFY.S    o//libc/nexgen32e/memcpy.o
OBJECTIFY.S    o//libc/nexgen32e/zip.o
OBJECTIFY.S    o//libc/nexgen32e/djbsort-avx2.o
OBJECTIFY.S    o//libc/nexgen32e/memjmpinit.o
OBJECTIFY.S    o//libc/nexgen32e/tinystrncmp.ncabi.o
OBJECTIFY.S    o//libc/nexgen32e/errno.o
libc/nexgen32e/errno.S: Assembler messages:
libc/nexgen32e/errno.S:36: Error: invalid character '"' before operand 1

gcc 9: compile failed:o/third_party/gcc/bin/x86_64-linux-musl-gcc -msse3 -mno-red-zone -fno-math-errno -fno-trapping-math -fno-fp-int-builtin-inexact -fno-ident -fno-common -fno-gnu-unique -fstrict-aliasing -fstrict-overflow -fno-omit-frame-pointer -fno-semantic-interposition -mno-omit-leaf-frame-pointer -Wall -Werror -fdebug-prefix-map=/data/zsx/download/lib/cosmopolitan2= -frecord-gcc-switches -pg -D__PG__ -Og -g -gdescribe-dies -DIMAGE_BASE_VIRTUAL=0x400000 -nostdinc -iquote . -include libc/integral/normalize.inc -Wa,-W -Wa,-I. -Wa,--noexecstack -c -o o//libc/nexgen32e/errno.o libc/nexgen32e/errno.S -no-canonical-prefixes -fdiagnostics-color=always
make: *** No rule to make target `o//libc/nexgen32e/errno.o', needed by `o//libc/nexgen32e/nexgen32e.a.pkg'.  Stop.

**Comment by jart** [comment]
I can't reproduce this, sorry.
