### ISSUE TITLE
Integrate JSON support

### ISSUE THREAD

**Issue by pkulchenko** [jart/cosmopolitan#247]
@jart, I've been looking through JSON modules that may be a good target for integration into cosmopolitan (and redbean) and the following two seem to be interesting candidates: (1) [yyjson](https://github.com/ibireme/yyjson) and (2) [tiny-json](https://github.com/rafagafe/tiny-json) and [json-maker](https://github.com/rafagafe/json-maker).

The first one is 10 times larger (in terms of the codebase size), but more fully functional. Both should be fast, C89-compatible and provide one-file integration. Both are available under the MIT license and seem to be recently updated.

Some of the design decisions in tiny-json are interesting (`To maintain reduced memory usage and fast processing the strings are not copied. When you request the value of a JSON element, a reference to the original JSON string is returned. To facilitate the processing of the data the returned strings are null-terminated. This is achieved by setting the null character to JSON control characters such as commas, brackets, braces, and quotation marks.`) and I can probably expose some of that API through Lua metatables to provide access to specific fields instead of converting the entire json into Lua tables every time it's processed.

Let me know if one or two of these look interesting and I'll try to build them with cosmopolitan libs and run some tests.

**Comment by jart** [comment]
There's JSON code in the QuickJS folder. It would actually be supremely excellent if we could find some way to use that for Lua too. Because that would open doors for us, like imagine if redbean supported multiple languages (e.g. Lua, JS, Scheme, Python, etc.) and  you could just freely call functions between languages and pass common data structures without remarshaling.

**Comment by pkulchenko** [comment]
It doesn't seem to be easy, as it looks to be closely integrated with the rest of the JS library (by accepting `JSContext`, `JSValue`, and the rest), so it may be a bit challenging to make it work for other languages. The two libraries I mentioned provide more generic interface that we can use with Lua data structures.

**Comment by pkulchenko** [comment]
@jart, btw, json-maker's API is very similar to the one you have with `append*` functions: https://github.com/rafagafe/json-maker#philosophy. In fact, I suspect that some of its code can be simplified/rewritten using `append*` functions. Are you okay with me taking a stub at integrating it (and possibly tiny-json) into redbean?

**Comment by pkulchenko** [comment]
The generation part has been implemented in #322.

**Comment by ahgamut** [comment]
How about ultrajson? https://github.com/ultrajson/ultrajson

**Comment by curiousleo** [comment]
The SQLite extension json1 contains a JSON parser too: https://github.com/jart/cosmopolitan/blob/5df3e4e7a898d223ce9bd646e37345ef7c54f84e/third_party/sqlite3/json1.c#L791

**Comment by jart** [comment]
redbean 2.0.11 now has a [`DecodeJson` function](https://redbean.dev/#DecodeJson). Enjoy! Please let us know if there's any issues with it.
