### ISSUE TITLE
Some complex binaries will not run when built in dbg mode under windows

### ISSUE THREAD

**Issue by Keithcat1** [jart/cosmopolitan#284]
From WSL:
make -j4 MODE=dbg -O o/dbg/third_party/quickjs
Then from the windows command line:
o/dbg/third_party/quickjs/qjs.com
Instead of a JS REPL appearing, the process exited after a second without sending any output to the terminal. This also seems to happen with Python. I believe that hello world programs can run with asan enabled though.

**Comment by pkulchenko** [comment]
I wonder if you can add `--ftrace` support as suggested [here](https://github.com/jart/cosmopolitan/issues/97#issuecomment-790083959) to see where it's looping. It helped me troubleshoot a similar issue with LuaJIT, as discussed in #272.

**Comment by Keithcat1** [comment]
Actually, it seems to have been fixed recently. I'll reopen it if this comes back.
