### ISSUE TITLE
redbean: hiding `.lua` extensions in URLs

### ISSUE THREAD

**Issue by 0ihsan** [jart/cosmopolitan#290]

**Comment by pkulchenko** [comment]
@0ihsan, can you clarify what you mean by this? Do you mean hiding files with .lua extension in the listing? Or being able to use URL `/mypage` instead of `/mypage.lua`? Or something else?

**Comment by pkulchenko** [comment]
Something like this should do then:

```lua
OnHttpRequest = function()
  local path = GetPath()
  if not RoutePath() and GetAssetSize(path..".lua") then
    RoutePath(path..".lua")
  else
    Route()
  end
end
```

**Comment by 0ihsan** [comment]
That worked. Now, I realise that init.lua runs on every page even if they don't exist. This opens up many doors. Thanks.
