### ISSUE TITLE
Memory quota too tight when building pythontester

### ISSUE THREAD

**Issue by jacereda** [jart/cosmopolitan#296]
Building on NixOS I had to add in python.mk:

```
o/$(MODE)/third_party/python/pythontester.com.dbg: QUOTA += -M512m
```

**Comment by jart** [comment]
Thanks for your patience. The quota is increased globally. New nightlies have been pushed to https://justine.lol/cosmopolitan/download.html Thanks for supporting us NixOS! Let me know if you need a semver release.
