### ISSUE TITLE
noinline attribute conflicts

### ISSUE THREAD

**Issue by vshymanskyy** [jart/cosmopolitan#310]
When trying to define my own macro for `__attribute__((noinline))`, getting this error:
```
In file included from <command-line>:
./cosmopolitan/cosmopolitan.h:533:18: error: expected ‘)’ before ‘__attribute__’
  533 | #define noinline __attribute__((__noinline__))
      |                  ^~~~~~~~~~~~~
../../source/m3_config_platforms.h:77:40: note: in expansion of macro ‘noinline’
   77 | #  define M3_NOINLINE   __attribute__((noinline))
      |                                        ^~~~~~~~
../../source/m3_compile.c:25:8: note: in expansion of macro ‘M3_NOINLINE’
   25 | static M3_NOINLINE
      |        ^~~~~~~~~~~
compilation terminated due to -Wfatal-errors.
```

As a workaround, I can do this:
```
#  if defined(noinline)
#    define M3_NOINLINE   noinline
#  else
#    define M3_NOINLINE   __attribute__((noinline))
#  endif
```

**Comment by pkulchenko** [comment]
@vshymanskyy, yes, it's an issue. This already [came up previously in the context of LuaJIT discussion](https://github.com/jart/cosmopolitan/issues/272#issuecomment-921654759). @ahgamut, do you want to submit a PR to fix this, as you mentioned earlier?

**Comment by ahgamut** [comment]
I did a find-and-replace to change `noinline` to `dontinline` but the change led to a complaint in a chibicc compilation `o/tokenize.chibicc.o`

```
libc/integral/c.inc:250: #define dontinline __attribute__((__noinline__))
                                                           ^ unknown function attribute
third_party/chibicc/tokenize.c:123: dontinline int read_ident(char *start) {
                                    ^ unknown function attribute
`make MODE= -j4 o//third_party/chibicc/tokenize.chibicc.o` exited with 1:
o//third_party/chibicc/chibicc.com.dbg -fno-common -include libc/integral/normalize.inc -DIMAGE_BASE_VIRTUAL=0x400000 -c -o o//third_party/chibicc/tokenize.chibicc.o third_party/chibicc/tokenize.c
```

Also I thought it was `__atttribute__((noinline))`? What difference do the underscores make?

**Comment by jart** [comment]
@ahgamut  The underscores simply help avoid conflicts. I'm surprised chibicc isn't working with `__noinline__`. We should fix that.

@vshymanskyy Please accept our apologies for the inconvenience. Playing fast and loose with names helped the project be rapidly developed. However as it grows the user needs to be the one in charge of names, so we're working to resolve these conflicts by either:

1. Adding underscore prefixes to the non-standard names we've defined, or
2. Using highly creative names, e.g. `printfesque`, that don't appear elsewhere

In any case thanks for the report and we'll do the necessary refactorings shortly. @ahgamut let me know if you need my help troubleshooting chibicc consume_attribute().

**Comment by ahgamut** [comment]
> The underscores simply help avoid conflicts. I'm surprised chibicc isn't working with __noinline__. We should fix that.

chibicc does work with `__noinline__`. 
the chibicc parser checks for attributes by removing the underscores and then checking for `noinline`, which I had blindly changed by find-and-replace.

Anyways I submitted #312, it uses `dontinline` instead of `noinline`.

**Comment by jart** [comment]
Now that https://github.com/jart/cosmopolitan/pull/312 is in I'm pushing new binaries to the website which are available here:

- https://justine.lol/cosmopolitan/cosmopolitan.zip
- https://justine.lol/cosmopolitan/download.html

Let me know if you need a semver release on GitHub for your CI system. In which case we might call it 2.0 due to the breaking change with the `/zip/` vs. old `zip:path` way of doing things.
