### ISSUE TITLE
the many faces of ape?

### ISSUE THREAD

**Issue by coderofsalvation** [jart/cosmopolitan#319]
```bash
$ file hello.com # https://justine.lol/hello.com
hello.com: ELF 64-bit LSB executable, x86-64, version 1 (FreeBSD), for OpenBSD, statically linked, corrupted section header size
```

```bash
$ file redbean.com # https://redbean.dev/redbean-1.4.com
redbean.com: DOS/MBR boot sector
```

Can somebody explain the difference?
Is it possible to compile redbean.com, so that it identifies itself like hello.com too (ELF 64bit) on 64bit linux?
(reason: for some reason docker gets confused by redbean.com, but not hello.com)

**Comment by ahgamut** [comment]
redbean restores MZ header after startup: refer #202, [this comment](https://github.com/jart/cosmopolitan/issues/202#issuecomment-873370865)

**Comment by coderofsalvation** [comment]
```bash
zip -d redbean.com .ape
ls -la /redbean.com
zip -sf redbean.com
bash ./redbean.com -h
```

gotcha..thanks
