### ISSUE TITLE
cosmopolitan 'com'tainers

### ISSUE THREAD

**Issue by coderofsalvation** [jart/cosmopolitan#329]
> Btw. does a `o/tool/build/comtainer.com` utility already exist? (see explanation below)

I can't get this to work..it doesn't find the embedded `.boot` (it errors instead with `.boot not found`).
The idea is simple: recursive (re)distribution and (re)use of cosmopolitan binaries: 

```
$ o/tool/build/comtainer.com myapp.com ~/projects/myapp/*
$ unzip -l myapp.com
.boot               <--- this is the 'main' of the app, which runs `#/bin/sh redbean.com & ; lua.com test.lua &`
redbean.com
lua.com
test.lua
```

> why: COMtainers easify polyglot application-collaboration and speeds up the development cycle by not having to deal with docker-plumbing or nixos complexity. Containerization (using zip) is one of the USP's of redbean imho.

## My attempt

```c
$ cat bundle.c
STATIC_YOINK("zip_uri_support");
STATIC_YOINK("usr/share/zoneinfo/Beijing");
STATIC_YOINK(".boot");

#define bufsize 128

void main(){
  showcrashreports();
  FILE *f = fopen("/zip/.boot", "r");
  if( f == -1){              
    printf(".boot not found\n");
    return;      
  }              
  close(f);        
  system("/zip/.boot")
}

$ cat make

APP=myapp
SRC="main.c"
[[ ! -f cosmopolitan.zip ]] && { wget https://justine.lol/cosmopolitan/cosmopolitan.zip; }
unzip -o cosmopolitan.zip 
gcc -g3 -Og -static -nostdlib -nostdinc -fno-pie -no-pie -mno-red-zone -pg \
    -fno-omit-frame-pointer -pg -mnop-mcount  \
    -o $APP.com.dbg ${SRC} -fuse-ld=bfd -Wl,-T,ape.lds \
    -include cosmopolitan.h crt.o ape.o cosmopolitan.a
objcopy -S -O binary $APP.com.dbg $APP.com && ls -la $APP.com
zip $APP.com .boot        # I think this is needed since the STATIC_YOINK did not include .boot
unzip -l $APP.com
```

> if somebody want's to collaborate on this idea let me know.

**Comment by pkulchenko** [comment]
Leon, I have a similar idea, but it's all built around redbean, as it already includes Lua, sqlite, and integrates http(s) access. I've recently submitted a patch to expose -e option to run arbitrary Lua code (for example, to executed bundled Lua asset when launched from the command line).

In general, if you provide .init.lua that does `os.exit()` in the end, then the webserver itself won't start, but everything else will already be established. You can run any bundled script, as you'd do with a standalone Lua interpreter, so I see this as a convenient way to bundle and distribute Lua applications. You can also pass additional parameters (or use -e option) to further customize the script execution.

**Comment by coderofsalvation** [comment]
I'm experimenting with your `os.exit()` hint now (which does open up more possibilities, so thanks for that).
Still I think a barebones wrapper of this comtainer approach (for lack of a better word) could still be interesting, and seems to be a lowhanging fruit.
Just think about how easy it would be so setup a micro-unix image, compared to creating docker-images:

```shell
$ echo -e "bin" > .path                                            # in C: setenv("PATH", ....)
$ cp mysql3.com redbean.com lua.com bin/.         # copy stuff your comtainer actually uses
$ cat > .boot                                                            # in C: system("./.boot")
#!/bin/sh
redbean.com &                                                        # your redbean 
while sleep 60s; do lua.com scheduler.lua; done    # scheduler
$ comtainer ../myapp.com .
$ ../myapp.com
running redbean at 8080
scheduling!
```

The only issue with this approach is the `/bin/sh` dependency.
I do agree that lua would be a better first-class citizen for this kind of scripting (redbean). 
However, are background processes (like in `.boot`) even possible with `.init.lua` and `os.exit()`?
I've read something about coroutines, but could not get any background processes to launch (maybe I'm missing something?).

> In other words, if redbean is going to be the ultimate COMtainer including scripting language, then how to run multiple processes with it by simply invoking `./redbean.com` once?

**Comment by pkulchenko** [comment]
> However, are background processes (like .boot) even possible with .init.lua and os.exit()?
> I've read something about coroutines, but could not get any background processes to launch (maybe I'm missing something?).

Coroutines are executed within the same process, so they are not going to help you here (they are used for cooperative multitasking with only one executed at a time). You should still be able to use `os.execute()` to launch an external process from redbean (although it doesn't work for me on Windows, likely due to limited fork support there).

> how hard is it to build a Sleep( ) and background feature (Start('./foo',{bg=true}) instead of &) for lua?

@jart and I have been discussing exposing Fork() to Lua or even something more high level to implement cron-like features:

```
SetSchedule({
  ["0 0 * * *"] = function() print("midnight") end,
  ["0 12 * * *"] = function() print("noon") end,
})
```

Still `os.execute("cmd &")` should allow you to execute external commands in background.

> what about a ZipExecute {"bin/qjs.com", "myscript.js" }

Yes, that's what `os.execute()` would do. Does it work for you when you launch run from redbean.com or lua.com on your system?

**Comment by coderofsalvation** [comment]
```
SetSchedule({
  ["0 0 * * *"] = function() print("midnight") end,
  ["0 12 * * *"] = function() print("noon") end,
})
```

> that would be awesome, even a `Sleep` or `setInterval` would be ok for me already. 

> Yes, that's what os.execute() would do. Does it work for you when you launch run from redbean.com or lua.com on your system?

ah yes that works..awesome, didn't knew `os.execute` did that out of the box (I was fiddling with `/zip/*` paths but I guess you dont need that here).

Well I think I'm just going to keep an eye on those efforts, and do some more tests with `os.execute` then.
Thx for elaborating on it.
I'll close this, but we can always re-open this issue in case needed.

**Comment by pkulchenko** [comment]
> that would be awesome, even a Sleep or setInterval would be ok for me already.

Yes, there is [Sleep](https://redbean.dev/#Sleep) already; is that the one you were looking for?
