### ISSUE TITLE
redbean segfaults on Linux x86_64

### ISSUE THREAD

**Issue by trholding** [jart/cosmopolitan#344]
redbean.com when built from source segfaults on Linux x86_64 (Kernel 5.15.3-arch1-1)

*** Update: The binary downloaded from your website also segfaults.
*** Filetype before executing:
*** [linux@linux cosmopolitan]$ file o//tool/net/redbean.com 
*** o//tool/net/redbean.com: DOS/MBR boot sector
*** Tested on Windows 11 and works fine on windows

CLI Output:

```
[linux@linux cosmopolitan]$ o//tool/net/redbean.com -vv
Segmentation fault (core dumped)
[linux@linux cosmopolitan]$ file o//tool/net/redbean.com 
o//tool/net/redbean.com: ELF 64-bit LSB executable, x86-64, version 1 (FreeBSD), for OpenBSD, statically linked, no section header

```
Debug version works

My default compiler is Clang. But I think that como ships with its own gcc-musl.

Further CLI:

```
[linux@linux cosmopolitan]$ rm o//tool/net/redbean.com 
[linux@linux cosmopolitan]$ make -j8 o//tool/net/redbean.com
♥cosmo
     5,116⏰     4,966⏳   3,032k   3,184iop o/third_party/gcc/bin/x86_64-linux-musl-objcopy -S -O binary o//tool/net/redbean.com.dbg o//tool/net/redbean.com
    11,122⏰    10,960⏳   3,316k   3,240iop o//third_party/infozip/zip.com -qj o//tool/net/redbean.com o//tool/net/.ape tool/net/help.txt tool/net/.init.lua tool/net/favicon.ico tool/net/redbean.png
[linux@linux cosmopolitan]$ o//tool/net/redbean.com -vv
Segmentation fault (core dumped)
```

Strace:

```
[linux@linux cosmopolitan]$ strace o/tool/net/redbean.com
execve("o/tool/net/redbean.com", ["o/tool/net/redbean.com"], 0x7ffe86381310 /* 81 vars */) = 0
mmap(0x6ffffffe0000, 262144, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS|MAP_GROWSDOWN, -1, 0) = 0x6ffffffe0000
mprotect(0x6ffffffe0000, 4096, PROT_NONE) = 0
newfstatat(AT_FDCWD, "o/tool/net/redbean.com", {st_mode=S_IFREG|0755, st_size=1657367, ...}, 0) = 0
getcwd("/home/linux/NOSTROMO/COSMO/cosmopolitan", 1023) = 48
ioctl(1, TCGETS, {B38400 opost isig icanon echo ...}) = 0
getrandom(NULL, 0, 0)                   = 0
mmap(0x100080000000, 65536, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x100080000000
mmap(0x100080010000, 196608, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x100080010000
sigaltstack({ss_sp=0x1000800023a0, ss_flags=0, ss_size=131072}, NULL) = 0
rt_sigaction(SIGQUIT, {sa_handler=0x510871, sa_mask=~[QUIT ILL TRAP ABRT BUS FPE SEGV PIPE], sa_flags=SA_RESTORER|SA_ONSTACK|SA_NODEFER|SA_SIGINFO, sa_restorer=0x546a10}, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=0}, 8) = 0
rt_sigaction(SIGFPE, {sa_handler=0x51087c, sa_mask=~[QUIT ILL TRAP ABRT BUS FPE SEGV PIPE], sa_flags=SA_RESTORER|SA_ONSTACK|SA_NODEFER|SA_SIGINFO, sa_restorer=0x546a10}, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=0}, 8) = 0
rt_sigaction(SIGILL, {sa_handler=0x510887, sa_mask=~[QUIT ILL TRAP ABRT BUS FPE SEGV PIPE], sa_flags=SA_RESTORER|SA_ONSTACK|SA_NODEFER|SA_SIGINFO, sa_restorer=0x546a10}, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=0}, 8) = 0
rt_sigaction(SIGSEGV, {sa_handler=0x510892, sa_mask=~[QUIT ILL TRAP ABRT BUS FPE SEGV PIPE], sa_flags=SA_RESTORER|SA_ONSTACK|SA_NODEFER|SA_SIGINFO, sa_restorer=0x546a10}, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=0}, 8) = 0
rt_sigaction(SIGTRAP, {sa_handler=0x51089d, sa_mask=~[QUIT ILL TRAP ABRT BUS FPE SEGV PIPE], sa_flags=SA_RESTORER|SA_ONSTACK|SA_NODEFER|SA_SIGINFO, sa_restorer=0x546a10}, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=0}, 8) = 0
rt_sigaction(SIGABRT, {sa_handler=0x5108a8, sa_mask=~[QUIT ILL TRAP ABRT BUS FPE SEGV PIPE], sa_flags=SA_RESTORER|SA_ONSTACK|SA_NODEFER|SA_SIGINFO, sa_restorer=0x546a10}, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=0}, 8) = 0
rt_sigaction(SIGBUS, {sa_handler=0x5108b3, sa_mask=~[QUIT ILL TRAP ABRT BUS FPE SEGV PIPE], sa_flags=SA_RESTORER|SA_ONSTACK|SA_NODEFER|SA_SIGINFO, sa_restorer=0x546a10}, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=0}, 8) = 0
rt_sigaction(SIGPIPE, {sa_handler=0x5108be, sa_mask=~[QUIT ILL TRAP ABRT BUS FPE SEGV PIPE], sa_flags=SA_RESTORER|SA_ONSTACK|SA_NODEFER|SA_SIGINFO, sa_restorer=0x546a10}, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=0}, 8) = 0
sched_yield()                           = 0
clock_gettime(CLOCK_REALTIME, {tv_sec=1641069519, tv_nsec=382211569}) = 0
nanosleep({tv_sec=0, tv_nsec=100000}, NULL) = 0
clock_gettime(CLOCK_REALTIME, {tv_sec=1641069519, tv_nsec=382475221}) = 0
sched_yield()                           = 0
clock_gettime(CLOCK_REALTIME, {tv_sec=1641069519, tv_nsec=382588017}) = 0
nanosleep({tv_sec=0, tv_nsec=100000}, NULL) = 0
clock_gettime(CLOCK_REALTIME, {tv_sec=1641069519, tv_nsec=382845720}) = 0
sched_yield()                           = 0
clock_gettime(CLOCK_REALTIME, {tv_sec=1641069519, tv_nsec=382988830}) = 0
nanosleep({tv_sec=0, tv_nsec=100000}, NULL) = 0
clock_gettime(CLOCK_REALTIME, {tv_sec=1641069519, tv_nsec=383246940}) = 0
sched_yield()                           = 0
clock_gettime(CLOCK_REALTIME, {tv_sec=1641069519, tv_nsec=383359827}) = 0
nanosleep({tv_sec=0, tv_nsec=100000}, NULL) = 0
clock_gettime(CLOCK_REALTIME, {tv_sec=1641069519, tv_nsec=383617007}) = 0
clock_gettime(CLOCK_REALTIME, {tv_sec=1641069519, tv_nsec=383675786}) = 0
rt_sigprocmask(SIG_BLOCK, ~[], [], 8)   = 0
openat(AT_FDCWD, "/home/linux/NOSTROMO/COSMO/cosmopolitan/o/tool/net/redbean.com", O_RDONLY) = 3
fstat(3, {st_mode=S_IFREG|0755, st_size=1657367, ...}) = 0
mmap(0x100080040000, 1657367, PROT_READ, MAP_SHARED|MAP_FIXED, 3, 0) = 0x100080040000
munmap(0x100080040000, 1507328)         = 0
close(3)                                = 0
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
dup(2)                                  = 3
close(3)                                = 0
mmap(0x100080040000, 65536, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x100080040000
dup(2)                                  = 3
close(3)                                = 0
mmap(0x100080050000, 65536, PROT_READ|PROT_WRITE, MAP_SHARED|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x100080050000
openat(AT_FDCWD, "/home/linux/NOSTROMO/COSMO/cosmopolitan/o/tool/net/redbean.com", O_RDONLY) = 3
fstat(3, {st_mode=S_IFREG|0755, st_size=1657367, ...}) = 0
newfstatat(AT_FDCWD, "/home/linux/NOSTROMO/COSMO/cosmopolitan/o/tool/net/redbean.com", {st_mode=S_IFREG|0755, st_size=1657367, ...}, 0) = 0
mmap(0x1000801e0000, 1657367, PROT_READ, MAP_PRIVATE|MAP_FIXED, 3, 0) = 0x1000801e0000
dup(2)                                  = 4
close(4)                                = 0
close(3)                                = 0
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f580ef97000
mmap(NULL, 12288, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f580ef94000
mprotect(0x7f580ef97000, 4096, PROT_READ|PROT_EXEC) = 0
munmap(0x400000, 1544192)               = 0
munmap(0x579000, 12288)                 = 0
open("/home/linux/NOSTROMO/COSMO/cosmopolitan/o/tool/net/redbean.com", O_RDWR) = -1 ETXTBSY (Text file busy)
mmap(0x400000, 1544192, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_FIXED, -26, 0) = -1 EBADF (Bad file descriptor)
mmap(0x579000, 12288, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x579000
--- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_MAPERR, si_addr=0x545d82} ---
--- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_MAPERR, si_addr=0x510892} ---
...
--- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_MAPERR, si_addr=0x510892} ---
--- SIGSEGV {si_signo=SIGSEGV, si_code=SI_KERNEL, si_addr=NULL} ---
+++ killed by SIGSEGV (core dumped) +++
Segmentation fault (core dumped)
```

**Comment by pkulchenko** [comment]
@trholding, it appears to be failing on opening the redbean executable itself with O_RDRW permissions (inside the OpenExecutable call). Is your case similar in any way to #233? If so, you can try removing .ape file from the redbean archive.

You can also try the following patch (which should eliminate the SIGSEGV, even though it doesn't fix the underlying issue):

```diff
diff --git a/tool/net/redbean.c b/tool/net/redbean.c
index 0d5e4d20f..51163c4cf 100644
--- a/tool/net/redbean.c
+++ b/tool/net/redbean.c
@@ -7035,8 +7035,7 @@ void RedBean(int argc, char *argv[]) {
   zpath = program_executable_name;
   CHECK_NE(-1, (zfd = open(zpath, O_RDONLY)));
   CHECK_NE(-1, fstat(zfd, &zst));
-  OpenZip(true);
-  RestoreApe();
+  if (OpenZip(true)) RestoreApe();
   SetDefaults();
   GetOpts(argc, argv);
   LuaInit();
```

**Comment by trholding** [comment]
@pkulchenko removing the .ape from redbean, made it run ok, but it won't work on win after that I believe, so it is a temp solution.

On the other hand, I tested this on a Manjaro Distro, identical hardware, but kernel version 5.14.10-1 and worked flawlessly!

I think issue #233 is not related to this, I am not sure - maybe #233 could be related to VSYSCALL emulation not enabled in kernel...

**Comment by pkulchenko** [comment]
> On the other hand, I tested this on a Manjaro Distro, identical hardware, but kernel version 5.14.10-1 and worked flawlessly!
> I think issue #233 is not related to this, I am not sure - maybe #233 could be related to VSYSCALL emulation not enabled in kernel...

That I'm not sure about, but clearly something doesn't allow the file to opened for writing, so you most likely won't be able to restore the APE header until the underlying issue is resolved/found. Not being able to run on Windows may be a problem, but do you need to run your program on Windows after running it on Linux? The patches I suggested would avoid sigsegv even though they would still keep the modified image.

**Comment by trholding** [comment]
@pkulchenko Thank's for the suggestion. I'll apply your patch. That way the only problem would be that I'll have to just put a note in future applications built with this will not run on windows if executed in linux distros which does not support .ape . In that case it is also trivial to ship a helper script that adds back a .ape header if user desires to make it work in windows again or maybe some other kludge. Thanks again for the awesome work!

**Comment by trholding** [comment]
As this issue is a edge case and rarely encountered in real world situations and the patch provides a satisfactory work around, I am closing this issue.

**Comment by pkulchenko** [comment]
@igravious, does the patch proposed in https://github.com/jart/cosmopolitan/issues/344#issuecomment-1003897919 help in your case? What's your Linux version?

Here is an [interesting and relevant discussion on ETXTBSY](https://lwn.net/Articles/866493/). Judging by the strace results, [re-opening the file for writing fails in openexecutable.S](https://github.com/jart/cosmopolitan/blob/master/libc/runtime/openexecutable.S#L123) despite the segment already unmapped, but I don't quite understand *why* it happens. I don't have this failure on my linux system (running Ubuntu under WSL2), so I can't test the fix, but it's not clear to me why the code uses `$PAGESIZE` where I'd expect `$ape_rom_filesz` to be used. It does seem like it's possible that not the entire file unmapped, which creates an issue with its re-opening (at least on some systems).

**Comment by igravious** [comment]
@pkulchenko 

Howdy. Thanks for getting back to me. I tried the patch proposed in [#344 (comment)](https://github.com/jart/cosmopolitan/issues/344#issuecomment-1003897919) and it did nothing for me. Same deal. Segfault.

I'm running **Pop!_OS 21.10** which as you know is an Ubuntu derivative. Linux kernel version **5.15.23-76051523-generic**.

_News Flash!_ The debug version `o//tool/net/redbean.com.dbg` works, both with and without the patch. What's the debug version doing that the non-debug version isn't – or perhaps we're talking about what is the non-debug version doing that the debug version isn't.

Tbh, I don't really understand your “Here is an interesting and relevant discussion […]” musing has to do with Redbean :(

Ubuntu under WSL2 is very cool tech from the little I've played around with it.

**Comment by pkulchenko** [comment]
@igravious, the discussion I referenced is relevant, because the opening of redbean archive for writing fails with `ETXTBSY` (which is the topic of the discussion). The .dbg file doesn't have this problem, because `RestoreApe` has an early return for .dbg files not attempting to restore its .ape part (which is where the `sigsegv` happens).

Can you try this branch and let me know if this fixes the `SIGSEGV` for you: https://github.com/pkulchenko/cosmopolitan/tree/redbean-save-ape? You're likely to see `(srvr) can't restore .ape` message in the logs, but this is expected.

**Comment by pkulchenko** [comment]
@igravious, let me know if you had a chance to check on the patch and if that fixed the issue for you, as I'd like to merge it if it did. Thanks!

**Comment by pkulchenko** [comment]
Pushed another update based on a review from @jart.

**Comment by igravious** [comment]
@pkulchenko is there a way to `make clean` ?

**Comment by pkulchenko** [comment]
You can just delete the entire folder to clean `rm o//tool/net/`.

Yes, it appears to be working, as it should show you the message `can't restore .ape` without crashing. Thank you for checking!

**Comment by igravious** [comment]
No worries. If there's anything else you want me to test I'd be more than happy to help out.

**Comment by igravious** [comment]
@pkulchenko very nice :) awesome work :)
