### ISSUE TITLE
Problem when using zlib

### ISSUE THREAD

**Issue by Nanguage** [jart/cosmopolitan#345]
Hi, I noticed that there are zlib functions provided in the [document](https://justine.lol/cosmopolitan/documentation.html#gzread), but there are some problem when I try to using them.

test.c:
```C
#include "cosmopolitan.h"

int main()
{
        gzFile fp;
        fp = gzopen("./test.c", "r");
        return 0;
}

```

Compile using the command in readme:
```bash
$ gcc -g -Os -static -fno-pie -no-pie -mno-red-zone -nostdlib -nostdinc -fno-omit-frame-pointer -pg -mnop-mcount -o test.dbg test.c  -Wl,--gc-sections -fuse-ld=bfd -Wl,-T,ape.lds -include cosmopolitan.h crt.o ape.o cosmopolitan.a
/tmp/cclqVpUJ.o: In function `main':
/home/wzxu/tmp/cosmopolitan/test.c:6: undefined reference to `gzopen'
collect2: error: ld returned 1 exit status

```

**Comment by jart** [comment]
Thanks for the report. New nightlies pushed to https://justine.lol/cosmopolitan/download.html which now includes these gz functions.
