### ISSUE TITLE
Support binfmt_misc

### ISSUE THREAD

**Issue by Hugobros3** [jart/cosmopolitan#350]
Many (most?) distributions WINE packages come with file associations through the `binfmt_misc` interface of the kernel. These use the magic bytes of windows executables to rewrite `./hello.com` as `wine ./hello.com`, and since this works at the kernel level I don't know of any easy way to bypass it, short of disabling the whole thing: `echo -1 >/proc/sys/fs/binfmt_misc/status`. 

Which is obviously both not ideal for the portability aspect, and also because it requires disabling useful functionality (as a degenerate mouse user, I like clicking on executables, fight me). Maybe you have yet another trick to work around this ?

**Comment by trholding** [comment]
If you are on ubuntu the fifth answer from the following page may contain the solution to prevent exe running with wine on double click: 

https://askubuntu.com/questions/344088/how-to-ensure-wine-does-not-auto-run-exe-files

If on another distro, apply something similar.

**Comment by Hugobros3** [comment]
I'm not asking how to run APE binaries with WINE installed, I already figured that bit out.

I'm reporting that this is an issue because I believe the default behavior for cosmo binaries should be to run as native binaries even with WINE installed (which is very common), without any special user manipulation. I think having to do these defeats the point of an "actually portable executable" - hopefully some more magic number trickery can be applied here.

**Comment by tkchia** [comment]
Hello @Hugobros3,

I do see a `wine-binfmt` package for Ubuntu, but apparently it must be installed _separately_, and does not automatically go together with `wine`.  Indeed the `wine-binfmt` package description specifically says:

>  WARNING:  This increases the risk of inadvertently launching Windows malware, so please make sure that you understand the security risks before blindly installing this package.
> 
> This feature is probably most interesting for automatic software testing. Desktop users usually don't need it, so don't install wine-binfmt unless you know that you need it.  Refer to Wine's `README.debian` for more information.

I am not sure how other Linux distributions do things though.

Thank you!

**Comment by tkchia** [comment]
Hello @Hugobros3,

Also, in the meantime, `kernel.org` has some [information](https://www.kernel.org/doc/html/latest/admin-guide/binfmt-misc.html) on how to control the `binfmt_misc` special purpose filesystem, at least at the kernel level.

Thank you!

**Comment by Hugobros3** [comment]
Hi, Fedora seems to ship the package by default at least - haven't tried on Arch yet. Interesting that Ubuntu doesn't ship this.

**Comment by tkchia** [comment]
Hello @Hugobros3,

Hmm.  On my system at least, the `binfmt_misc` entry registered by `wine-binfmt` will glom onto _every_ executable that starts with the bytes `MZ` (`0x4d 0x5a`).  This unfortunately does not leave much leeway for any magic number trickery to avoid going through Wine.

Thank you!

**Comment by takase1121** [comment]
Here's an idea: Since APE detects the OS and then modifies itself with the appropriate headers, is it possible for the shim to somehow detect if its running through wine (https://stackoverflow.com/a/42333249) and account for that when writing the headers?

**Comment by jart** [comment]
Hey everyone. I think the optimal solution to this problem is to support binfmt_misc. Since binfmt_misc is what's causing WINE to run your APE binaries. So the only thing we can do, is play the binfmt_misc game too. I've got some local work in flight that will be published soon. It goes really fast too.

**Comment by pkulchenko** [comment]
@jart, is this still an issue with the new APE approach or should this be closed?

**Comment by jart** [comment]
This is fixed thanks to our new APE Loader https://justine.lol/apeloader/ which supports binfmt_misc.

**Comment by jart** [comment]
Just run `ape/apeinstall.sh` on this repo!

**Comment by tkchia** [comment]
Hello @jart,

Regarding the `binfmt_misc` unregistration, you mention in `ape/apinstall.sh`:

```
  # TODO: we need better uninstall recommendations
  #       the following works fine for justine
  #       but might remove unrelated software?
  # sudo sh -c 'echo -1 >/proc/sys/fs/binfmt_misc/status'
```

I have tried
```
$ sudo sh -c 'echo -1 >/proc/sys/fs/binfmt_misc/APE'
```
on my system, and it works &mdash; it unregisters only the `binfmt_misc` binary type entry for `APE`, and leaves the other entries alone.  (This procedure is mentioned in passing in the `kernel.org` [write-up](https://www.kernel.org/doc/html/latest/admin-guide/binfmt-misc.html).)

Hope this helps. :slightly_smiling_face: 

Thank you!

**Comment by jart** [comment]
Brilliant! Thank you for bringing that to my attention. It seems so obvious now that you've explained it. I'll update the docs.

**Comment by jart** [comment]
Wow can we use that? Where does _wexecv() come from?
