### ISSUE TITLE
redbean: including SQLite features like ALTER

### ISSUE THREAD

**Issue by stephenbenedict** [jart/cosmopolitan#353]
From the main redbean.dev page, I understand that SQLite features such as ALTER, VACUUM, ANALYZE, etc. have been disabled since they do not make sense for production serving. However, I am interested in building a kind of IDE with redbean and Lua where I can modify the SQLite schema as well. Would this be possible?

**Comment by pkulchenko** [comment]
@stephenbenedict, looks like you should be able to add a necessary define to the sqlite makefile under `$(THIRD_PARTY_SQLITE3_A_OBJS)` ([somewhere at line 163 may work](https://github.com/jart/cosmopolitan/blob/d6a039821f927cc81b71e11f21599ff93e1fed62/third_party/sqlite3/sqlite3.mk#L163)). You can check how it's configured for `$(THIRD_PARTY_SQLITE3_SHELL_OBJS)` in the same file. Also see #216 for a similar question.

I'd be curious about the IDE, as I've been developing ZeroBrane Studio Lua IDE for a long time (my email is in the profile if you want to connect).

**Comment by stephenbenedict** [comment]
@pkulchenko Thanks for the tip! I do not have access to a Linux machine currently to compile redbean so I cannot test this right away, but I will see if I can get it to work.

**Comment by pkulchenko** [comment]
You can also use WSL2 under windows (10+) if you have access to that. Let me know if you run into any issues and I'll take a look.

**Comment by stephenbenedict** [comment]
Finally getting around to testing this, but I cannot find the appropriate define/flag to enable ALTER, VACUUM, ANALYZE, etc. I've been looking through the SQLite documentation, but can't seem to find it. Any pointers would be helpful.

**Comment by pkulchenko** [comment]
I think ALTER is already included, as I remember issuing ALTER commands, which I use.

VACUUM is available unless `-DSQLITE_OMIT_VACUUM` is set, which I don't see being set in `sqlite3.mk`, so it should be enabled as well.

Similarly, ANALYZE should be enabled unless `-DSQLITE_OMIT_ANALYZE` is set, which I don't see either.

I tested ALTER and VACUUM and they both seem to be working with redbean.

@jart, I'd keep ALTER for sure, but should we disable VACUUM and ANALYZE? I'd also like to add JSON1, which doesn't seem to be included.

**Comment by stephenbenedict** [comment]
Thanks for confirming! Redbean docs currently state ALTER, VACUUM, and ANALYZE ARE disabled (https://redbean.dev/#lsqlite3) so maybe that should be updated.

**Comment by jart** [comment]
Docs updated.
