### ISSUE TITLE
Redbean: Cannot open assembly './redbean.com': File does not contain a valid CIL image.

### ISSUE THREAD

**Issue by catwell** [jart/cosmopolitan#356]
I have downloaded redbean as described on its homepage on my Arch Linux laptop and I get this error:

> Cannot open assembly './redbean.com': File does not contain a valid CIL image.

Any idea where it comes from?

![Screenshot from 2022-02-17 17-55-54](https://user-images.githubusercontent.com/221332/154531358-00e6c9d9-bc9a-4a05-88c2-ececcdba0f1a.png)

I do not have that issue with `redbean.com.dbg`. If I rename `redbean.com` I still have the issue so it is not the filename.

**Comment by pkulchenko** [comment]
@catwell, can you try launching it using bash: `bash redbean.com`? Judging by [this answer](https://superuser.com/questions/489328/file-does-not-contain-a-valid-cil-image), it looks like it's coming from the process launcher.

**Comment by catwell** [comment]
`bash redbean.com` results in "redbean.com: line 8: : No such file or directory"

Thanks for the link to the comment, I ran it and now `./redbean.com`... segfaults. Progress!

![Screenshot from 2022-02-17 18-28-05](https://user-images.githubusercontent.com/221332/154537240-4ac6c6de-55c2-4665-99c2-ef4b721b5847.png)

**Comment by pkulchenko** [comment]
@catwell, can you re-test on the current master? Per the discussion in #398, the issue may already be fixed there. Thanks!

**Comment by catwell** [comment]
@pkulchenko Sorry for the late answer.

It took me a while to figure how to build from master because I didn't have error output from the makefile, it turns out I had to install dosbox among other things. But it does work, thanks!

**Comment by pkulchenko** [comment]
ok; thank you for re-testing!

**Comment by pkulchenko** [comment]
@catwell, this should be all fixed in the recent [redbean 2.0 release](https://redbean.dev/2.0.html)

**Comment by catwell** [comment]
I tried with the latest released `redbean-2.0.8.com` and I can confirm I don't have that issue anymore, I have other issues I didn't have with the one I built from the master branch though.

- The `--assimilate` command does not work (it returns the help)

- When I try to access the server I get:

```
I2022-07-04T09:19:38.334615:tool/net/redbean.c:5844:runme:260] (req) received 1
27.0.0.1:56064 HTTP11 GET http://127.0.0.1:8080/ "" "Mozilla/5.0 (X11; Linux x8
6_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.115 Safari/537.3
6 OPR/88.0.4412.53"
0100:fixme:file:GetLongPathNameW UNC pathname L"\\\\?\\Z:\\dcs\\learn\\redbean\\2022-07-04-2dot0\\runme.com"
W2022-07-04T09:19:38+001361:tool/net/redbean.c:2276:runme:260] (rsp) 127.0.0.1:
56064 write error: ENOTSOCK/10038/Socket operation on non-socket/10038
```

**Comment by paulwratt** [comment]
`--assimilate` is mentioned in many places in the doc's, rather make it fail "gracefully" (not report as an error), after all it _is_ successful when there is nothing to `--assimilate` anyway ..

**Comment by catwell** [comment]
Confirmed, it runs it in Wine (I should have thought about that).

And when I try to `sh` it it does:

![2022-07-04_20-18](https://user-images.githubusercontent.com/221332/177203091-45f45133-2ff4-4e14-bc96-3fd6d1e11061.png)

(I don't have `ape` installed system-wide.)

**Comment by pkulchenko** [comment]
Right; assimilating it to be an ELF executable should work. There is a binfmt_misc solution for WINE discussed in #350, but it requires system-wide ape (running `ape/apeinstall.sh`). Getting an assimilated binary should be an easier solution.

**Comment by catwell** [comment]
Yeah and obviously to assimilate you need to run it with `sh`, otherwise it runs the Windows version which does not assimilate!
