### ISSUE TITLE
Redbean: Hangs until `kill -9`ed

### ISSUE THREAD

**Issue by heyarne** [jart/cosmopolitan#357]
Hi!

I stumbled over redbean and it looked very interesting to me. I wrote a small Lua script that creates a bit of dynamic HTML and I'm impressed by how fast the script executes. Developing with it locally on NixOS was lots of fun!

Trying to deploy it however something goes wrong and I'm not sure what. The server is running Centos 7:

```
# uname -srvmpio
Linux 3.10.0-1160.42.2.el7.x86_64 #1 SMP Tue Sep 7 14:49:57 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

I managed to reproduce the issue like so:

```
# wget https://redbean.dev/redbean-1.5.com -O redbean.com
# chmod +x redbean.com
# ./redbean.com -vvvv # the port doesn't matter
D2022-02-18T08:38:52.622755:tool/net/redbean.c:5341:redbean:25383] (lua) LuaRun("/.init.lua")
I2022-02-18T08:38:52+004452:tool/net/redbean.c:6700:redbean:25383] (srvr) listen http://127.0.0.1:8080
I2022-02-18T08:38:52+000177:tool/net/redbean.c:6700:redbean:25383] (srvr) listen http://100.64.143.2:8080
V2022-02-18T08:38:52+004843:tool/net/redbean.c:1709:redbean:25383] (ssl) could not find non-CA SSL certificate key pair with -addext keyUsage=digitalSignature -addext extendedKeyUsage=serverAuth
V2022-02-18T08:38:52+000060:tool/net/redbean.c:1712:redbean:25383] (ssl) could not find CA key signing key pair with -addext keyUsage=keyCertSign
V2022-02-18T08:38:52+000075:tool/net/redbean.c:1714:redbean:25383] (ssl) generating self-signed ssl certificates
D2022-02-18T08:38:52+004246:net/https/logcertificate.c:28:redbean:25383] generated EC certificate
 cert. version     : 3
 serial number     : 10:00:80:03:D6:20
 issuer name       : CN=localhost
 subject name      : CN=localhost
 issued  on        : 2022-02-17 16:38:52
 expires on        : 2023-02-19 16:38:52
 signed using      : ECDSA with SHA256
 EC key size       : 256 bits
 basic constraints : CA=false
 subject alt name  :
     dNSName : localhost
     dNSName : localhost.localdomain
     dNSName : localhost4
     dNSName : localhost4.localdomain4
     dNSName : xxxx
     iPAddress : 127.0.0.1
     iPAddress : 100.64.143.2
 key usage         : Digital Signature
 ext key usage     : TLS Web Server Authentication, TLS Web Client Authentication
V2022-02-18T08:38:52+000489:tool/net/redbean.c:574:redbean:25383] (ssl) using EC certificate "CN=localhost" for HTTPS server
```

Now, trying to get some kind of response from it, I don't see any additional log output from the redbean process. The curl log looks like this:

```
# curl -vvvv localhost:8080
*   Trying 127.0.0.1:8080...
* Connected to localhost (127.0.0.1) port 8080 (#0)
> GET / HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.81.0
> Accept: */*
>
```

… and both processes just hang indefinitely. I can't `Ctrl + C` the redbean process and at that point I have to `kill -9` it. Any idea why this happens? Thanks!

**Comment by heyarne** [comment]
Interestingly, I can execute `redbean-unsecure-1.5.com` just fine, which solves the problem (at least for me).

**Comment by heyarne** [comment]
I just did, the log gets flooded with

```
getrandom(0x70000001fc88, 8, GRND_NONBLOCK|GRND_RANDOM) = -1 EAGAIN (Resource temporarily unavailable)
```

**Comment by pkulchenko** [comment]
It looks like there is [not enough randomness/entropy for getrandom to work](https://lwn.net/Articles/800509/), but I'm not sure where exactly this call is coming from (as the caller needs to check for EAGAIN and return an error after enough attempts). Seems to be somewhere in mbedtls, but I don't see where...

**Comment by pkulchenko** [comment]
@heyarne, do you have a bit more context for getrandom calls? Can you include some calls before `getrandom`, as I'm trying to find where the calls are coming from?

**Comment by heyarne** [comment]
> @heyarne, do you have a bit more context for getrandom calls? Can you include some calls before `getrandom`, as I'm trying to find where the calls are coming from?

I have barely written a line of C in my life, I merely use redbean as it is distributed at the moment. If you offer more precise instructions on what to do I'll gladly help.

**Comment by pkulchenko** [comment]
I was just thinking maybe including some of the calls from `strace` that you see before `getrandom` calls start (15-20 lines), which may allow us to figure out the function that makes that `getrandom` call.

**Comment by heyarne** [comment]
I had call `redbean.com` like `bash -c redbean.com`, so this might be a bit noisy, but here you go: [redbean.log](https://github.com/jart/cosmopolitan/files/8187092/redbean.log)

**Comment by heyarne** [comment]
I had call `redbean.com` like `bash -c redbean.com`, so this might be a bit noisy, but here you go:
[redbean.log](https://github.com/jart/cosmopolitan/files/8187110/redbean.log)

**Comment by jart** [comment]
redbean by default will generate an SSL certificate for you at startup. On modern computers this should go fast and never block, because hardware random number generators are available. However if you run redbean on an older computer, you may need to jiggle the mouse a bit if you run it on Linux, where /dev/random is extremely conservative.

You could also generate a certificate beforehand.

```
    # generate key signing key
    openssl req -x509 -newkey rsa:2048 \
      -keyout .ca.key -out .ca.crt -days 6570 -nodes \
      -subj '/C=US/ST=CA/O=Jane Doe/CN=My Root CA 1' \
      -addext 'keyUsage = critical,cRLSign,keyCertSign'
    # install it for your linux desktop
    sudo cp .ca.crt /usr/local/share/ca-certificates/redbean.crt
    sudo update-ca-certificates
    # use the certificate
    sudo ./redbean.com -C ca.crt -K .ca.key -p 80 -p 443
    # -or-
    echo '
      ProgramCertificate(LoadAsset("/ca.crt"))
      ProgramPrivateKey(LoadAsset("/.ca.key"))
      ProgramPort(80)
      ProgramPort(443)
    ' >.init.lua
    zip redbean.com .init.lua ca.crt .ca.key
    sudo ./redbean.com
```

Another thing you can do, is use redbean-unsecure.com. That doesn't need entropy since it doesn't do SSL.

**Comment by jart** [comment]
Actually sorry quick clarification about my previous comment. redbean will still need to generate a serving key if you provide it with a key signing key. So that wouldn't fully work around the starved entropy if you can't jiggle the mouse. What you can do instead is buy a certificate, or go through the openssl tutorials on how to use your CA key to sign a certificate. **If you give redbean a normal certificate (rather than KSK) then redbean won't bother generating a certificate for SSL.** I would have included how to do that in the example, but it's hard to do with openssl and requires a lot more work than a one-liner. It's one of the reasons why redbean tries to abstract that process and make it easy using ephemeral serving keys.

**Comment by pkulchenko** [comment]
@jart, these are interesting considerations. I still think that an error should be returned after some reasonable time (2 minutes were suggested in the [link I referenced above](https://lwn.net/Articles/800509/)):

> Ts'o [suggested](https://lwn.net/ml/linux-kernel/20190912082530.GA27365@mit.edu/) adding a kind of "fail safe" flag that would let callers request that getrandom() only block for, say, two minutes; after that, the best available random numbers would be returned. But Torvalds [believes](https://lwn.net/ml/linux-kernel/CAHk-=wjyH910+JRBdZf_Y9G54c1M=LBF8NKXB6vJcm9XjLnRfg@mail.gmail.com/) that blocking by default is simply wrong. He said that any new flag should request the blocking behavior explicitly so that unthinking users get what they expect. Or perhaps an error could be returned:
> An alternative might be to make getrandom() just return an error instead of waiting. Sure, fill the buffer with "as random as we can" stuff, but then return -EINVAL because you called us too early.

I think it's fine to wait for 1-2m and then return an error with a message; the user can either increase the "wait time" or use another alternative, but right now the user is in the dark as to why this is happening.

**Comment by heyarne** [comment]
I agree that a clear error message would have helped me - maybe with some sort of comment hinting at `redbean-unsecure.com`? The hardware I'm running this on is not particularly old from what I can tell, it's running on a virtual server that I have access to in a shared hosting setting (multiple users get access to the same virtual server with individual accounts, only the admin has sudo). I think there is probably something else going on wrt why there's an issue with collecting the required entropy, but that's beyond the scope of redbean to handle. :) Thanks in any case!
