### ISSUE TITLE
redbean: allow symlinks for -D path

### ISSUE THREAD

**Issue by mischief** [jart/cosmopolitan#358]
hi, i tried to run redbean like
```
redbean.com -p 80 -D /data/git
```

but i see
```
E2022-02-19T14:07:40+000016:tool/net/redbean.c:921:redbean:1] (cfg) error: not a directory: "/data/git"
```

because /data/git is indeed a symlink.

in https://github.com/jart/cosmopolitan/blob/master/tool/net/redbean.c#L914, it seems to disallow them. is there a particular reason why?

**Comment by jart** [comment]
Thanks for the report. That's unintended. Should be an easy fix.

**Comment by mischief** [comment]
@jart it looks like there is `isdirectory` and `issymlink`, but is there a call to check if a path is a directory *or* a symlink to one that can be used? or (maybe less ideal), don't check isdirectory and let stats/opens fail later?

**Comment by pkulchenko** [comment]
@mischief, I noticed that `examples/cp.c` simply checks for `(endswith(dst, "/") || isdirectory(dst))`; we can do the same here. The other option would be to something like the following:

```
struct stat st;
fstatat(AT_FDCWD, path, &st, 0) != -1 && S_ISDIR(st.st_mode);
```

This is what `isdirectory` does (at least an equivalent of, per the comment there), just with `AT_SYMLINK_NOFOLLOW`. I think adding `endswith` may be sufficient.

**Comment by mischief** [comment]
@pkulchenko it seems like trying to call fstatat directly might break some behavior because current `isdirectory` can check the embedded zip.

i could either copy isdirectory into a modified function in redbean or add a new argument to isdirectory to allow symlink. which is preferred?

**Comment by pkulchenko** [comment]
I probably would just add `endswith(dst, "/")` check. This is what [I did in the PR I just submitted](https://github.com/pkulchenko/cosmopolitan/commit/f4cd70a9fff8ce59474c72cfd27cbb7860d6de0b#diff-a937cc5818818785e079eab14ff76fa5db080fe9bd902d1ab21aa546aa79c7d1R3529) to cover a similar case in StoreFile.

**Comment by pkulchenko** [comment]
I also considered adding new argument to isdirectory, but it would be an API change and require updating all instances of that call.

@jart, should issymlink return `st_mode` value of the target (as the "true" value) to allow testing it for its mode values? We could then just use `S_ISDIR(issymlink(path))` or something along those lines and it would still be backward compatible (assuming `st_mode` doesn't allow/have 0 as a valid value)?

**Comment by mischief** [comment]
@pkulchenko i think your change to allow symlink for -A flag in a similar fashion to -D makes sense.
