### ISSUE TITLE
redbean hang for response on windows

### ISSUE THREAD

**Issue by caizongchao** [jart/cosmopolitan#378]
Just tried red bean for a while and I really love it. I found an issue but not sure whether it's a bug or a limitation of windows platform: 

redbean 1.5, windows 10

1. open redbean.com (without args)
2. open http://127.0.0.1:8080 from browser(chrome), and then refresh several times. redbean works fine.
3. open http://127.0.0.1:8080 using curl ( curl http://127.0.0.1:8080), curl hang for response until a new request is fired from chrome.

**Comment by caizongchao** [comment]
this issue only happens in redbean downloaded from website (https://redbean.dev/redbean-1.5.com). I tried the latest git version and everything works fine.

**Comment by jart** [comment]
Glad to hear things are working for you at head. We've put a lot of work into improving the windows story recently. We'll be getting a release out soon too.
