### ISSUE TITLE
redbean – Read Data from Packaged SQLite database

### ISSUE THREAD

**Issue by dbready** [jart/cosmopolitan#379]
First of all, thanks for creating this project, it is true sorcery. However, now that I know magic is real, I want more.

Is it possible to create a single redbean blob containing both the Lua code + a SQLite database that could be read from within the hosting application? I would be willing to accept significant performance penalties and be limited to read-only access (read-write might be too much power for me to handle).

The idea strikes me as impossible, but I remembered [this project](https://phiresky.github.io/blog/2021/hosting-sqlite-databases-on-github-pages/) where the author was able to utilize range requests with a custom SQLite driver to return queries from a remote database. After struggling to get the javascript build pipeline working – I was able to make this code work against a redbean hosted SQLite database. That is to say, inside a redbean zip, there is a SQLite database, the javascript module, and a barebones HTML file which runs the javascript, which makes a call into the database, and returns the query result as json.

The author confesses this is not production grade (and my attempts to go off the beaten path immediately resulted in breaking the code), but I love the idea. Was wondering what it would take to produce a redbean native driver which could accomplish the same thing on the hosting side.

Having a single object to distribute instead of redbean + database would be interesting. I am currently considering some alternatives (pack database into the blob, extract to temp dir for reading; pack many separate .json objects we read on demand; etc), but shipping data + code as one unit could eliminate some headaches.

**Comment by jart** [comment]
Check out the [StoreAsset](https://redbean.dev/#StoreAsset) function which does exactly that. Although not with SQLite. It's just a basic object store. It's super cool but only supported on a few platforms at the moment. The focus at the moment is battletesting SQLite to make sure it's as production worthy as possible, and then moving on to the more novel approach of packing everything in the same zip. Glad you're loving the project!

**Comment by setop** [comment]
> That is to say, inside a redbean zip, there is a SQLite database, the javascript module, and a barebones HTML file which runs the javascript, which makes a call into the database, and returns the query result as json.

The think is, if the sqlite database is zipped, it must be deflated as a whole before being able to serve "range" request. This kinda defeat the purpose of "sql.js-httpvfs". Or you could compress each page individually ...
