### ISSUE TITLE
COSMOPOLITAN_C_END_  not found

### ISSUE THREAD

**Issue by gbbnfhb** [jart/cosmopolitan#38]
cosmopolitan\libc\nt\systeminfo.h
COSMOPOLITAN_C_END_  not found

**Comment by jart** [comment]
Thanks for the report! It's now fixed. The latest snapshots can be downloaded here: 

- https://justine.lol/cosmopolitan/cosmopolitan.zip
- https://justine.lol/cosmopolitan/cosmopolitan.tar.gz
