### ISSUE TITLE
odd segfault related to output + structs with array members

### ISSUE THREAD

**Issue by somebody1234** [jart/cosmopolitan#381]
`err<n>` all give segfaults, `ok<n>` all work fine. no idea what's going wrong, pretty sure they work fine with regular gcc.
using the normal command from [getting started](https://justine.lol/cosmopolitan/index.html)
```c
#include "./cosmopolitan.h"
typedef struct a { int *i; } a;
typedef struct b { long long i; } b;
void f(int a) { puts("a"); }
void g(int a) { fflush(stdout); }
int h(int a) { return 1 + 1; }
void err1(a a) { f(0); f(0); }
void err2(a a) { puts("a"); puts("b"); }
void err3(a a) { g(0); g(0); }
void ok1(b b) { f(0); f(0); }
void ok2(b b) { puts("a"); puts("b"); }
void ok3(b b) { g(0); g(0); }
void ok4(a a) { puts("a"); }
int ok5(a a) { return h(0) + h(0); }
main() {
    a a = { (int[]) { 0 } };
    b b = { 0 };
    ok3(b);
}
```

**Comment by ahgamut** [comment]
@somebody1234 can you show the error/debug output?
I'm unable to replicate the crash with the current commit of the repo (https://github.com/jart/cosmopolitan/commit/9b11206ae37e8bffbbcfa839ddd34b43c3638f80): calling all the functions works without error.

**Comment by somebody1234** [comment]
juat a segfault, gdb output:

```gdb
Dump of assembler code for function main:
   0x000000000040146a <+0>:     push   %rbp
   0x000000000040146b <+1>:     mov    %rsp,%rbp
   0x000000000040146e <+4>:     sub    $0x10,%rsp
   0x0000000000401472 <+8>:     nopl   0x0(%rax,%rax,1)
=> 0x0000000000401477 <+13>:    mov    %fs:0x28,%rax
   0x0000000000401480 <+22>:    mov    %rax,-0x8(%rbp)
   0x0000000000401484 <+26>:    xor    %eax,%eax
   0x0000000000401486 <+28>:    lea    -0xc(%rbp),%rdi
   0x000000000040148a <+32>:    movl   $0x0,-0xc(%rbp)
   0x0000000000401491 <+39>:    call   0x4030a6 <err1>
   0x0000000000401496 <+44>:    mov    -0x8(%rbp),%rax
   0x000000000040149a <+48>:    sub    %fs:0x28,%rax
   0x00000000004014a3 <+57>:    je     0x4014aa <main+64>
   0x00000000004014a5 <+59>:    call   0x406918 <__stack_chk_fail>
   0x00000000004014aa <+64>:    leave  
   0x00000000004014ab <+65>:    xor    %eax,%eax
   0x00000000004014ad <+67>:    ret   
```

**Comment by somebody1234** [comment]
i'm using 1.0.0 though, wasn't able to get master to build when i tried a while back

**Comment by somebody1234** [comment]
oh i guess it just took a few `make`s to build completely... i've copied the build artifacts over though and it still seems to fail for me.
on an unrelated note, `make test` is failing for me...:
`make MODE= -j8 o//third_party/mbedtls/test/test_suite_aes.cbc.com.ok` exited with 1

**Comment by ahgamut** [comment]
> i'm using 1.0.0 though, wasn't able to get master to build when i tried a while back

I use `make MODE= -j8 -i` if the build is interrupted due to a test failure.
Can you check again with https://github.com/jart/cosmopolitan/commit/9b11206ae37e8bffbbcfa839ddd34b43c3638f80?

**Comment by jart** [comment]
New nightly pushed to the website: https://justine.lol/cosmopolitan/cosmopolitan.zip

Please give it a try if you're using 1.0. New official release will be rolled soon.

**Comment by somebody1234** [comment]
same error (same gdb output too)
9b11206 *is* what i tested with, nightly doesn't work either

**Comment by somebody1234** [comment]
seems like the reason one function call works but two fails, is that when there's only one function call it gets inlined.
building using gcc 11.2.0 if that makes a difference.

ok just tried with the gcc in the repo, seems like that works. very odd... it *is* 9.2.0 so maybe it *is* the version?

oh well... i guess i'll just use the builtin (?) gcc for the time being

**Comment by jart** [comment]
Please do. We embed the GCC binaries in this repo for a reason. If you can help us understand why it isn't working with the compiler that comes with your system, let us know and we'll fix it.

**Comment by somebody1234** [comment]
gdb output with embedded gcc:
seems like the main (only?) difference is that the `__stack_chk_fail` is absent from gcc 9 output.
adding `-fno-stack-protector` to the flags with gcc 11 makes the program work (same with the full program that caused the issue in the first place)
so maybe it is just gcc working as intended?
```gdb
   0x00000000004024d0 <+0>:     push   %rbp
   0x00000000004024d1 <+1>:     mov    %rsp,%rbp
   0x00000000004024d4 <+4>:     sub    $0x10,%rsp
   0x00000000004024d8 <+8>:     nopl   0x0(%rax,%rax,1)
   0x00000000004024dd <+13>:    lea    -0x4(%rbp),%rdi
   0x00000000004024e1 <+17>:    movl   $0x0,-0x4(%rbp)
   0x00000000004024e8 <+24>:    call   0x404f38 <err1>
   0x00000000004024ed <+29>:    xor    %eax,%eax
   0x00000000004024ef <+31>:    leave  
   0x00000000004024f0 <+32>:    ret   
```

**Comment by somebody1234** [comment]
... on second thought, the programs work fine with the stack protector when compiled without cosmopolitan, so it might still be an issue with cosmopolitan

gdb output without cosmopolitan:
```gdb
   0x00000000000012d0 <+0>:     push   %rbp
   0x00000000000012d1 <+1>:     mov    %rsp,%rbp
   0x00000000000012d4 <+4>:     sub    $0x20,%rsp
   0x00000000000012d8 <+8>:     mov    %fs:0x28,%rax
   0x00000000000012e1 <+17>:    mov    %rax,-0x8(%rbp)
   0x00000000000012e5 <+21>:    xor    %eax,%eax
   0x00000000000012e7 <+23>:    movl   $0x0,-0xc(%rbp)
   0x00000000000012ee <+30>:    lea    -0xc(%rbp),%rax
   0x00000000000012f2 <+34>:    mov    %rax,-0x20(%rbp)
   0x00000000000012f6 <+38>:    movq   $0x0,-0x18(%rbp)
   0x00000000000012fe <+46>:    mov    -0x20(%rbp),%rax
   0x0000000000001302 <+50>:    mov    %rax,%rdi
   0x0000000000001305 <+53>:    call   0x11a1 <err1>
   0x000000000000130a <+58>:    mov    $0x0,%eax
   0x000000000000130f <+63>:    mov    -0x8(%rbp),%rdx
   0x0000000000001313 <+67>:    sub    %fs:0x28,%rdx
   0x000000000000131c <+76>:    je     0x1323 <main+83>
   0x000000000000131e <+78>:    call   0x1040 <__stack_chk_fail@plt>
   0x0000000000001323 <+83>:    leave  
   0x0000000000001324 <+84>:    ret   
```

differences (i don't asm so i'm not sure what to make of this):
```gdb
   0x00000000000012d0 <+0>:     push   %rbp
   0x00000000000012d1 <+1>:     mov    %rsp,%rbp
 - 0x000000000040146e <+4>:     sub    $0x10,%rsp
 + 0x00000000000012d4 <+4>:     sub    $0x20,%rsp
 - 0x0000000000401472 <+8>:     nopl   0x0(%rax,%rax,1)
   0x00000000000012d8 <+8>:     mov    %fs:0x28,%rax
   0x00000000000012e1 <+17>:    mov    %rax,-0x8(%rbp)
   0x00000000000012e5 <+21>:    xor    %eax,%eax
 - 0x0000000000401486 <+28>:    lea    -0xc(%rbp),%rdi
   0x00000000000012e7 <+23>:    movl   $0x0,-0xc(%rbp)
 + 0x00000000000012ee <+30>:    lea    -0xc(%rbp),%rax
 + 0x00000000000012f2 <+34>:    mov    %rax,-0x20(%rbp)
 + 0x00000000000012f6 <+38>:    movq   $0x0,-0x18(%rbp)
 + 0x00000000000012fe <+46>:    mov    -0x20(%rbp),%rax
 + 0x0000000000001302 <+50>:    mov    %rax,%rdi
   0x0000000000001305 <+53>:    call   0x11a1 <err1>
 + 0x000000000000130a <+58>:    mov    $0x0,%eax
 - 0x0000000000401496 <+44>:    mov    -0x8(%rbp),%rax
 + 0x000000000000130f <+63>:    mov    -0x8(%rbp),%rdx
   0x0000000000001313 <+67>:    sub    %fs:0x28,%rdx
   0x000000000000131c <+76>:    je     0x1323 <main+83>
   0x000000000000131e <+78>:    call   0x1040 <__stack_chk_fail@plt>
   0x0000000000001323 <+83>:    leave  
 - 0x00000000004014ab <+65>:    xor    %eax,%eax
   0x0000000000001324 <+84>:    ret   
```

**Comment by ahgamut** [comment]
I compiled the below file with gcc-11.2.1 (Fedora 35) and got warnings but no crashes:

```c
#include <stdio.h>

typedef struct a { int *i; } a;
typedef struct b { long long i; } b;
void f(int a) { puts("a"); }
void g(int a) { fflush(stdout); }
int h(int a) { return 1 + 1; }
void err1(a a) { f(0); f(0); }
void err2(a a) { puts("a"); puts("b"); }
void err3(a a) { g(0); g(0); }
void ok1(b b) { f(0); f(0); }
void ok2(b b) { puts("a"); puts("b"); }
void ok3(b b) { g(0); g(0); }
void ok4(a a) { puts("a"); }
int ok5(a a) { return h(0) + h(0); }
int main() {
    a a = { (int[]) { 0 } };
    b b = { 0 };
    ok1(b);
    ok2(b);
    ok3(b);
    ok4(a);
    ok5(a);
    err1(a);
    err2(a);
    err3(a);
}
```

![image](https://user-images.githubusercontent.com/41098605/162097319-e014861e-effa-4c58-bb13-fb5cbae48d00.png)

**Comment by somebody1234** [comment]
@ahgamut Seems like that's because of `-flto`? When I add `-flto` there are no errors for me either

**Comment by jart** [comment]
I recommend against using lto and the stack protector. Cosmopolitan provides much stronger memory safety tools like ASAN and UBSAN if you use the Git repository.

**Comment by ahgamut** [comment]
> Seems like that's because of -flto? When I add -flto there are no errors for me either
@somebody1234 it works for me without the LTO flag also.

**Comment by jart** [comment]
I'm going to close this out since LTO isn't something we have time to do right now, but I agree that it would be nice to have happen at some point in the future.
