### ISSUE TITLE
printf("%c", val) incorrect when val==0

### ISSUE THREAD

**Issue by qroq** [jart/cosmopolitan#417]
Apparently char formatting defers to string-of-length 1 processing.
This program should print "len=1", but cosmopolitan says "len=0"

int main()
{
	char c = 0;
	printf("len=%d\n", snprintf(0, 0, "%c", c));
	return 0;
}

**Comment by jart** [comment]
Thanks for spotting this and filing a report. A push will be fixed shortly.

**Comment by qroq** [comment]
Sure thing.  I love what you're doing (cosmo, ape, sector*) almost as much
as what I'm doing ;)

Which is a self-hosted turing-complete PEG-based compiler-compiler that
generates compiletely
standalone C (not yet published, but if you're interested...).  It's qroq
(recursively outputs q(roq)).

Used to run under cosmo, this bug broke it.  Thanks for the quick fix!

**Comment by jart** [comment]
You're welcome to post a link to your project here when it's ready. I would also invite you to our Discord channel https://discord.gg/EZwQUAcx I monitor and receive notifications for the bugs channel on that discord. That channel is great for reporting small issues, getting quick turnaround, or just hanging out :-)

**Comment by jart** [comment]
New amalgamation pushed to https://justine.lol/cosmopolitan/download.html which contains a fix for this issue.

**Comment by qroq** [comment]
>  I would also invite you to our Discord channel
https://discord.gg/EZwQUAcx I monitor and receive notifications...

That invite is now invalid - is that expected, or just an oversight?
I was enjoying hanging out there while it worked.

- Eric

**Comment by jart** [comment]
They expire after a few days. Here's a new one https://discord.gg/mvkhxRaW and I've updated the website.

**Comment by ghaerr** [comment]
> That invite is now invalid - is that expected, or just an oversight?
> I was enjoying hanging out there while it worked.

Eric, you should be able to continue to use Discord with an auto-login after using an invite once. Just save the URL and/or click on one of the "missed notification" emails you should be receiving.
