### ISSUE TITLE
Mac OS 11.6 `zsh: exec format error: ./redbean.com`

### ISSUE THREAD

**Issue by frederikfab** [jart/cosmopolitan#427]
When trying to run the redbean demo, i get an error from zsh

```sh
curl https://redbean.dev/redbean-demo-2.0.1.com >redbean.com
chmod +x redbean.com
./redbean.com -v
```

The output is
`zsh: exec format error: ./redbean.com`

since `zsh` is now the default shell in MacOS, this seems to need attention. Running it in bash works fine however.

```sh
bash
./redbean.com
```

works as expected

**Comment by Infinita740** [comment]
Hi,

I think this is a known issue.

Workaround from [https://redbean.dev#install](https://redbean.dev/#install):

```zsh
bash -c './redbean.com -v'  # zsh/fish workaround (we upstreamed patches!)
```

**Comment by jart** [comment]
Thank you for helping our friend @Infinita740. Please use bash in the meantime. You can also upgrade to the latest version of zsh. I upstreamed a patch with the zhs project over a year ago. I believe it'll eventually make its way into the default MacOS shell. https://github.com/zsh-users/zsh/commit/326d9c203b3980c0f841bc62b06e37134c6e51ea

**Comment by bstro** [comment]
I'm on MacOS 11.6.7 and upgraded my version of `zsh` to 5.9 but still run into the same error. Using `bash -c ./redbean.com` as a workaround.
