### ISSUE TITLE
Migrate from Travis CI to another CI (e.g., GitHub Actions)?

### ISSUE THREAD

**Issue by mbrukman** [jart/cosmopolitan#431]
This repo currently has a [`travis.yml`][travis-yml] and no other CI config file, but Travis CI has [changed its pricing and support model for OSS projects a while back][travis-ended-oss-support], and both of these URLs are now displaying errors:

* https://www.travis-ci.org/jart/cosmopolitan
* https://www.travis-ci.com/jart/cosmopolitan

This means that the project is currently operating with a CI that runs automatically on every PR, whereas it used to before.

Given that the entire Travis CI config is very simple, amounting to `make -j4 V=0`:

https://github.com/jart/cosmopolitan/blob/67b28b9af199f3ba9118c3e1196e92c0d3b3a0d8/.travis.yml#L1-L6

it should be pretty straight-forward to replicate with GitHub Actions. They don't support the `virt: lxd` parameter that Travis CI supported, but I'm guessing this was an optimization to have faster spin-up while still having `sudo` access? Overall, I've found GitHub Actions to be pretty fast, so this may not be an issue.

GitHub actions has [a lot of docs][ga-docs], but to get started quickly, you can probably adapt a variation of this [default blank template that GitHub provides][ga-template] and get up and running very quickly. I'm using something [very similar][my-ga-config].

[travis-yml]: https://github.com/jart/cosmopolitan/blob/67b28b9af199f3ba9118c3e1196e92c0d3b3a0d8/.travis.yml
[travis-ended-oss-support]: https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing
[ga-docs]: https://docs.github.com/en/actions
[ga-template]: https://github.com/jart/cosmopolitan/new/master?workflow_template=blank
[my-ga-config]: https://github.com/mbrukman/c-stdlib/blob/main/.github/workflows/main.yml

**Comment by jart** [comment]
Could you help us do that? I haven't had time to learn how to use GitHub actions. The lxd thing was for a more lightweight environment if I remember. Our build doesn't require sudo access. It doesn't even require that the make command be installed anymore, since you can use `build/bootstrap/make.com`.

**Comment by thetanil** [comment]
started on this. It's absolutely basic, but i would like some feedback and a green build before I move too much further.

i put the badge under the badger. i can move it, open to suggestions.

the build is failing on testcves on my local debian as well as gh runners, so I guess it's correct that there are failing tests ATM.

https://github.com/thetanil/cosmopolitan/tree/issues-431-gh-actions

**Comment by jart** [comment]
@thetanil I'm noticing the log got truncated and am having trouble reading it. One thing that helped us with logging on Travis is the `V=0 make` feature that causes logging to be ephemeral. I've pushed a change to make sure that's working. Could you give it a try on GA?

**Comment by thetanil** [comment]
@jart thank you, that's better: [log not truncated now](https://github.com/thetanil/cosmopolitan/runs/6981854271?check_suite_focus=true)

**Comment by thetanil** [comment]
HasMzHeader check disabled. No PR yet.

now we are failing on reservefd_test TestGrowth. Off by one or off by 2 in every check. [log: off by ones or twos](https://github.com/thetanil/cosmopolitan/runs/6982711345?check_suite_focus=true)

locally i am getting errors on python os_test which look legit. I assume we will see them on gh once these failures are cleared. they are in third party, and I assume they are not really critical. i can just disable them in python.mk and everything elses passes. is it ok to disable with todo(jart) here too?

the reserve fd tests look more serious. I can just disable checks with todos if you want, but maybe you want to look first? we can keep doing it this way, it's fine for me, but if you just say force everything green and open issues for disabled tests, I can do that too. Let me know how you want it.

**Comment by jart** [comment]
> now we are failing on reservefd_test TestGrowth. Off by one or off by 2 in every check. [log: off by ones or twos](https://github.com/thetanil/cosmopolitan/runs/6982711345?check_suite_focus=true)

Wat. Could you run o//examples/printargs.com under GitHub Actions and let me know what it says? For example, there might be rogue file descriptors being inherited from the GA test environment. Under normal circumstances, it should print something like this:

```
SYSTEM
  nightmare on Linux 5.4.192-0-lts

MICROPROCESSOR
  GenuineIntel Kabylake (Client Grade)
  3100mhz freq / 5000mhz turbo / 100mhz bus
  L1 data 8-way 32,768 byte cache w/ 64 sets of 64 byte lines shared across 2 threads
  L1 code 8-way 32,768 byte cache w/ 64 sets of 64 byte lines shared across 2 threads
  L2 4-way 262,144 byte cache w/ 1,024 sets of 64 byte lines shared across 2 threads
  L3 16-way 16,777,216 byte cache w/ 16,384 sets of 64 byte lines shared across 16 threads complexly-indexed
  SSE3 SSSE3 SSE4_2 POPCNT AVX AVX2 FMA BMI BMI2 ADX F16C AES RDRND RDSEED RDTSCP FSGSBASE

FILE DESCRIPTORS
 ☼ 0 (revents=0 fcntl(F_GETFL)=0x8402 isatty()=true)
 ☼ 1 (revents=0 fcntl(F_GETFL)=0x1 isatty()=false)
 ☼ 2 (revents=0 fcntl(F_GETFL)=0x1 isatty()=false)

SIGNALS {0, 0}
  no signals blocked

ARGUMENTS (0x7ffe745f4e50)
 ☼ o/examples/printargs.com

ENVIRONMENT (0x7ffe745f4e60)
 ☼ SHELL=/bin/bash
 ☼ HISTCONTROL=ignoreboth:erasedups
...
```

**Comment by thetanil** [comment]
@jart 

I needed to get a clean build in order to run printargs.com

#### currently disabled:

- HasMzHeader - with todo as requested
- test/libc/test.mk : calls (grow fd)
- python.mk : os_test (spawn, ioctl for stdin)
- python.mk : ioctl_test (i think this was also stdin stdout fd problem)

after that, we are green...

#### output printargs:
```
Run ./o/examples/printargs.com
SYSTEM
  fv-az128-475 on Linux 5.13.0-1029-azure
MICROPROCESSOR
  GenuineIntel Icelake (Server Grade)
  Running inside Microsoft Hv (eax=0x40000006)
  L1 data 12-way 49,152 byte cache w/ 64 sets of 64 byte lines shared across 1 threads
  L1 code 8-way 32,768 byte cache w/ 64 sets of 64 byte lines shared across 1 threads
  L2 20-way 1,310,720 byte cache w/ 1,024 sets of 64 byte lines shared across 1 threads
  L3 12-way 50,331,648 byte cache w/ 65,536 sets of 64 byte lines shared across 2 threads
  SSE3 SSSE3 SSE4_2 POPCNT AVX AVX2 FMA BMI BMI2 ADX F16C AES RDRND RDSEED RDTSCP FSGSBASE
FILE DESCRIPTORS
 ☼ 0 (revents=0x10 fcntl(F_GETFL)=0 isatty()=false)
 ☼ 1 (revents=0 fcntl(F_GETFL)=0x1 isatty()=false)
 ☼ 2 (revents=0 fcntl(F_GETFL)=0x1 isatty()=false)
 ☼ 8 (revents=0 fcntl(F_GETFL)=0x2 isatty()=false)
 ☼ 112 (revents=0 fcntl(F_GETFL)=0x800 isatty()=false)
 ☼ 115 (revents=0 fcntl(F_GETFL)=0x1 isatty()=false)
SIGNALS {0, 0}
  no signals blocked
ARGUMENTS (0x7ffd1595e3a0)
 ☼ ./o/examples/printargs.com
ENVIRONMENT (0x7ffd1595e3b0)
 ☼ DEPLOYMENT_BASEPATH=/opt/runner
 ☼ DOTNET_NOLOGO=1
 ☼ USER=runner
 ☼ CI=true
 ☼ GITHUB_ENV=/home/runner/work/_temp/_runner_file_commands/set_env_ac66b9b6-960d-4312-8a86-eede12104e7f
 ☼ PIPX_HOME=/opt/pipx
 ☼ JAVA_HOME_8_X64=/usr/lib/jvm/temurin-8-jdk-amd64
 ☼ SHLVL=1
 ☼ HOME=/home/runner
 ☼ RUNNER_TEMP=/home/runner/work/_temp
 ☼ GITHUB_EVENT_PATH=/home/runner/work/_temp/_github_workflow/event.json
 ☼ JAVA_HOME_11_X64=/usr/lib/jvm/temurin-11-jdk-amd64
 ☼ PIPX_BIN_DIR=/opt/pipx_bin
 ☼ GRAALVM_11_ROOT=/usr/local/graalvm/graalvm-ce-java11-22.1.0
 ☼ GITHUB_REPOSITORY_OWNER=thetanil
 ☼ GRADLE_HOME=/usr/share/gradle-7.4.2
 ☼ HOMEBREW_PREFIX=/home/linuxbrew/.linuxbrew
 ☼ ANDROID_NDK_LATEST_HOME=/usr/local/lib/android/sdk/ndk/24.0.8215888
 ☼ GITHUB_WORKSPACE=/home/runner/work/cosmopolitan/cosmopolitan
 ☼ ACCEPT_EULA=Y
 ☼ GITHUB_JOB=build
 ☼ RUNNER_PERFLOG=/home/runner/perflog
 ☼ GITHUB_SHA=8fe17044933a26b2b62f31c3bf7ff35ca0105ea6
 ☼ GITHUB_RUN_ATTEMPT=1
 ☼ GITHUB_REF=refs/heads/issues-431-gh-actions
 ☼ GITHUB_ACTOR=thetanil
 ☼ ANDROID_SDK_ROOT=/usr/local/lib/android/sdk
 ☼ LEIN_HOME=/usr/local/lib/lein
 ☼ GITHUB_PATH=/home/runner/work/_temp/_runner_file_commands/add_path_ac66b9b6-960d-4312-8a86-eede12104e7f
 ☼ JAVA_HOME=/usr/lib/jvm/temurin-11-jdk-amd64
 ☼ ***
 ☼ RUNNER_WORKSPACE=/home/runner/work/cosmopolitan
 ☼ HOMEBREW_CLEANUP_PERIODIC_FULL_DAYS=3650
 ☼ GITHUB_EVENT_NAME=push
 ☼ HOMEBREW_NO_AUTO_UPDATE=1
 ☼ ANDROID_HOME=/usr/local/lib/android/sdk
 ☼ GITHUB_SERVER_URL=https://github.com/
 ☼ GECKOWEBDRIVER=/usr/local/share/gecko_driver
 ☼ LEIN_JAR=/usr/local/lib/lein/self-installs/leiningen-2.9.8-standalone.jar
 ☼ HOMEBREW_REPOSITORY=/home/linuxbrew/.linuxbrew/Homebrew
 ☼ SGX_AESM_ADDR=1
 ☼ CHROME_BIN=/usr/bin/google-chrome
 ☼ SELENIUM_JAR_PATH=/usr/share/java/selenium-server.jar
 ☼ ANDROID_NDK_HOME=/usr/local/lib/android/sdk/ndk-bundle
 ☼ GITHUB_STEP_SUMMARY=/home/runner/work/_temp/_runner_file_commands/step_summary_ac66b9b6-960d-4312-8a86-eede12104e7f
AUXILIARY (0x7ffd1595e6b0)
 ☼ AT_SYSINFO_EHDR [  33] = 0x7ffd1596e000
 ☼ AT_HWCAP        [  16] = 0x1f8bfbff    
 ☼ AT_PAGESZ       [   6] = 0x1000        
 ☼ AT_CLKTCK       [  17] = 100           
 ☼ AT_PHDR         [   3] = 0x200040      
 ☼ AT_PHENT        [   4] = 0x38          
 ☼ AT_PHNUM        [   5] = 0x4           
 ☼ AT_BASE         [   7] = 0             
 ☼ AT_FLAGS        [   8] = 0             
 ☼ AT_ENTRY        [   9] = 0x200400      
 ☼ AT_UID          [  11] = 1001          
 ☼ AT_EUID         [  12] = 1001          
 ☼ AT_GID          [  13] = 121           
 ☼ AT_EGID         [  14] = 121           
 ☼ AT_SECURE       [  23] = 0             
 ☼ AT_RANDOM       [  25] = 0x7ffd1595e7f9
 ☼ AT_HWCAP2       [  26] = 0x2           
 ☼ AT_EXECFN       [  31] = /home/runner/.ape
 ☼ AT_PLATFORM     [  15] = 0x7ffd1595e809
SPECIALS
 ☼ umask() = 022
 ☼ getpid() = 166037
 ☼ getppid() = 166036
 ☼ getpgrp() = 686
 ☼ getsid() = 686
 ☼ getuid() = 1001
 ☼ geteuid() = 1001
 ☼ getgid() = 121
 ☼ getegid() = 121
 ☼ kTmpPath = "/tmp/"
 ☼ kNtSystemDirectory = ""
 ☼ kNtWindowsDirectory = ""
 ☼ GetProgramExecutableName = "/home/runner/work/cosmopolitan/cosmopolitan/o/examples/printargs.com"
 ☼ GetInterpreterExecutableName = "/home/runner/.ape"
 ☼ RSP = 0x70000001ffd0
 ☼ GetStackAddr() = 0x700000000000
 ☼ GetStaticStackAddr(0) = 0x700000000000
 ☼ GetStackSize() = 0x20000
MEMTRACK
70000000-70000001 rw-Sa-- 2x stack  
# 2 frames mapped w/ 0 frames gapped
TERMIOS
  - tcgetattr(0) failed ENOTTY/25/Not a typewriter
  - tcgetattr(1) failed ENOTTY/25/Not a typewriter
```

**Comment by thetanil** [comment]
@jart the ENOTTY there reported by printargs is I guess the same issue as showing up in the python ioctl and os tests. I lost the exact message in my terminal scrollback buffer, but it was also something like stdin/stdout are not a tty.

**Comment by thetanil** [comment]
I think just to keep things moving here, I try to setup a remote runner on my local machine. I will report back if that changes anything.

**Comment by jart** [comment]
What we'll probably do to fix the tests which are impacted by those file descriptors is modifying [`libc/testlib/testmain.c`](https://github.com/jart/cosmopolitan/tree/master/libc/testlib/testmain.c) so it uses [`poll()`](https://github.com/jart/cosmopolitan/blob/56eff8544f1b51ddf497b30a5b938c48f8f5ea13/libc/runtime/printargs.greg.c#L251) to close any open file descriptors greater than or equal to 3.

**Comment by thetanil** [comment]
maybe I'm misunderstanding the issue, but fds >=3 is not going to fix stdin / stdout is it?

**Comment by jart** [comment]
It won't close stdin/stdout. If you're referring to Python isatty thing, then Python tests should not be assuming that. Any tests in Python that require a TTY should be disabled. They should be rewritten to use something like `openpty()`.

**Comment by thetanil** [comment]
ok, no pressure, just a questions of timing. sounds like you have an idea of an easy fix. Will you have that in before I set up a remote runner (in the next day or two), or should I go ahead and do that?

**Comment by jart** [comment]
Thanks to @thetanil's contributions this issue is now solved. Great work everyone!
