### ISSUE TITLE
chibicc called with -o /dev/null fails due to elfwriter_open tmppath naming convention

### ISSUE THREAD

**Issue by tgbugs** [jart/cosmopolitan#434]
While fiddling with the cosmo chibicc to see if I could get it to build musl I ran into an issue where musl configure would call the compiler with the output file set to `/dev/null`. This causes chibicc to attempt to open `/dev/null.{pid}`, which causes the program to exit.

One potential fix is to special case handling of `/dev/null` in `elfwriter_open` and `elfwriter_close` in elfwriter.c, but I'm not sure whether that is the best solution because we wind up having to create a tmpfile but one where we need to know the path to keep calls to `elf->tmppath` happy (it does work though).

**Comment by jart** [comment]
I'm reasonably certain we don't need the atomic tmp+rename behavior in elfwriter_open() anymore. That behavior is now being implemented by a program called `compile.com` which our Makefile build uses to wrap each command invocation to do just that. I'll remove it in an upcoming change, at which point this issue will be closed. Thanks for the report.
