### ISSUE TITLE
I feel like root handling is a bit inconsistent

### ISSUE THREAD

**Issue by 752963e64** [jart/cosmopolitan#449]
Hello I've clooned the last version and ran ```build/bootstrap/make.com -j16 MODE=rel```,
did ```cp o/rel/tool/net/redbean-demo.com ~/bin/```
then ```cd ~/bin```
and then ```mkdir demo && cd demo && unzip ~/bin/redbean-demo.com && cd ..```
then ```cp demo/maxmim.lua . && vim maxmind.lua```
I see path points to /usr/local/share/maxmind/*.mmdb.
```mkdir -pv usr/local/share/maxmind && cp GeoLite* usr/local/share/maxmind```
then ```zip -r redbean-demo.com usr/```
ensuring ```zipinfo redbean-demo.com```
```./redbean-demo.com -vvvV```
browser test. ```500 internal error```
also some uncomplete read error showing in interactive console...
So, I didn't give up... tried another path
```mkdir adir && cp GeoLi* adir/ && zip -r redbean-demo.com adir/ maxmind.lua``` I ofc change path into maxmind.lua to point to "adir/*.mmdb" notice I choose no to write fullpath.
Browser test working. However putting fullpath doesn't work "/adir/*.mmdb".
Hmmm also it seems to work by picking outside zip (ROOTFS) file without an overlay or given path... path test-bed "/usr/local/share/maxmind/GeoLite*.mmdb" ooof.

**Comment by 752963e64** [comment]
Also note the bad uri handling... when http[s]://ip|whatname//a.example

logging shows ```GET http[s]://a.example``` while still providing an index.html and producing another request from browser which end like ```GET http[s]://main.css``` in log...

sick stuff in short :D

**Comment by 752963e64** [comment]
I think it would be nice to prefix internal zipfs content access, because you can literally overlap your system fs into a zip and with the actual behavior you dunno what you accessing...

**Comment by 752963e64** [comment]
I also would like to add that a few examples will work if you uses unprivileged ports.
While the entry port case shouldn't play in routing...

**Comment by jart** [comment]
Thank you for the feedback! We'll be sure to take it into consideration. Enjoy redbean!

**Comment by 752963e64** [comment]
Well, I've been wrong in some way... Looks like maxmind doesn't support zip asset still... that's why it picking up on local FS...

The ```//``` in url is from client based ```strange``` procedures... 

sry for disturbing...
