### ISSUE TITLE
memzoom: it is unclear what byte values are shown if I zoom out.

### ISSUE THREAD

**Issue by alexey-milovidov** [jart/cosmopolitan#464]
E.g. with no zoom, it shows `⌂ELF` as the first four bytes.
If I zoom out, I expect to see some summary of every two bytes per character.
The first bytes in zoom level 2 are `eD` and it's unclear to me, how these characters correspond to `⌂ELF`.

**Comment by jart** [comment]
It's based on a CP437 mapping of all 256 byte values. 

https://github.com/jart/cosmopolitan/blob/5df3e4e7a898d223ce9bd646e37345ef7c54f84e/libc/nexgen32e/kcp437.S#L60-L92

For example, if you downscale `AZ` it'll probably land somewhere in the area of `J`. But if you downscale something like `AAAAAZZZZZ` then it'll probably look like `AAJZZ`. 

Basically all it's doing is the same thing an image scaler would do. It's just operating on text.

**Comment by alexey-milovidov** [comment]
No interpolation (take the first byte) will be better for visualization. At least it will not display the bytes that were not present in memory. So, "⌂ELF" / 2 will be "⌂L".
