### ISSUE TITLE
printimage.com chokes on network mounts in WSL

### ISSUE THREAD

**Issue by pluma** [jart/cosmopolitan#467]
Trying to run `printimage.com /mnt/c/Users/username/filepath.png` fails with a stacktrace:

```
error:tool/viz/printimage.c:377:printimage.com: check failed on hostname pid 14956
        CHECK_NE(-1, (fd = open(path, O_RDONLY)));
                 → -1 (-1)
                != -1 ((fd = open(path, O_RDONLY)))
        /mnt/c/Users/username/filepath.png
        EACCES[5][Permission denied][Access is denied][5]
        printimage.com /mnt/c/Users/username/filepath.png
6ffffffffd70 000000421f59 __die+68
6ffffffffd90 000000421e90 __check_fail+368
6ffffffffe60 00000040a1e1 WithImageFile+830
6fffffffffa0 00000040a5c0 main+102
6fffffffffd0 000000402b30 cosmo+71
6fffffffffe0 00000042ce3d _jmpstack+22
```

As it works fine when running against files in WSL, I'm guessing this is specific to network mounts (in this case the host system). The file shows as `0777` in `ls` and I can `cat` it just fine.

**Comment by jart** [comment]
PrintImage is running as a WIN32 executable. Try changing the path from `/mnt/c/Users/username/filepath.png` (WSL convention) to `/c/Users/username/filepath.png` (Cosmo / Cygwin convention).

**Comment by jart** [comment]
One issue worth noting is that, if you're launching PrintImage from the WSL bash shell, then the fact that it's running as a WIN32 executable is not a good thing. Microsoft configures `binfmt_misc` by default to do this unholy thing where it launches Windows binaries in the WSL environment and it's such an irregular environment that we can't support it. If that's the case, then you need to launch printimage from CMD.EXE or PowerShell. If you want to use bash, then you have to disable what microsoft did to binfmt_misc by running `sudo sh -c 'echo -1 >/proc/sys/fs/binfmt_misc/status'`. In that case, launching PrintImage under WSL it'll run as a Linux executable.
