### ISSUE TITLE
dwarf line number information for .yoink ignored.

### ISSUE THREAD

**Issue by nicholatian** [jart/cosmopolitan#48]
```
src/chalkboard/main.c: Assembler messages:
src/chalkboard/main.c:21: Warning: dwarf line number information for .yoink ignored
```

It is odd that the assembler would be complaining through C, but I suppose Cosmo does have a lot of inline assembly. The line it mentions is blank:
https://github.com/aquefir/oamas/blob/274a2f0c42e5ad1435e056fca9eb53fb1045a7c5/src/chalkboard/main.c#L21

What is the best way to silence these things?

**Comment by jart** [comment]
I don't know. Consider using the prebuilt gcc binaries in [//third_party/gcc](https://github.com/jart/cosmopolitan/tree/master/third_party/gcc). You could also pass the `-w` flag. Compiler warnings are a sideshow of a sideshow compared to modern techniques like sanitization and unit testing which Cosmopolitan makes easier than any other libc. Contributions are welcome for changes that make warnings go away. See this file:

https://github.com/jart/cosmopolitan/blob/ac3b1dfb211dc34eb76e8205fb80a93920a9f301/libc/integral/c.inc#L652-L746

Also this file:

https://github.com/jart/cosmopolitan/blob/ac3b1dfb211dc34eb76e8205fb80a93920a9f301/tool/build/compile.c#L124-L603
