### ISSUE TITLE
[Request] Tag releases of sub-tools on `master`

### ISSUE THREAD

**Issue by chrisokuda** [jart/cosmopolitan#511]
### Background

I'm working on some documentation generation tools for redbean (not even alpha stage yet, so don't worry about that for now) and currently to update the documentation based on changes to the `help.txt` file, I need to do a `git diff` between two commits that might or might not be labeled in the commit message as a certain redbean version.

## Request: 

It would be simpler to `git diff` between tags, so it would be helpful if when you rev the version for the tools like `redbean-VERSION.com` and others, if you could `git tag` the `master` branch with something like `redbean-x.y.z` or `pledge-x.y.z` (or others). 

Thanks for consideration!

**Comment by jart** [comment]
I've added the following tags:

```
pledge-1.1
pledge-1.3
pledge-1.4
redbean-0.3
redbean-1.2
redbean-1.4
redbean-1.5
redbean-2.0.1
redbean-2.0.10
redbean-2.0.12
redbean-2.0.13
redbean-2.0.14
redbean-2.0.15
redbean-2.0.2
redbean-2.0.3
redbean-2.0.4
redbean-2.0.5
redbean-2.0.6
redbean-2.0.7
redbean-2.0.8
redbean-2.0.9
redbean-2020-10-05
redbean-2020-12-28
redbean-2021-01-16
redbean-2021-01-24
redbean-2021-02-25
redbean-2021-02-27
redbean-2021-03-01
redbean-2021-03-02
redbean-2021-03-03
redbean-2021-03-09
```

I'll try to dig up the other ones as soon as I have time.

Enjoy!
