### ISSUE TITLE
Two libc typos

### ISSUE THREAD

**Issue by gottfriedleibniz** [jart/cosmopolitan#515]
Two small libc typos I have come across while experimenting with this awesome project:

1. `COSMOPOLITAN_C_START_` is [placed](https://github.com/jart/cosmopolitan/blob/master/libc/calls/struct/sigaction.h#L24-L25) inside the `GNU && !ANSI` check while `COSMOPOLITAN_C_END_` is [placed](https://github.com/jart/cosmopolitan/blob/master/libc/calls/struct/sigaction.h#L77-L79) outside.
1. `flockfile` and `funlockfile` are [declared](https://github.com/jart/cosmopolitan/blob/master/libc/stdio/stdio.h#L129-L130) with void return types. However, this conflicts with the following [ternary](https://github.com/jart/cosmopolitan/blob/master/libc/stdio/stdio.h#L183-L184) statement, i.e., it is expecting `((void)0)`.

Thanks

**Comment by jart** [comment]
Thanks for reporting this. Fixing now.

**Comment by jart** [comment]
That's fine. Let us know if you find anything else.
