### ISSUE TITLE
How to build a portable socket program?

### ISSUE THREAD

**Issue by mochazi** [jart/cosmopolitan#517]

**Comment by pkulchenko** [comment]
I'm not sure what exactly you need, but you can check examples in the examples/ folder, for example [curl.c](https://github.com/jart/cosmopolitan/blob/master/examples/curl.c). If you need something more high level, then using [unix.socket](https://redbean.dev/#unix.socket) and related functions from [unix.* module](https://redbean.dev/#unix) may work. See [unix-finger.lua](https://github.com/jart/cosmopolitan/blob/17cbe734118a6c4f4e5739cfd875f35bdaca7bf1/tool/net/demo/unix-finger.lua) for an example.

If you need to build it, then you can skip that step for Lua modules (as they come bundled with redbean server) and if you need to compile the curl example, then running `make -j8 o//examples/curl.com` from the cosmopolitan folder should do it.

**Comment by mochazi** [comment]
@pkulchenko 
What do I need to do if I want to build `curl.c` for Windows?

**Comment by pkulchenko** [comment]
If you build curl.com as described above, the generated executable will run on Windows, but the build process itself will need to be done on Linux (it will be much easier to set up).

**Comment by mochazi** [comment]
![image](https://user-images.githubusercontent.com/54659396/181703959-d4c81342-2518-4c2b-a3a7-c4152a6ae024.png)

I tried executing it with an `Android 9` virtual machine and found it didn't work. Android doesn't seem to be supported at the moment.
