### ISSUE TITLE
discord channel

### ISSUE THREAD

**Issue by athiakos** [jart/cosmopolitan#518]
Hi,

Sorry to spam the tracker but all the discord invites seem to be expired. Is there an active server or even better an IRC channel that I can join and discuss dev related issues?

-Alex

**Comment by shmup** [comment]
@athiakos here's an invite url that doesn't expire, but has 5 uses. It's a concept I wanted to see if @jart approved of :P We can have more uses configured on them. Maybe not a bad idea, though, versus expiration?

https://discord.gg/b8aYhdeQFx

**Comment by athiakos** [comment]
cheers, i got in. Not sure if @jart wants to open the server but if yes better put something on the main readme for others to find.

**Comment by jart** [comment]
The latest invite link is https://discord.gg/eDHaUtmk

As far as I can tell, it's not possible to make our Discord public until we have 1,000 members. So far we have ~150. If anyone reading this wants an invite in the future, email jtunney@gmail.com.

**Comment by Mirodin** [comment]
@jart I tried to join but the invite is invalid again. Would it be possible to post another one?

**Comment by jart** [comment]
https://discord.gg/tvxyUrpY

**Comment by paulwratt** [comment]
just used that link, numbers are already up by another 50 ..

**Comment by rishavs** [comment]
@jart , can you share the invite again? It has gotten invalid now.

**Comment by xloem** [comment]
I just got removed without comment or message from the discord server and the invite in this readme is giving me this:
![redbeanissue202304090548EST](https://user-images.githubusercontent.com/279585/230766401-e3d92e22-1537-4e2c-8005-d612182059f1.png)
can any confirm if this is a server ban (i am unwanted and should stay away) or a malicious action by a third party?
be great to have a new invite to try too
