### ISSUE TITLE
Unable to run redbean on Windows 10 and Ubuntu (WSL).

### ISSUE THREAD

**Issue by rajat1saxena** [jart/cosmopolitan#52]
Followed the guide: https://justine.lol/redbean/index.html

On Windows 10, I am getting a "This app cannot run on your PC" error and on Ubuntu I'm getting the following error.

rajat@rajat-desktop:/mnt/c/Users/91858/Downloads$ cat index.html
<b>hello</b>
rajat@rajat-desktop:/mnt/c/Users/91858/Downloads$ zip redbean.com index.html
  adding: index.html (stored 0%)
rajat@rajat-desktop:/mnt/c/Users/91858/Downloads$ ./redbean.com -vv
./redbean.com: Invalid argument

**Comment by jart** [comment]
What shell are you using? Could you try downloading the latest build again and let me know if it works?  https://justine.lol/redbean/index.html

**Comment by ben-e** [comment]
Hi @jart, for what it's worth, I'm getting a similar error as @rajat1saxena. In fact, it actually looks like some of the issues discussed in #56.

On Windows 10 (build 19042.804) I can run redbean.com successfully, but modifying the archive via Windows Explorer causes this error:
![image](https://user-images.githubusercontent.com/11801950/109404863-10ef5700-791f-11eb-820a-55a87a1c7651.png)

Likewise, I can run redbean.com in WSL (Ubuntu 20.04, via Windows Terminal), but adding anything to the archive causes the error @rajat1saxena noted:
```
ben@DESKTOP-7D20RMA:/mnt/c/Users/benew/Downloads/beantest$ curl https://justine.lol/redbean/redbean-latest.com > redbean.com
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  200k  100  200k    0     0   412k      0 --:--:-- --:--:-- --:--:--  412k
ben@DESKTOP-7D20RMA:/mnt/c/Users/benew/Downloads/beantest$ chmod +x redbean.com
ben@DESKTOP-7D20RMA:/mnt/c/Users/benew/Downloads/beantest$ echo '<b>hello</b>' >index.html
ben@DESKTOP-7D20RMA:/mnt/c/Users/benew/Downloads/beantest$ zip redbean.com index.html
  adding: index.html (stored 0%)
ben@DESKTOP-7D20RMA:/mnt/c/Users/benew/Downloads/beantest$ ./redbean.com -vv
./redbean.com: Invalid argument
```
I do get a little security popup on Windows, but it doesn't seem to be actually doing anything. I get this issue running with redbean-latest.com and redbean-2021-02-27.com, which I assume are actually the same.

Thank you for taking a look!

**Comment by rajat1saxena** [comment]
@jart On Windows 10, I simply added a index.html to the zip and double clicked on the file (after renaming it back to .com) to run it. Then I got that error.

Ubuntu (WSL) is running bash.

**Comment by madacol** [comment]
This error happens to me too if I download `redbean.com` from the html link provided in https://justine.lol/redbean/index.html (https://justine.lol/redbean/redbean-2021-02-25.com)

But if instead I use the one in the `curl` command https://justine.lol/redbean/redbean-latest.com it works just fine

**Comment by madacol** [comment]
I'm getting a similar error, but it happens to me if I download `redbean.com` binary from https://justine.lol/redbean/redbean-2021-02-25.com that's the one pointed in the html link in https://justine.lol/redbean/index.html

But if instead I use the link from the `curl` command https://justine.lol/redbean/redbean-latest.com it works just fine

**Comment by rovashan** [comment]
The latest binary **redbean-2021-03-02.com** is working after updating the archive on Windows 10.

**Comment by jart** [comment]
Good news! Right now the problem is being worked around by making redbean go a little slower on Windows. See https://github.com/jart/cosmopolitan/commit/7e4021bf821832aa45e8207dd2cacda468ccdd95 We'll find a better solution real soon. But this at least gets us back up and running quickly.
