### ISSUE TITLE
Support explicit execution by shell

### ISSUE THREAD

**Issue by orent** [jart/cosmopolitan#526]
I tried to run ```sh hello.com``` without chmod +x first.  It started executing the script but failed at ```exec "$0"```.

Suggestion: have the script chmod +x itself to support this mode of execution, too.

This is either for smartasses like me, or to make it easier to explain to first-time users on linux - just use sh instead of trying to spell 'chmod +x` over the phone.

**Comment by jart** [comment]
Is there any particular reason you can't run `./hello.com`?

**Comment by orent** [comment]
Nonono. Everything works fine if I just chmod +x. This is not a bug report. It’s  a nice-to-have suggestion. Yet another way to run the ape: “sh ape.com” with no need for chmod +x first

Many installation packages on unix/linux are tar files with a shell script header. The instructions are “download this and run it with sh”. It’s simply easier to explain in the docs than chmod+execute.

**Comment by jart** [comment]
Thanks for the creative suggestion. It's not something we're planning to implement at this time. In many respects, `chmod +x` is a way for the user to signal intent that they want something to be executed. Having a feature that sets the bit automatically might lead to outcomes that the user didn't intend to happen, and that's something we don't want to happen.

**Comment by orent** [comment]
chmod +x was just a suggested possible implementation

Another possibility, for example, is for the ape loader to support running from a file without the X flag (but only if passed the actual file, no path search for something without X flag, of course).

Are you rejecting the implementation or the feature? I think "sh something" is a very clear intent for wanting something executed.

**Comment by orent** [comment]
Just noticed that the examples in the documentation include:

```bash hello.com              # runs it natively```

As well as using sh as a workaround for an unpatched zsh. It this means it should work even if hello.com is without +x rather than emitting an unhelpful error.

I definitely understand not changing anything about the executable by default. But ```sh hello.com --assimilate``` needs to do do everything required to turn hello.com into a native executable for the host OS, including +x, if necessary.

**Comment by jart** [comment]
Contributions welcome on helping us clean up the docs. Code like that needs to be updated to say `sh -c ./foo.com` or `bash -c ./foo.com`
