### ISSUE TITLE
QEMU boot looping

### ISSUE THREAD

**Issue by JoshuaWierenga** [jart/cosmopolitan#527]
Hi, I was messing around with bare metal applications with an older version of cosmopolitan and after updating to the newest pre-built version, all tested programs would just cause QEMU to boot loop when it tries to run them.

I bisected the problem and found that e7611a8476ae5e6dc36b871e50f661bd968be351 is the commit that introduced the regression.
Looking at QEMU logs it appears that something is causing an exception which ends up causing a triple fault.
I spent some time messing with that commit and figured out it was the new stack code in [cosmo.S](https://github.com/jart/cosmopolitan/blob/e7611a8476ae5e6dc36b871e50f661bd968be351/libc/runtime/cosmo.S#L79-L115) causing the fault.  I tried duplicating the windows jmp code to run for bios well so that it would skip the new code as well but that doesn't change anything. However, removing the new stack code does fix it, even without readding the old version in [systemfive.S](https://github.com/jart/cosmopolitan/blob/2046c0d2aebd9fe7e23755c9daec4234e40b7dce/libc/sysv/systemfive.S#L362-L457).

With the sample deathstar.c program, QEMU spits out the following log when using `qemu-system-x86_64 -m 16 -nographic -fda deathstar.com -d in_asm,cpu_reset,int -D log`:
```----------------
...
IN: 
0x0040c01d:  48 83 c0 08              addq     $8, %rax
0x0040c021:  eb d0                    jmp      0x40bff3

check_exception old: 0xffffffff new 0xd
     0: v=0d e=0000 i=0 cpl=0 IP=0028:000000000040c012 pc=000000000040c012 SP=0030:00006fffffffffb0 env->regs[R_EAX]=00006ffffffffff8
RAX=00006ffffffffff8 RBX=0000000000000001 RCX=00006fffffffff54 RDX=0000000000000000
RSI=00000000004118f0 RDI=00000000004118f0 RBP=00006fffffffffc0 RSP=00006fffffffffb0
R8 =0000000000000084 R9 =00000000004025a8 R10=0000000000000002 R11=0000000000000001
R12=00313d4c4154454d R13=00006fffffffffb0 R14=00006fffffffffc0 R15=00006fffffffffd0
RIP=000000000040c012 RFL=00200002 [-------] CPL=0 II=0 A20=1 SMM=0 HLT=0
ES =0030 0000000000000000 ffffffff 00af9300 DPL=0 DS   [-WA]
CS =0028 0000000000000000 ffffffff 00af9b00 DPL=0 CS64 [-RA]
SS =0030 0000000000000000 ffffffff 00af9300 DPL=0 DS   [-WA]
DS =0030 0000000000000000 ffffffff 00af9300 DPL=0 DS   [-WA]
FS =0030 0000000000000000 ffffffff 00af9300 DPL=0 DS   [-WA]
GS =0030 0000000000000000 ffffffff 00af9300 DPL=0 DS   [-WA]
LDT=0000 0000000000000000 0000ffff 00008200 DPL=0 LDT
TR =0000 0000000000000000 0000ffff 00008b00 DPL=0 TSS64-busy
GDT=     00000000000024dc 00000038
IDT=     0000000000000000 00000000
CR0=80000013 CR2=0000000000000000 CR3=000000000007e000 CR4=000002a0
DR0=0000000000000000 DR1=0000000000000000 DR2=0000000000000000 DR3=0000000000000000 
DR6=00000000ffff0ff0 DR7=0000000000000400
CCS=0000000000000008 CCD=00006fffffffff54 CCO=LOGICB  
EFER=0000000000000501
...
```

Disassembling the unstripped binary shows that the crash happens within [getenv](https://github.com/jart/cosmopolitan/blob/e7611a8476ae5e6dc36b871e50f661bd968be351/libc/intrin/getenv.greg.c#L35-L77), I saw `__hostos` in the symbols a few lines in so perhaps that is not available until [systemfive.S](https://github.com/jart/cosmopolitan/blob/e7611a8476ae5e6dc36b871e50f661bd968be351/libc/sysv/systemfive.S) on bios since `_init_systemfive` appears to [set it up?](https://github.com/jart/cosmopolitan/blob/e7611a8476ae5e6dc36b871e50f661bd968be351/libc/sysv/systemfive.S#L200) I did try removing both the `IsWindows` macro and the `mmap` call in the new stack code since both rely on `__hostos` but then it didn't build with cosmopolitan.h being missing and a bunch of tests failing. Sticking a `jmp 9f` at the top works as expected but would likely break support for any OSes other than windows since it wouldn't run at all.

I assumed the reason for the triple fault would be the same in 7bd4179b9b2eae4ae594611ce5b74ee7a42d4b07 but not only is it different, but there are also now two different faults that alternate. The first is in [__enable_tls](https://github.com/jart/cosmopolitan/blob/9de3d8f1e6fa09f39671d244d12a6b596d7f15eb/libc/runtime/enable_tls.c#L96-L259) in one of the `syscall`s, [this one?](https://github.com/jart/cosmopolitan/blob/9de3d8f1e6fa09f39671d244d12a6b596d7f15eb/libc/runtime/enable_tls.c#L162-L165) The second appears to have four exceptions though the first is not tagged `check_exception` and occurs well before 0x400000 so might not have anything to do with this bug.

Thanks, Joshua.

**Comment by jart** [comment]
Thanks for spotting this and for the investigation. It's been a few months since I've had a chance to focus on our bare metal support. Could someone here please help us by submitting a PR? Now that we have some idea what's going on. The `METAL=1` variable is set at the end of `ape/ape.S`

**Comment by tkchia** [comment]
Hello @jart, hello @JoshuaWierenga,

To (hopefully) get things going, I have submitted a pull request https://github.com/jart/cosmopolitan/pull/529, which should fix this particular crash.

With this patch, `o/examples/hello.com` now crashes a bit further down, somewhere within `__enable_tls`:
```
----------------
IN: 
0x000000000040c1ae:  mov    $0x9e,%eax
0x000000000040c1b3:  mov    $0x1002,%edi
0x000000000040c1b8:  mov    %r13,%rsi
0x000000000040c1bb:  syscall 
```
...
```
check_exception old: 0xffffffff new 0xe
     0: v=0e e=0000 i=0 cpl=0 IP=0000:0000000000000000 pc=0000000000000000 SP=0008:000070000001ff40 CR2=0000000000000000
RAX=000000000000009e RBX=0000000000415bc0 RCX=000000000040c1bd RDX=00000000004105eb
```
...

I presume that TLS support has not yet been implemented for the bare metal target?

Thank you!

**Comment by JoshuaWierenga** [comment]
Unsurprisingly the TLS issue was introduced in 69f4152f38c820e7fb5d6137616c98c642f5dd8f. We could use the same jump fix as the stack setup just one function higher in cosmo.S or insert `__tls_enabled = false;` somewhere in bios setup. Though looks like ``__enable_tls()`` is just calling `arch_prctl()` via syscall by default and it does appear to have a bios implementation with`arch_prctl_msr()`, any reason why the syscall is not set up? I don't know enough about the bios implementation or syscalls, in general, to know if setting it up is too complex so perhaps it's that.

**Comment by JoshuaWierenga** [comment]
Thanks @tkchia and @jart,

Now that #529 is merged, very basic bios programs are building again. More advanced functionality is something I am looking into and I will open another issue if something comes up. I will close this issue for now as its looks like everything I mentioned initially is fixed. But if bios support breaks again in the near future it might be worth reopening it then.
