### ISSUE TITLE
make unveiling: /tmp strictness

### ISSUE THREAD

**Issue by chrysn** [jart/cosmopolitan#530]
Currently, make unconditionally unveils `/tmp`. This can be seen as a practical shortcut (given that many programs put stuff in `/tmp`), but also carries risks of interfering with other makes, accessing unrelated files or simply discarding general read protections because someone who is certainly not me has a habit of checking out stuff in `/tmp` if it's unlikely to be needed for longer. (Hey, free cleanups at reboot!).

I'd like to suggest that rather than unveiling `/tmp`, `TMPDIR` be unveiled. If it's not set[^1], a temporary TMPDIR could be picked (maybe `mktemp -d` style); it probably makes sense to do that per Makefile rule (and not for the whole Makefile, and not per shell line). Thus, inside a rule, files can be created and used to pass data between shell lines inside a rule, but if a Makefile tries to sidestep declared inputs and outputs to (inadvertently, usually) smuggle data from one rule to the other, this gets detected.

Programs that fail due to such a mechanism (eg. because they write to `/tmp` rather to `${TMPDIR:-/tmp}`) can still unveil `/tmp` 

[^1]:  Maybe even if it is set; in that case it'd be under that predefined TMPDIR. That might be excessive in terms of what it'd need to opt out, though.

**Comment by jart** [comment]
This sounds good to me. We'd need to make sure the temp directory created for each rule will live across multiple lines of commands within that rule.

Would you be interested in contributing this? Please let me know either way. If that does interest you, then please join our Discord so we can collaborate! https://discord.gg/94A33huZ

Apropos /tmp I fixed this morning an issue where temporary files weren't being cleaned up properly.

**Comment by jart** [comment]
As of https://github.com/jart/cosmopolitan/commit/4c3ab6d11ec51b46e8cf07c35cdb4f6c4fd0ded3 Landlock Make now offers a strict mode. Declaring `.STRICT = 1` in your Makefile will

1. Disable implicitly unveiled paths, e.g. `/tmp`
2. Disable dynamic executables
3. Disable `$PATH` searching

You can get those things back using the `.UNVEIL` variable, which may now be specified both as a global variable or as a target-specific variable. For example:

```
.STRICT = 1
.UNVEIL =			\
	rwcx:o/tmp		\
	libc/integral		\
	libc/disclaimer.inc	\
	rx:build/bootstrap	\
	rx:o/third_party/gcc	\
	/proc/self/status	\
	rw:/dev/null		\
	w:o/stack.log		\
	/etc/hosts		\
	~/.runit.psk
```

I believe our recent change satisfactorily resolves this issue. It shouldn't be necessary to modify Make's core code to setup and teardown $TMPDIR folders. That would be more appropriately implemented in a tiny program that wraps command invocations, e.g.

```
%.o: %.c
  autotmp cc -o $@ -c $<
```

It's also important to note that Landlock Make currently isn't intended as a security layer. It can prevent you from shooting yourself in the foot. It currently isn't designed to secure your computer against someone intentionally being malicious. If these concerns aren't just theoretical then please help me understand the use case for running untrusted code under make and I'll consider writing more features that can help you accomplish that.

**Comment by jart** [comment]
I've changed my mind on this. I'll be pushing a change shortly that lets make abstract TMPDIR setup and teardown.
