### ISSUE TITLE
pthread_create isn't defined anywhere?

### ISSUE THREAD

**Issue by Keithcat1** [jart/cosmopolitan#534]
While pthread_create is declared and can be gotten by including "libc/isystem/pthread.h", actually using it gets you a linker error: undefined symbol to the face and none of the .C files in Cosmopolitan contained pthread_create when I did a grep. The same thing might also be happening with pthread_destroy.

**Comment by jart** [comment]
It'll be coming soon. We had a `cthread_create` function, but it wasn't clear why the tests for it weren't passing across platforms. Right now the stable working threading solution is `_spawn()` and `_join()`

https://github.com/jart/cosmopolitan/blob/0ea0d33a770bed044b9001be0df9a413b3843820/libc/thread/spawn.c#L56-L71

We've got thread-local storage working on all seven platforms. Just use `_Thread_local`.

The only POSIX thread APIs we have right now which are stable and working well are `pthread_mutex_lock` and the tls key api.
