### ISSUE TITLE
Document "why" and "future potential" for current limitations

### ISSUE THREAD

**Issue by solvingj** [jart/cosmopolitan#57]
On hackernews and other places where discussion is happening, people are asking obvious questions about supported capabilities:
- Thread support
- GUI support
- etc.

Some answers can be found in the current documentation (which is a great read btw). However, more detailed explanations have been posted in the other _threads_ like hackernews (blockers for `clone()` on posix, willingness to accept raw x11 support, but caveats). The suggestion here is just to have section in readme, or page on your docs explaining where each major thing is at.  

Also, your projects might see a huge influx of brilliant and eager contributors, so dropping breadcrumbs about "good places for contributors to dump effort" is helpful. 

Also, a contributing section with comments like this are great way to help people understand intention:
> so far Cosmopolitan has mostly refrained from defining novel interfaces, since the focus has been twiddling with low level magic numbers in order to make the textbook interfaces we already have work everywhere!

**Comment by jart** [comment]
It isn't a question of limitations. It's a question of focus.

Cosmopolitan a scrappy project. What's helped us have a lot of impact so far is a razor sharp focus on the few things that yield the most bang for the buck. I've used a simple tool to help me do that, and you can use it too. Check out the magic numbers used by system interfaces in [libc/sysv/syscalls.sh](https://github.com/jart/cosmopolitan/blob/master/libc/sysv/syscalls.sh) which tells us which ideas have consensus and which ones don't. 

Big things have small beginnings, so I don't want to come across as ruling out any of the awesome things folks have requested. I think threads are great. I love graphical user interfaces too. It's just that there's no obvious path forward for those things in the numbers file. Nothing's impossible. There isn't anything about Cosmopolitan's design that would limit it from having such things in the future. It's simply a question of resources and this project aims to bring you the most value with what it has.

**Comment by solvingj** [comment]
Sounds good!
