### ISSUE TITLE
[Feature Request] to add async function calling in redbean-lua

### ISSUE THREAD

**Issue by diyism** [jart/cosmopolitan#615]
I used to use the nginx-lua / openresty web server, there are 2 ways to run async tasks in it:
1.
```
ngx.say("bye bye, my user");
ngx.eof()      --close the client(browser) http connection without closing the lua process
a_task_function_cost_much_time(para1, para2, ...)
```
2.
```
ngx.timer.at(0, a_task_function_cost_much_time, para1, para2, ...)
ngx.say("bye bye, my user")
ngx.exit(200)
```

If we have a "async(fun, time_out)" in redbean-lua, It's very useful to request a time-costing url:
```
local function fetch_url(url)
    status, headers, payload = Fetch(url)
end
async(fetch_url(...), time_out)
```

Just a naive wish.

**Comment by pkulchenko** [comment]
@diyism, all these options are available with redbean already, as it allows closing the http connection with `unix.close(GetClientFd())` and continuing with the Lua script. You can also set a timer with `unix.setitimer` or use `OnServerHeartbeat` to schedule/run periodic tasks as needed. You can also fork a separate process to run background tasks.

I'm not sure what `async()` would do in the case of slow/time-consuming URL request if there is nothing for the requesting process to do at this time, as nothing is blocked. Redbean is a forking server, which is a very different architecture from the event-driven one that Nginx is using.

**Comment by jart** [comment]
The redbean unix module is designed to give you the power to implement whatever i/o abstraction you want. It'd be great to see someone in the community use it implement an async framework for redbean that makes it behave more like OpenResty. If you want to be the one to build it, we'll support you. I'm going to close this issue because it isn't a feature request. Thanks for reaching out.

**Comment by diyism** [comment]
Amaing, it seems that all things in nginx that I like have been realized in redbean web server.
I have a dream to build a blockchain administrated mesh network of home-hosted web servers,
so redbean is the best foundation stone, thanks to @pkulchenko , @jart

**Comment by diyism** [comment]
@pkulchenko   I've tested the "unix.close(GetClientFd())":

```
SetStatus(200)
SetHeader('Content-Type', 'text/plain; charset=utf-8')
Write('bye bye, my user')
unix.close(GetClientFd())

--continue to do something cost time
```

the browser shows "The connection was reset",
it's not the same effect with the ngx.eof(),
nginx-lua will show the "bye bye, my user" correctly.

Any idea?

**Comment by jart** [comment]
That's because redbean doesn't send the response until after your lua server page has finished running. If you want to use `unix.close` on the raw file descriptor, then you have to use `unix.write` to send an HTTP response manually.

**Comment by diyism** [comment]
Yes, it works now:
```
unix.write(GetClientFd(), 'bye bye, my user1')
unix.close(GetClientFd())
--continue to do something cost time
```
Thanks
