### ISSUE TITLE
cosmipolitan/tty.c - GetXlatSgr()

### ISSUE THREAD

**Issue by paulwratt** [jart/cosmopolitan#626]
is it just me of is **bold** missing from `GetXlatSgr` at [line 180 in tty.c](https://github.com/jart/cosmopolitan/blob/55b8af325061bbe3b6e589a968a05207c94d825f/libc/vga/tty.c#L180)

```c
static wchar_t *GetXlatSgr(struct Tty *tty) {
  switch (!!(tty->pr & kTtyFraktur) << 2 | !!(tty->pr & kTtyItalic) << 1 |
          !!(tty->pr & kTtyBold) << 0) {
    case 0b100:
    case 0b110:
      return GetXlatFraktur();
    case 0b101:
    case 0b111:
      return GetXlatBoldFraktur();
    case 0b011:
      return GetXlatBoldItalic();
    case 0b010:
      return GetXlatItalic();
    default:
      return GetXlatAscii();
  }
}

```
maybe should be:
```c
    case 0b010:
      return GetXlatItalic();
    case 0b001:
      return GetXlatBold();
    default:
      return GetXlatAscii();
```
with an accompanying (also unimplemented) `GetXlatBold()`

**Comment by jart** [comment]
Xlat is for character translation maps. The code for supporting bold text is:

https://github.com/jart/cosmopolitan/blob/be29b709b7e74807f9c7bb965847f1c294e0ff4c/tool/build/lib/pty.c#L756-L759

**Comment by paulwratt** [comment]
The `GetXlatSgr` in `pty.c` also does not call out to a `GetXlatBold()` either. Since alot of `tty.c` came directly from there that makes sense, as they do the same think in different context. There are _combined Bold_ calls, but not _plain Bold_ call. The bit/switch/flag is set and reset, but its never _acted_ on, unlike the (unimplemented) _combined_ versions.
