### ISSUE TITLE
`make -j12` fails on Arch Linux

### ISSUE THREAD

**Issue by xyproto** [jart/cosmopolitan#632]
Hi,

I just tried following the tutorial. After cloning the repository and running `make -j12` on my system, I get many errors.

The last 10 lines of the output are:

```
make: *** [build/rules.mk:168: o/ape/loader.h.ok] Error 127
02fc:fixme:file:GetLongPathNameW UNC pathname L"\\\\?\\Z:\\home\\alexander\\cl"

`make MODE= -j0 o/ape/config.h.ok` exited with 127:
o/third_party/gcc/bin/x86_64-linux-musl-gcc -S -Wall -Werror -fdebug-prefix-ma_
consumed 72,879µs wall time
needed 20,000us cpu (100% kernel)

make: *** [build/rules.mk:168: o/ape/config.h.ok] Error 127
```

The full output from running `make  -j12` is here:

[stderr.txt](https://github.com/jart/cosmopolitan/files/9615136/stderr.txt)

I'm looking forward to trying out cosmopolitian some time, I really like the idea!

**Comment by ahgamut** [comment]
Seems like `binfmt_misc`? @xyproto perhaps [this comment](https://github.com/jart/cosmopolitan/issues/356#issuecomment-1174055078) from #356 or https://redbean.dev/#install might help.

**Comment by xyproto** [comment]
@ahgamut Thanks for the pointer, but I use a regular Arch Linux Linux kernel and do not have any kernel module named something with `binfmt` loaded, according to `lsmod | grep binfmt`.

**Comment by tkchia** [comment]
Hello @xyproto,

It is possible that `binfmt_misc` is compiled right inside the kernel rather than available as a module &mdash; in this case `lsmod` will not show it.

Perhaps you can also try checking if your system has a `/proc/sys/fs/binfmt_misc/` directory?

Thank you!

**Comment by xyproto** [comment]
Yes, `/proc/sys/fs/binfmt_misc` is there.

Apparently, it's included in the plain vanilla Arch Linux kernel:

```
zcat /proc/config.gz| grep -i binfmt
CONFIG_BINFMT_ELF=y
CONFIG_COMPAT_BINFMT_ELF=y
CONFIG_BINFMT_SCRIPT=y
CONFIG_BINFMT_MISC=y
```

**Comment by tkchia** [comment]
Hello @xyproto,

Ah.  In that case, you can try either of the two sets of instructions at https://redbean.dev/#install (as mentioned by @ahgamut), and see if things work better.  Thank you!

**Comment by xyproto** [comment]
But, my ambitions is not only to try it out, but also to package it for Arch Linux if it appears to be useful.

I think the package not building from source with `make` on the (in my opinion) most vanilla of all Linux distros should be considered an issue.

**Comment by tkchia** [comment]
Hello @xyproto,

The problem is not exactly very easy to solve unfortunately on the Cosmopolitan side of things.

And personally, I think this is a bug on the Wine side of things.  It tries to take over the execution of _every_ program that kind of looks remotely like it _might_ be a Windows executable (including MS-DOS programs and [Mono apps](https://bbs.archlinux.org/viewtopic.php?id=238357)), which is what is causing your problem.  I am not sure that this behaviour is a good thing.

Thank you!

**Comment by xyproto** [comment]
That makes sense, @tkchia. Thanks for the insightful replies.

**Comment by tkchia** [comment]
Hello @xyproto,

Incidentally, I use Ubuntu, which has separate packages for `wine` itself and its `binfmt_misc` registration (the package is called `wine-binfmt`).

```
$ apt show wine-binfmt
Package: wine-binfmt
Version: 6.0.3~repack-1
Priority: optional
Section: universe/otherosfs
Source: wine
Origin: Ubuntu
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Original-Maintainer: Debian Wine Party <debian-wine@lists.debian.org>
Bugs: https://bugs.launchpad.net/ubuntu/+filebug
Installed-Size: 110 kB
Depends: wine, binfmt-support
Homepage: https://www.winehq.org
Download-Size: 5,526 B
APT-Sources: http://www.gtlib.gatech.edu/pub/ubuntu jammy/universe amd64 Packages
Description: Register Wine as the interpreter for Windows executables
 Wine is a free MS-Windows API implementation.
 .
 This package registers Wine as an interpreter for Windows executables, using
 the kernel binfmt_misc module.  This causes Wine to be invoked automatically
 whenever a Windows PE (Portable Executable) file is to be launched.
 .
 WARNING:  This increases the risk of inadvertently launching Windows
 malware, so please make sure that you understand the security risks before
 blindly installing this package.
 .
 This feature is probably most interesting for automatic software testing.
 Desktop users usually don't need it, so don't install wine-binfmt unless you
 know that you need it.  Refer to Wine's README.debian for more information.
```

This arrangement happens to avert the problem.

Thank you!

**Comment by jart** [comment]
We intend to patch the Linux kernel to run APE binaries natively soon, due to these namespace conflicts with distros that install WINE. We document the workaround for this in several places. I'm going to close this out but thank you for the report. It's something we're actively working to improve.
