### ISSUE TITLE
issues with mkntcmdline quote handling

### ISSUE THREAD

**Issue by G4Vi** [jart/cosmopolitan#644]
Attempting to implement `system()` for perl on NT using `excl`, I've enter countered issues with quoting that also apply to cosmopolitan's `system()`.

It appears with  `cmd.exe /c` filenames can just be passed with additional quoting without escaping:

From a interactive Command Prompt:
```batch
D:\Personal>cmd.exe /c "echo abc>"name with spaces.txt""
D:\Personal>cmd.exe /c "more < "name with spaces.txt""
abc
```

However, attempting to run the commands from cosmopolitan's `system()` fails, note I just added the below tests, they are not in cosmopolitan.
```batch
D:\Personal>mkntcmdline_test.com
The filename, directory name, or volume label syntax is incorrect.
error:test/libc/calls/mkntcmdline_test.c:96: mkntcmdline_fixAsBestAsWeCanForNow1() on MINI-DISPENSER pid 9948 tid 9952
        EXPECT_EQ(0, system("echo abc>\"name with spaces.txt\""))
                need 0  (or 0 or  =
                 got 256        (or 0x100)
        EUNKNOWN/0/No error information/6/The handle is invalid
        mkntcmdline_test.com @ MINI-DISPENSER
The system cannot find the file specified.
error:test/libc/calls/mkntcmdline_test.c:97: mkntcmdline_fixAsBestAsWeCanForNow1() on MINI-DISPENSER pid 9948 tid 9952
        EXPECT_EQ(0, system("more < \"name with spaces.txt\""))
                need 0  (or 0 or  =
                 got 256        (or 0x100)
        EUNKNOWN/0/No error information/6/The handle is invalid
        mkntcmdline_test.com @ MINI-DISPENSER
```

This appears to be caused from cosmopolitan attempting to escape the `"` pair for the filename instead of just passing it as is, actually passing `\"name with spaces\"` to cmd.exe with the backslashes

**Comment by jart** [comment]
Looks like the right thing to do is escaping like `cmd.exe /c "echo hello2 >"""foo bar.txt"""". Triple quoting quotes appears to be correctly implemented in `GetDosArgv()` but for some reason `mkntcmdline()` was implemented to use backslash. I'm addressing this now. There'll be a release too, soon, to incorporate this. I'd also get this backported into the vista branch.
