### ISSUE TITLE
memzoom on Windows 10 for binary file fails "open() failed"

### ISSUE THREAD

**Issue by jtmoon79** [jart/cosmopolitan#65]
tl;dr Under Powershell and `cmd.exe`, tried to read `notepad.exe` with various invocation strings; all failed `error: open() failed: C:\Windows\system32\notepad.exe`

The `memzoom` Download page suggest Windows-based analysis of a binary file should work.
> If your system doesn't have /proc you can still view binary files. 

Using Powershell 5.1.19041.610 on a Windows 10.0.19041 host, inside a Windows Sandbox
```
PS C:\Users\WDAGUtilityAccount\Downloads> dir C:\Windows\system32\notepad.exe


    Directory: C:\Windows\system32


Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a----         1/13/2021   1:03 AM         202240 notepad.exe

PS C:\Users\WDAGUtilityAccount\Downloads> .\memzoom-2021-01-24.com C:\Windows\system32\notepad.exe
error: open() failed: C:\Windows\system32\notepad.exe

PS C:\Users\WDAGUtilityAccount\Downloads> memzoom-2021-01-24.com C:\Windows\system32\notepad.exe
...
    + FullyQualifiedErrorId : CommandNotFoundException
...

PS C:\Users\WDAGUtilityAccount\Downloads> $env:PATH+=";."

PS C:\Users\WDAGUtilityAccount\Downloads> memzoom-2021-01-24.com C:\Windows\system32\notepad.exe
error: open() failed: C:\Windows\system32\notepad.exe

PS C:\Users\WDAGUtilityAccount\Downloads> memzoom-2021-01-24.com "C:\Windows\system32\notepad.exe"
error: open() failed: C:\Windows\system32\notepad.exe

PS C:\Users\WDAGUtilityAccount\Downloads> memzoom-2021-01-24.com "C:/Windows/system32/notepad.exe"
error: open() failed: C:/Windows/system32/notepad.exe

PS C:\Users\WDAGUtilityAccount\Downloads> memzoom-2021-01-24.com "c:/Windows/system32/notepad.exe"
error: open() failed: c:/Windows/system32/notepad.exe

PS C:\Users\WDAGUtilityAccount\Downloads> memzoom-2021-01-24.com "c:\Windows\system32\notepad.exe"
error: open() failed: c:\Windows\system32\notepad.exe

PS C:\Users\WDAGUtilityAccount\Downloads> move-item .\memzoom-2021-01-24.com .\memzoom.com

PS C:\Users\WDAGUtilityAccount\Downloads> memzoom.com "C:\Windows\system32\notepad.exe"
error: open() failed: C:\Windows\system32\notepad.exe
```
Similar for `cmd.exe`
```
C:\Users\WDAGUtilityAccount\Downloads>PATH=%PATH%;.

C:\Users\WDAGUtilityAccount\Downloads>memzoom-2021-01-24.com "C:\Windows\system32\notepad.exe"
error: open() failed: C:\Windows\system32\notepad.exe
```

---

The memzoom Download page suggests that invocation particulars may matter. Hence the many variations.

> Windows Notes
> You may need to run:
> `memzoom.com -h`
> Instead of:
> `./memzoom.com -h`

**Comment by alisonatwork** [comment]
Did you try compiling this from the latest source? For me on HEAD the application compiles and shows the visualization as expected, but keyboard input isn't working. You could also try opening an executable in the current directory, in case the problem on that version is related to resolving relative directory paths.

**Comment by jtmoon79** [comment]
> Did you try compiling this from the latest source?

I considered it until I remembered how much work compiling from a Windows Command-line is.
Weird obscure paths to various `Libs` and special flags for special `.dll`, etcetera.

**Comment by jtmoon79** [comment]
> You could also try opening an executable in the current directory

Good guess @alisonatwork .  Worked!

After some testing, it appears the binary file analyzed must be in the same directory as `memzoom.com`.  Current working directory does not matter.

@jart may want to add a note to the Downloads or help like

> Windows version can only analyze binary files residing the same directory as `memzoom.com`.

**Comment by jart** [comment]
You should be able to memzoom the notepad executable in the system32 folder now. That issue likely got fixed at some point in the past month, possibly when I was perfecting the mmap() code in 2fdc19e7a7f4b6b880f37c9f40ef0135e80706d2. I did some further digging and there turned out to be another issue which has now been addressed. I've also taken the liberty of pushing a new release of Memzoom to the website which can be downloaded here: https://justine.lol/memzoom/download.html Thanks again for the report and for using Cosmopolitan!

**Comment by jtmoon79** [comment]
This worked. Thanks!
```
PS C:\Users\WDAGUtilityAccount> C:\Users\WDAGUtilityAccount\Downloads\memzoom-2021-02-27.com C:\Windows\system32\notepad.exe
```
