### ISSUE TITLE
Tests failing on WSL

### ISSUE THREAD

**Issue by JoshuaWierenga** [jart/cosmopolitan#665]
After noting the setrlimit_test.c test failing in #646 I tried to reproduce it outside of wsl but hit a different error on a fresh ubuntu 22.04.1 vm with the master branch.

```
test/tool/net/lunix_test.lua:131: assertion failed!
test/tool/net/lunix_test.lua:169: UnixTest failed (o/tmp/o/tmp/lunix_test.190074)
stack traceback:
[C]: in function 'error'
test/tool/net/lunix_test.lua:169: in function 'main'
test/tool/net/lunix_test.lua:173: in main chunk

`make MODE= -j4 o//test/tool/net/lunix_test.lua.runs` exited with 2:
o//tool/net/redbean.com -i test/tool/net/lunix_test.lua
consumed 78,178µs wall time
ballooned to 2,748kb in size
needed 3,298us cpu (0% kernel)
caused 320 page faults (100% memcpy)
14 context switches (50% consensual)
performed 19 read and 0 write i/o operations
```

I tried to continue the build to see if it would reoccur and got a different error:
```
error:test/libc/calls/ftruncate_test.c:95: ftruncate_test() on ubuntu-vm-xpra pid 191370 tid 191370
	ASSERT_EQ(4096 / 512, st.st_blocks)
		need 8	(or 0x8 or '◘') =
		 got 2	(or 0x2 or '☻')
	EUNKNOWN/0/No error information
	o//test/libc/calls/ftruncate_test.com @ ubuntu-vm-xpra
1 / 46 tests failed

`make MODE= -j4 o//test/libc/calls/ftruncate_test.com.runs` exited with 1:
o//test/libc/calls/ftruncate_test.com
consumed 1,771µs wall time
ballooned to 332kb in size
needed 1,682us cpu (0% kernel)
caused 114 page faults (35% memcpy)
performed 9 read and 0 write i/o operations

make: *** [build/rules.mk:133: o//test/libc/calls/ftruncate_test.com.runs] Error 1
```
Trying to continue the build from now on just gives this error again with no trace of either of the previous setrlimit_test.c or luniux_test.lua errors.

**Comment by jart** [comment]
I'm working on getting WSL in tip top shape. Here's the changes I've made so far:

- d6ff4c754e22f151a4c3b0a2550ad641f32e03f5 Workaround WSL misconfiguring the x87 FPU
- f44d88707e68de5e2f177df2b3872a3bd76dee4f Workaround sendfile() bug in WSL
- fc96af058bda94968df3b37932d152718df15f3d Workaround MAP_GROWSDOWN unavailability on WSL

It seems like we've written a lot of system call tests since the last time I ran a full build on WSL, which are illuminating all the weird breakages that Microsoft did with its Linux-like environment.

**Comment by jart** [comment]
It's worth mentioning that you can build binaries in the repository without running the tests. For example:

```
make -j8 o//examples
make -j8 o//examples/hello.com
```

Are both valid ways to build the hello.com program. You can do that for any target and any package.

**Comment by jart** [comment]
Anyone who's reading this issue that uses Cosmopolitan and WSL, could you please respond and tell me if you're using WSL 1 or WSL 2? If you're not sure, then you can run `wsl -l -v` in PowerShell to find out.

**Comment by jart** [comment]
I'm proud to announce that WSL2 is part of our distributed test fleet. Our complete set of hundreds of tests pass on WSL now. They'll be regression tested every time a change is submitted to GitHub.
