### ISSUE TITLE
"CIL Image" error attempting to run cosmopolitan executable in Github Actions CI environment

### ISSUE THREAD

**Issue by brenhinkeller** [jart/cosmopolitan#674]
In order to test that my code is working correctly, I'm attempting to compile and run a cosmopolitan executable as part of my github actions CI. The compilation part seems to be working fine as far as I can tell (producing an executable of the expected size and permissions)
```
-rwxr-xr-x  1 runner docker 124K Oct 25 05:11 times_table.com
```
but when I try to actually _run_ this in the same CI environment
```
Cannot open assembly './times_table.com': File does not contain a valid CIL image.
```
Is there any known workaround for this, or any suggestions on what to try?

**Comment by pkulchenko** [comment]
Is this the same issue as discussed [here](https://github.com/jart/cosmopolitan/issues/356#issuecomment-1043202698)?

**Comment by brenhinkeller** [comment]
Ah, so it is! Not sure why that and https://github.com/jart/cosmopolitan/issues/586 didn't come up in googling but thanks for your help!
