### ISSUE TITLE
errno values are "extern const", which isn't a constant integer expression

### ISSUE THREAD

**Issue by mulle-nat** [jart/cosmopolitan#675]
My problem is that:

``` c
switch( errno)
{
case ENOENT:  ;
}
``` 

doesn't compile: The error is  `error: expression is not an integer constant expression`. That's because `ENOENT` is actually a macro (which is correct, as the [C Standard](https://en.cppreference.com/w/cpp/error/errno_macros) defines it so) that resolves to an `extern const errno_t ERRNO`. Though this has the `const` keyword, that doesn't make it a [constant integer expression](https://stackoverflow.com/questions/14081737/clarification-on-integer-constant-expressions). 

With respect to the C standard, that's broken, so that's a clear disadvantage. Also I don't see any advantage in having these values not plain integers.

**Comment by pkulchenko** [comment]
@mulle-nat, this has been discussed in several tickets; most recently [here](https://github.com/jart/cosmopolitan/issues/103#issuecomment-791351951). These statements will need to be updated to work with cosmopolitan. Yes, this is inconvenient, but @jart already provided rationale for this design decision in the ticket I referenced. Also see [this comment for further details on this topic](https://github.com/rust-lang/rfcs/pull/3305#issuecomment-1238864430).
