### ISSUE TITLE
`uname` function inconsistency in WSL environment

### ISSUE THREAD

**Issue by ONLYA** [jart/cosmopolitan#676]
The code `hello.c` uses `uname` to retrieve the platform information. Running `hello.com` will return "Windows" in WSL instead of "Linux" while it returns proper value on a real Linux machine. However, running `hello.com.dbg` will return "Linux" on WSL.
The code is:
```c
#include <stdio.h>
#include <stdlib.h>
#include <errno.h>
#include <sys/utsname.h>

int main(void) {

   struct utsname buffer;

   errno = 0;
   if (uname(&buffer) < 0) {
      perror("uname");
      exit(EXIT_FAILURE);
   }

   printf("system name = %s\n", buffer.sysname);
   printf("node name   = %s\n", buffer.nodename);
   printf("release     = %s\n", buffer.release);
   printf("version     = %s\n", buffer.version);
   printf("machine     = %s\n", buffer.machine);

   #ifdef _GNU_SOURCE
      printf("domain name = %s\n", buffer.domainname);
   #endif

   return EXIT_SUCCESS;
}

```

For your convenience, you can compile this easily with https://github.com/ONLYA/Display_only/tree/master/9.
I guess it might go through some strange processes to somehow retrieve the information about the root system.

**Comment by jart** [comment]
That's because your program is running as a win32 binary. It's a known issue. Try running:

```
sudo sh -c 'echo -1 >/proc/sys/fs/binfmt_misc/status'
```

I also recommend running:

```
ape/apeinstall.sh
```

We're working on getting the Linux kernel patched so this isn't an issue anymore.
