### ISSUE TITLE
ape error: phdrs must be 4096-aligned,

### ISSUE THREAD

**Issue by mulle-nat** [jart/cosmopolitan#679]
I get this error, when running a linked executable, which I don't understand. What are `phdrs` and how can I influence their makeup ?

``` sh
ape error: ./kitchen/cosmopolitan/Debug/xxx1: APE phdrs must be 4096-aligned and 4096-padded
```

**Comment by mulle-nat** [comment]
I think the answer to this is no. If I leave a certain (self-compiled) `o` file out of the build process, then things work. But when I add this `o` file, I get the error. Now I could get into more details, but maybe just understanding what `phdrs` could help me fix this. Or maybe it won't :smile:

**Comment by jart** [comment]
Maybe what you need is `-Wl,-zmax-page-size=0x1000`.

Background time. Here's an example. If I use the `assimilate.com` program on `hello.com` to turn it into an ELF file, then run `readelf -Wa hello.com`, then I get this:

```
Program Headers:
  Type           Offset   VirtAddr           PhysAddr           FileSiz  MemSiz   Flg Align
  LOAD           0x000000 0x0000000000400000 0x0000000000002000 0x012000 0x012000 R E 0x1000
  LOAD           0x012000 0x0000000000412000 0x0000000000014000 0x001000 0x005000 RW  0x1000
  GNU_STACK      0x013000 0x0000700000000000 0x0000000000015000 0x000000 0x010000 RW  0x10
  NOTE           0x000b08 0x0000000000400b08 0x0000000000002b08 0x000030 0x000030 R   0x8
```

Those `LOAD` program headers are all 0x1000 or 4096 byte aligned. The APE format requires that all your program headers be like that. Otherwise it won't run on Windows. If you're linking code into your binary that's causing program headers to be generated that aren't page-size aligned, then you'll need to tune your compiler flags so whatever feature that is doesn't do it anymore.

Please note that the program headers in the com.dbg binary are different. Those actually are generated by the linker, whereas the program headers in the .com file are generated by `ape/ape.S`. Here's what `hello.com.dbg`'s program headers look like:

```
Program Headers:
  Type           Offset   VirtAddr           PhysAddr           FileSiz  MemSiz   Flg Align
  LOAD           0x001000 0x0000000000400000 0x0000000000002000 0x001000 0x001000 R E 0x1000
  LOAD           0x002000 0x0000000000401000 0x0000000000003000 0x011000 0x011000 R E 0x1000
  LOAD           0x013000 0x0000000000412000 0x0000000000014000 0x001000 0x001000 RW  0x1000
  TLS            0x014000 0x0000000000413000 0x0000000000413000 0x000000 0x000000 RW  0x1
  LOAD           0x014000 0x0000000000413000 0x0000000000015000 0x000000 0x004000 RW  0x1000
  GNU_STACK      0x000000 0x0000000000000000 0x0000000000000000 0x000000 0x000000 RW  0x8
```

Here again we see all the `LOAD` ones are page-aligned.

In any case, could you please share more about what you're doing and what your use case is? I love hearing about the uses folks get out of my work. Specifics are great and you're welcome to contact me in privately if you wish. Thanks!

**Comment by mulle-nat** [comment]
Thanks for the detailed response! OK, so what I am trying to do - in once sentence - is getting my [Objective-C compiler](//github.com/mulle-cc/mulle-clang-project) to be compatible with *cosmopolitan*. It's working OK with *glibc*, *System.dylib* and *musl* (and windows libs for that matter), but cosmopolitan so far presents a problem. The compiler is basically *clang* with some changes. If I get into specifics, I could write a book :smile: 

I used your suggestion with `-zmax-page-size=0x1000`, but there was no difference in outcome, I still get the ape error. So I dumped the linked executable before running it through `objcopy` and looked at the addresses and alignments of the LOAD, but they look OK to me:

```
Program Headers:
  Type           Offset   VirtAddr           PhysAddr           FileSiz  MemSiz   Flg Align
  LOAD           0x001000 0x0000000000400000 0x0000000000002000 0x001000 0x001000 R E 0x1000
  LOAD           0x002000 0x0000000000401000 0x0000000000003000 0x061000 0x061000 R E 0x1000
  LOAD           0x063000 0x0000000000462000 0x0000000000064000 0x001048 0x001048 RW  0x1000
  TLS            0x064048 0x0000000000463048 0x0000000000065048 0x000000 0x3fefb8 RW  0x1
  LOAD           0x000000 0x0000000000464000 0x0000000000066000 0x000000 0x04b000 RW  0x1000
  GNU_STACK      0x000000 0x0000000000000000 0x0000000000000000 0x000000 0x000000 RW  0x8
```

Now neither the `TLS` offset nor the `GNU_STACK` are page aligned, but neither are they in your example (also 0x1 and 0x8), but your `TLS` offset is (is this a hint).

The complete elf dump without symbols:

```
ELF Header:
  Magic:   7f 45 4c 46 02 01 01 00 00 00 00 00 00 00 00 00 
  Class:                             ELF64
  Data:                              2's complement, little endian
  Version:                           1 (current)
  OS/ABI:                            UNIX - System V
  ABI Version:                       0
  Type:                              EXEC (Executable file)
  Machine:                           Advanced Micro Devices X86-64
  Version:                           0x1
  Entry point address:               0x402442
  Start of program headers:          64 (bytes into file)
  Start of section headers:          2541232 (bytes into file)
  Flags:                             0x0
  Size of this header:               64 (bytes)
  Size of program headers:           56 (bytes)
  Number of program headers:         6
  Size of section headers:           64 (bytes)
  Number of section headers:         20
  Section header string table index: 19

Section Headers:
  [Nr] Name              Type            Address          Off    Size   ES Flg Lk Inf Al
  [ 0]                   NULL            0000000000000000 000000 000000 00      0   0  0
  [ 1] .head             PROGBITS        0000000000400000 001000 001000 00  AX  0   0  8
  [ 2] .text             PROGBITS        0000000000401000 002000 061000 00  AX  0   0 4096
  [ 3] .data             PROGBITS        0000000000462000 063000 001000 00  WA  0   0 16

  [ 4] __DATA,_objc_load_info PROGBITS        0000000000463000 064000 000048 00  WA  0   0  8

  [ 5] .tdata            NOBITS          0000000000463048 064048 000fb8 00 WAT  0   0  1
  [ 6] .tbss             NOBITS          0000000000464000 064048 000000 00 WAT  0   0  1
  [ 7] .bss              NOBITS          0000000000464000 065000 04b000 00  WA  0   0 64
  [ 8] .debug_aranges    PROGBITS        0000000000000000 064050 007ff0 00      0   0 16
  [ 9] .debug_info       PROGBITS        0000000000000000 06c040 0d5450 00      0   0  1
  [10] .debug_abbrev     PROGBITS        0000000000000000 141490 01f984 00      0   0  1
  [11] .debug_line       PROGBITS        0000000000000000 160e14 05571f 00      0   0  1
  [12] .debug_frame      PROGBITS        0000000000000000 1b6538 007910 00      0   0  8
  [13] .debug_str        PROGBITS        0000000000000000 1bde48 01bcca 01  MS  0   0  1
  [14] .debug_loc        PROGBITS        0000000000000000 1d9b12 05be39 00      0   0  1
  [15] .debug_ranges     PROGBITS        0000000000000000 235950 0084e0 00      0   0 16
  [16] .GCC.command.line PROGBITS        0000000000000000 23de30 010432 01  MS  0   0  1
  [17] .symtab           SYMTAB          0000000000000000 24e268 011520 18     18 1572  8
  [18] .strtab           STRTAB          0000000000000000 25f788 00ce56 00      0   0  1
  [19] .shstrtab         STRTAB          0000000000000000 26c5de 0000ce 00      0   0  1
Key to Flags:
  W (write), A (alloc), X (execute), M (merge), S (strings), I (info),
  L (link order), O (extra OS processing required), G (group), T (TLS),
  C (compressed), x (unknown), o (OS specific), E (exclude),
  D (mbind), l (large), p (processor specific)

There are no section groups in this file.

Program Headers:
  Type           Offset   VirtAddr           PhysAddr           FileSiz  MemSiz   Flg Align
  LOAD           0x001000 0x0000000000400000 0x0000000000002000 0x001000 0x001000 R E 0x1000
  LOAD           0x002000 0x0000000000401000 0x0000000000003000 0x061000 0x061000 R E 0x1000
  LOAD           0x063000 0x0000000000462000 0x0000000000064000 0x001048 0x001048 RW  0x1000
  TLS            0x064048 0x0000000000463048 0x0000000000065048 0x000000 0x3fefb8 RW  0x1
  LOAD           0x000000 0x0000000000464000 0x0000000000066000 0x000000 0x04b000 RW  0x1000
  GNU_STACK      0x000000 0x0000000000000000 0x0000000000000000 0x000000 0x000000 RW  0x8

 Section to Segment mapping:
  Segment Sections...
   00     .head 
   01     .text 
   02     .data __DATA,_objc_load_info 
   03     .tdata .tbss 
   04     .bss 
   05     

There is no dynamic section in this file.

There are no relocations in this file.
No processor specific unwind information to decode
```

Just for fun, I ran `assimilate.com` (the `-f` flag doesn't seem to work) on the APE executable. I get some warnings there. In the way the program behaves, I see that Objective-C data values have been lost (zeroed) in the process:

```
ELF Header:
  Magic:   7f 45 4c 46 02 01 01 09 00 00 00 00 00 00 00 00 
  Class:                             ELF64
  Data:                              2's complement, little endian
  Version:                           1 (current)
  OS/ABI:                            UNIX - FreeBSD
  ABI Version:                       0
  Type:                              EXEC (Executable file)
  Machine:                           Advanced Micro Devices X86-64
  Version:                           0x1
  Entry point address:               0x402442
  Start of program headers:          2600 (bytes into file)
  Start of section headers:          0 (bytes into file)
  Flags:                             0x0
  Size of this header:               64 (bytes)
  Size of program headers:           56 (bytes)
  Number of program headers:         4
  Size of section headers:           0 (bytes)
  Number of section headers:         0
  Section header string table index: 0

There are no sections in this file.

There are no section groups in this file.

Program Headers:
  Type           Offset   VirtAddr           PhysAddr           FileSiz  MemSiz   Flg Align
  LOAD           0x000000 0x0000000000400000 0x0000000000002000 0x062000 0x062000 R E 0x1000
  LOAD           0x062000 0x0000000000462000 0x0000000000064000 0x001fb8 0x04d000 RW  0x1000
  GNU_STACK      0x063fb8 0x0000700000000000 0x0000000000065fb8 0x000000 0x010000 RW  0x10
  NOTE           0x000b08 0x0000000000400b08 0x0000000000002b08 0x000030 0x000030 R   0x8

There is no dynamic section in this file.

There are no relocations in this file.
No processor specific unwind information to decode

Dynamic symbol information is not available for displaying symbols.

No version information found in this file.

Displaying notes found at file offset 0x00000b08 with length 0x00000030:
  Owner                Data size 	Description
  OpenBSD              0x00000004	NT_VERSION (version)	   description data: 07 00 00 00 
readelf: Warning: note with invalid namesz and/or descsz found at offset 0x20
readelf: Warning:  type: 0x4453, namesize: 0x00000001, descsize: 0x4274654e, alignment: 8
```

What else did I do ? I used the bfd linker explicitly to build a glibc based executable and objcopied it once. But that went OK.

**Comment by jart** [comment]
This line looks suspect:

```
  [ 2] .text             PROGBITS        0000000000401000 002000 061000 00  AX  0   0 4096
```

It's irregular for something in `.text` to have that big of an alignment requirement. But that doesn't seem to be the problem. I tried adding `.align 4096` to one of my code files, and the APE binary ran just fine.

Could you please attach your `.o` file to a comment on this issue tracker? If you can help me reproduce this issue locally, then I can fiddle around and find out what's wrong.

**Comment by tkchia** [comment]
Hello @mulle-nat, hello @jart,

It seems that this program header is the one causing the issue:

> ```
>   Type           Offset   VirtAddr           PhysAddr           FileSiz  MemSiz   Flg Align
> ...
>   LOAD           0x062000 0x0000000000462000 0x0000000000064000 0x001fb8 0x04d000 RW  0x1000
> ```

If each program header must be "4096-padded", i.e. padded to a multiple of `0x1000` bytes, so the file image size `FileSiz` being `0x1fb8` bytes will be a problem.

> ```
>  Section to Segment mapping:
>   Segment Sections...
>    00     .head 
>    01     .text 
>    02     .data __DATA,_objc_load_info 
>    03     .tdata .tbss 
>    04     .bss 
>    05     
> ```

It looks like the `__DATA,__objc_load_info` section is an orphan section that is not covered by the `ape/ape.lds` linker script?

Thank you!

**Comment by mulle-nat** [comment]
@tkchia your thoughts sound very plausible to me.

@jart  here is the `main.m.o` file, it needs a `printf` and a `mulle_objc_loadinfo_enqueue_nofail` symbol as external linkage.

[main.m.o.zip](https://github.com/jart/cosmopolitan/files/9946643/main.m.o.zip)

Thanks for taking a look at it.

The only special section in `main.m.o`  is I guess the lonely `__DATA,_objc_load_info`. The Objective-C compiler could produce quite a few other sections though. Looking at the compiler source I see:

|  Section | Comment
|------------------------------------------------------------|--|
| `__DATA,__category,regular,no_dead_strip` | |
| `__DATA,__class,regular,no_dead_strip` | |
| `__DATA,__instance_vars,regular,no_dead_strip` | |
|`__DATA,__module_info,regular,no_dead_strip` | |
|`__DATA,_objc_load_info` | Why is there no `regular,no_dead_strip` and a missing underscore ? Probably an oversight by me. |
|`__DATA,__objc_stringobj,regular,no_dead_strip`| |
|`__DATA,__supers,regular,no_dead_strip`| |
|`__DATA,__protocols,regular,no_dead_strip`| |
|`__DATA,__protoclassids,regular,no_dead_strip`| |
|`__DATA,__property,regular,no_dead_strip` | |
|`__DATA,__cat_cls_meth,regular,no_dead_strip` | |
|`__DATA,__cat_inst_meth,regular,no_dead_strip`  | |

These are all arrays of C structs, with no special alignment requirements.

I will append ",regular,no_dead_strip" to see, if it makes any difference. I think it won't though. I believe ",regular,no_dead_strip" is information for the macos linker only. The Apple ObjC runtime is very different, as the symbols aren't really connected to `main` or any `__attribute__((constructor))` functions. They lie there waiting to be found by the runtime. An inattentative linker might strip them off. But in my runtime these symbols are all tied to `__attribute__((constructor))`, so it shouldn't be a problem.

**Comment by tkchia** [comment]
Hello @mulle-nat, hello @jart,

The section names themselves are mightily suspicious.
* `__DATA,__objc_load_info`, `__DATA,__image_info, `no_dead_strip` etc., are clearly Mach-O-isms &mdash; and should only show up in Mach-O object files.  Why are these things inside an ELF object file?
* What is the intended use of these sections?  I am wondering if Apple macOS's dynamic loader (`dyld`) treat these sections in a special way.  Probably the correct thing to do is to try to map them to equivalent structures that will normally appear in an Objective-C implementation for ELF (e.g. GNU `libobjc`).

Thank you!

**Comment by mulle-nat** [comment]
The Apple runtime is somewhat different, in that the Objective-C bits are just lying around and are grabbed at runtime via `dyld` from the runtime. I would guess that `no_dead_strip` inhibits the macho linker from discarding the section.
In my runtime the sections are actually connected to a `__attribute_((constructor))` function, so they shouldn't be discarded by a overzealous linker. I think in terms of linking I don't need those adornments.  I sort of remember though, that I relied on them  in my `gdb` or `lldb` debugger hacks to distinguish between pure C and Objective-C object files. But I would have to check that.

I didn't change the names from the original code, because until now, there was no ill effect. If different section names would demonstrably fix the problem, I would most likely change them.

**Comment by tkchia** [comment]
Hello @mulle-nat,

In that case, I guess you can consider naming the sections something like e.g. `.data.objc_load_info` (if read/write) or `.rodata.objc_load_info` (if read-only), when targeting ELF.  The `ape/ape.lds` linker script should know about these names, and know how to position the sections in the right places.

Thank you!

**Comment by mulle-nat** [comment]
I changed my sections to '.data.objc.objc_load_info' and now the 4096 bytes problem is no more.
