### ISSUE TITLE
calling unix.opendir example twice [outside a function]

### ISSUE THREAD

**Issue by coderofsalvation** [jart/cosmopolitan#682]
So I was just fiddling with this example:

* https://github.com/jart/cosmopolitan/blob/master/tool/net/demo/unix-dir.lua

First of all, this `unix.opendir()` is a very cool function..because: I've never written so little code for so much directory-traversing goodness.
In many scripting languages I've used, it's easy to traverse over directorynames recursively..but then to get more file-attributes you have to fiddle with all kinds of other functions.
So thanks..

Anyways, if I run this code twice, then it only works the first time..but not the second time:

.init.lua
```
function OnHttpRequest()
  require "unix-dir"      -- unix-dir.lua is residing in .lua folder
end
```

However, if I modify the `unix-dir.lua`, and wrap it into a function it **does** work all the time:

.init.lua
```
unixdir = require "unix-dir"
function OnHttpRequest()
  unixdir.serve() -- I've file is residing in .lua folder
end
```

> Question: why is this? I know requiring on the fly is bad performance, but in this I don't really get why it does not work.

**Comment by jart** [comment]
You might be misunderstanding how Lua `require` works. It doesn't run a file. It loads a module.
