### ISSUE TITLE
Netcat / ncat / any network util cosmo port?

### ISSUE THREAD

**Issue by h4sh5** [jart/cosmopolitan#686]
Hi, first of all wanted to say love this project! It's truly amazing to have write-once-run-anywhere-forever binaries <3

Any chance that swiss army knife like utils like netcat/ncat can be ported or is already ported somewhere? I have been looking for a rust alternative for netcat that will by default work on both windows and \*unix but haven't had any luck, and most netcat implementations are platform specific (e.g. GNU netcat uses `fnctl` which i dont think will work on windows

**Comment by jart** [comment]
Yes! Absolutely! Check out https://github.com/jart/cosmopolitan/blob/master/examples/nc.c which should hopefully have all the features you need. If not, send us a PR adding them and I'll merge it.
