### ISSUE TITLE
hellojs.com isn't fully javascript

### ISSUE THREAD

**Issue by bradparks** [jart/cosmopolitan#69]
I dumped the hellojs.com example, and see that it has `example/hello.js` in it, which I expected to be fully javascript, but I see this - is there more documentation on how this could have embedded javascript without using NativePrint ?

![image](https://user-images.githubusercontent.com/185477/109391184-3747cf00-78ec-11eb-9e80-53fecc466a38.png)

**Comment by alisonatwork** [comment]
I would imagine you could just not call the native function. One of the cool things about embedding a JavaScript interpreter in a compiled program is that you can call in to compiled code, which is what this example shows. See also the Duktape example on their website: https://duktape.org/

**Comment by bradparks** [comment]
cool... i will take a look - thanks for the info!

**Comment by jart** [comment]
I'm going to update the example to rename `NativePrint` to be `console.log` so that it's fully JavaScript.
