### ISSUE TITLE
Building PIE's

### ISSUE THREAD

**Issue by tacerus** [jart/cosmopolitan#703]
Hi,

apologies for the rookie question - but is it possible to build ape and redbean position independently?

If I attempt to build ape with `-fPIC -fPIE` compiler and `-pie` linker flags, I get:

`o/third_party/gcc/bin/x86_64-linux-musl-ld.bfd: o//ape/loader-elf.o: relocation R_X86_64_32 against undefined symbol textoff' can not be used when making a PIE object; recompile with -fPIC`

Would appreciate any input!

**Comment by jart** [comment]
You can build individual objects as PIE, but you can't link Actually Portable Executables as PIE. This would be nice to have but we'd have to change the GNU linker and fix bugs it has to do it.

**Comment by tacerus** [comment]
Understood - thank you!
