### ISSUE TITLE
Cosmopolitan 2.2 somewhere does a  #define I (and forgets to undefine it)

### ISSUE THREAD

**Issue by mulle-nat** [jart/cosmopolitan#705]
I ran into a funny compile problem, that I only get with cosmopolitan 2.2. I have no problems compiling the  file [`mulle-sprintf-function.h`](https://github.com/mulle-core/mulle-sprintf/blob/release/src/mulle-sprintf-function.h#L189) with musl or glibc:

```
mulle-sprintf-function.h:189:24: error: expected identifier or '(' before '__extension__'
  189 |    unsigned int        I;
```

This worked fine with the previous cosmopolitan version though. I could fix this with:

``` c
// cosmopolitan weirdness
#ifdef I
# undef I
#endif
```

I don't have time to track this down, as I am busy with my own release and its own problems :weary:

**Comment by ahgamut** [comment]
searching through the repo shows that the `#define I` is part of `libc/imag.h`, which is included in `libc/isystem/complex.h` and `libc/isystem/tgmath.h`.

@jart perhaps this is similar to #403, where the tty constants definitions overlapped with some variables that BLIS was using.

**Comment by jart** [comment]
complex.h is supposed to define `I` (which was a terrible idea btw)

```
$ grep -PR 'define I\b' /usr/include
/usr/include/complex.h:#define I _Complex_I
```

Could you please confirm that you're using the amalgamation header? Because we could should have `I` not be defined in the amalgamation.

**Comment by jart** [comment]
This and #403 are now resolved in cosmopolitan.h and the website's nightly downloads have been updated: https://justine.lol/cosmopolitan/download.html

**Comment by mulle-nat** [comment]
> complex.h is supposed to define I (which was a terrible idea btw)

Wow, I did not know this. There must be some math guy with a lot of clout in the C committee, that is able to push his half-baked ideas like generics through. :laughing: 
Anyway the damage has been inflicted, and I will have change my `I` usage in the next version to stay compatible with C99.

>Could you please confirm that you're using the amalgamation header? Because we should have I not be defined in the amalgamation.

Yes. In order to be able to transparently switch between *cosmopolitan* and *glibc* and *musl* I created a lot of tiny fake headers like this:

`time.h`:

``` c
#ifndef COSMOPOLITAN_H_
# include <cosmopolitan/cosmopolitan.h>
#endif
```

**Comment by jart** [comment]
If your goal is to stay compatible with other C libraries, one option you might consider is using [cosmocc](https://github.com/jart/cosmopolitan/blob/master/tool/scripts/cosmocc) and/or [cosmoc++](https://github.com/jart/cosmopolitan/blob/master/tool/scripts/cosmoc++) as your toolchain.

**Comment by mulle-nat** [comment]
Yeah, but I also need to support my compiler "mulle-clang". So I am somewhat duplicating *cosmocc* in [mulle-cosmopolitan-cc](https://github.com/mulle-cc/mulle-cosmopolitan-cc/blob/master/mulle-clang.cosmopolitan). Also in my build system *cosmopolitan* is local to the project... no system wide installs.

> Looking at your code, I learned something about the bourne shell `set` command, I didn't know yet :face_with_spiral_eyes:
