### ISSUE TITLE
Weird question: Cosmopolitan Rust?

### ISSUE THREAD

**Issue by i2** [jart/cosmopolitan#711]
Hey Justine (@jart)!

Long time follower of your work even before this repo reached 💯 stars. I have a question which I know would sound weird: Have you thought about cosmo-rust? (Please note I'm not in a rust cult at all!)

**Comment by ahgamut** [comment]
https://github.com/ahgamut/rust-ape-example
https://github.com/ahgamut/HVM/tree/cosmopolitan
https://github.com/ahgamut/ripgrep/tree/cosmopolitan

**Comment by i2** [comment]
Good example projects :)

By cosmo-rust, I loosely meant equivalent of what cosmopolitanc is for Rust: build-once run-anywhere rust library.

**Comment by i2** [comment]
What's the benefit of [https://github.com/ahgamut/ripgrep/tree/cosmopolitan](https://github.com/ahgamut/ripgrep/tree/cosmopolitan)?

**Comment by jart** [comment]
@ahgamut's work is cosmo-rust. Please check out the awesome tools he's created.
