### ISSUE TITLE
Cannot run blinkenlights' APE on Arch Linux

### ISSUE THREAD

**Issue by bertulli** [jart/cosmopolitan#719]
Hi!
I wanted to try blinkenlights, but somehow on Arch Linux it doesn't work.
I tried:
```sh
curl https://justine.lol/blinkenlights/hello.elf >hello.elf # all good
curl https://justine.lol/blinkenlights/blinkenlights-latest.com >blinkenlights.com # all good
chmod u+x blinkenlights.com
```
but then
```sh
[alessandro@commodoroII blinkenlights]$ ./blinkenlights.com -?
Cannot open assembly './blinkenlights.com': File does not contain a valid CIL image.
```
Note:
- I have installed `mono`
- I have created the file `/etc/binfmt.d/APE.conf`, containing `:APE:M::MZqFpD::/bin/sh:`, and restarted `systemd-binfmt`
- If I manually launch `blinkelights` I get
```sh
[alessandro@commodoroII blinkenlights]$ sh blinkenlights.com -?
blinkenlights.com: line 13: /tmp/ape-loader: No such file or directory
```
Am I doing something wrong?
Thanks!

**Comment by pkulchenko** [comment]
Seems to be binfmt_misc-related issue. See if #674 or [this](https://github.com/jart/cosmopolitan/issues/356#issuecomment-1043202698) helps.

**Comment by jart** [comment]
Yes it's binfmt_misc. Please disable it by running:

```
sudo sh -c 'echo -1 >/proc/sys/fs/binfmt_misc/status'
```

**Comment by jart** [comment]
Please also note that the release on the website is kind of old at this point. Build from source for the latest experience. We'll try to get another release out sometime soon.

**Comment by bertulli** [comment]
It works! But somehow [compiling from source](https://justine.lol/blinkenlights/sources.html) I get a segfault (even with the test `elf` provided). Is this because the repo exposes the development branch?

**Comment by jart** [comment]
The website is out of date. The sources fork Blinkenlights is here: https://github.com/jart/blink
