### ISSUE TITLE
Reproduce redbean benchmark results

### ISSUE THREAD

**Issue by setop** [jart/cosmopolitan#72]
Hi,

Benchmark section of [redbean documentation](https://justine.lol/redbean/index.html) claim 1Mrps.

I did some benchmark on my laptop (2c 4t i7-7600U 2.80GHz). I manage to have around 130krps with both `redbean` and `wrk` running locally. It is still impressive but yet far from a million.

What platform and which do you use to reach a million rps ?

Here are the results I get, depending on the number of threads (x axis) and the number of connections per thread (y axis).

![heatmap4](https://user-images.githubusercontent.com/7794056/109397139-7fd7aa80-7935-11eb-805f-c408abbfe507.png)

I reach a maximum between 2 and 4 treads and between 4 and 16 connections per thead.

Thanks for this project!

**Comment by jart** [comment]
What platform did you use?

Here's what I did:

```sh
$ wrk -H 'Accept-Encoding: gzip' -t 12 -c 120 \
  http://127.0.0.1:8080/tool/net/redbean.html
Running 10s test @ http://127.0.0.1:8080/tool/net/redbean.html
  12 threads and 120 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency   745.49us    8.79ms 406.77ms   99.54%
    Req/Sec    96.60k     6.10k  123.66k    77.36%
  11631210 requests in 10.10s, 7.96GB read
Requests/sec: 1151621.71
Transfer/sec:    807.23MB
$ uname -a
Linux nightmare 5.4.43-1-lts #2-Alpine SMP Thu, 28 May 2020 20:13:48 UTC x86_64 Linux
$ cat /proc/cpuinfo | grep model\ name | head -n1
model name      : Intel(R) Core(TM) i9-9900 CPU @ 3.10GHz
```

Basically it's an HP ProDesk 600 that cost about a thousand bucks and it runs Linux. The fastest operating systems for Redbean are Linux/FreeBSD and the slowest is Windows. However all should work very reliably.

**Comment by setop** [comment]
I run `Linux dawn 5.6.0-2-amd64 #1 SMP Debian 5.6.14-2 (2020-06-09) x86_64 GNU/Linux`

My [i7-7600U](https://ark.intel.com/content/www/us/en/ark/products/97466/intel-core-i7-7600u-processor-4m-cache-up-to-3-90-ghz.html) is 2 cores (4 threads) at 2.80GHz, 3.9GHz peak

Your [i9-9900](https://ark.intel.com/content/www/us/en/ark/products/191789/intel-core-i9-9900-processor-16m-cache-up-to-5-00-ghz.html) is 8 cores (16 threads) at 3.10GHz, 5.0GHz peak

If we do basic maths : `(8 / 2) * (5 / 3.9) ~= 6.5x` and `129 * 6.5 ~= 840 krps` we are not  far from your result. Probably cache (4MB vs 16MB) and ability to stay at peak plus some background system load can explain the rest...

**Comment by jart** [comment]
Thanks for crunching the numbers. It's good for people to see this kind of information coming from multiple independent sources. Now we know that Redbean on Linux is in a real snappy web server that goes even faster if you get a Core i9. Imagine what it could do with a nice Xeon.
