### ISSUE TITLE
[website] Broken link to mingw-w64-binutils.zip

### ISSUE THREAD

**Issue by kyx0r** [jart/cosmopolitan#730]
Hello this page:
https://justine.lol/cosmopolitan/windows-compiling.html

links to:
https://justine.lol/linux-compiler-on-windows/source-dir-with-objects/mingw-w64-binutils.zip

The url returns 404.

**Comment by jart** [comment]
I'm afraid to say I've lost those two files during a recent server migration, but I managed to find a local copy of the toolchain itself. The links to the huge object zips have been removed from the website.
