### ISSUE TITLE
Redbean can't handled hashed file names

### ISSUE THREAD

**Issue by ccmaris** [jart/cosmopolitan#731]
When you build any frontend sites this days (React, Vue, Svelte, Solid, etc.), the resulting file names are hashed (index-hashhere.html). 

Redbean right now can't handle that, and even if you have a file named about-a1b2c3.html, when you navigate to the /about route you get the Redbean 404.

Is there already a workaround in place?
Or how can I solve that w/o removing the hashes from the filenames?

**Comment by pkulchenko** [comment]
@ccmaris, I can't confirm that and there are several files that have dashes in their names in the redbean demo (you can get the package from the https://redbean.dev/ page to check yourself), so I suspect there may be something else in play. What exactly is your setup? Can you try with no .init.lua file (with redbean.com including all your files) and report the results back?

**Comment by ccmaris** [comment]
That was my mistake.

For future reference, what you want to do is build your site using any static-adapter provided by your frontend framework) **and** make sure to have [trailing slash](https://kit.svelte.dev/docs/page-options#trailingslash) enabled (if provided).
