### ISSUE TITLE
GraphQL Integration

### ISSUE THREAD

**Issue by ccmaris** [jart/cosmopolitan#732]
Are you guys thinking about something like that?

I believe a GraphQL integration would bring redbean miles closer to becoming an easy to use **fullstack server**.

**Comment by pkulchenko** [comment]
@ccmaris, would using something like [this](https://github.com/bjornbytes/graphql-lua) work? You'll need to use [LuLPeg](https://github.com/pygy/LuLPeg), as it has lpeg dependency and it's not available in redbean.

**Comment by ccmaris** [comment]
Thanks for the suggestion.

I'll give it a try and come back to you.

In the meantime, I'll close this issue.
