### ISSUE TITLE
Is `dlopen` expected to be supported eventually?

### ISSUE THREAD

**Issue by viferga** [jart/cosmopolitan#738]
I wanted to know if dlopen support is on the roadmap, and what limitations would it have.

**Comment by jart** [comment]
Right now the roadmap is bringing in support for other hardware architectures like ARM, using the Blink virtual machine https://github.com/jart/blink Adding support for dlopen() is something I want to happen but the project doesn't have the resources to do it right now. Contributions are welcome.
