### ISSUE TITLE
./build/bootstrap/*.com refresh

### ISSUE THREAD

**Issue by ingenieroariel** [jart/cosmopolitan#757]
Last time they were re-created it was 5-7 months ago.

It may be a good idea to refresh them before blink 1.0 and test make.com can build cosmo correctly.

**Comment by mrdomino** [comment]
These apparently mostly haven't been updated since 31dcdefaa83e314238574d42526ba8b64b907392 on Jan 1, but I don't think anything is broken at the moment.
