### ISSUE TITLE
cmake cannot find pthread

### ISSUE THREAD

**Issue by ingenieroariel** [jart/cosmopolitan#759]
If you are using cmake with cosmopolitan you may get an error about threads not being found.

The workaround is:
```
        -DCMAKE_THREAD_LIBS_INIT=/opt/cosmos/lib/libpthread.so
```

**Comment by jart** [comment]
Wouldn't that be libpthread.a which should be created automatically by the cosmocc program? https://github.com/jart/cosmopolitan/blob/master/tool/scripts/cosmocc
