### ISSUE TITLE
Is there possibility to port software using ncurses (e.g. vi) to ape?

### ISSUE THREAD

**Issue by dongdigua** [jart/cosmopolitan#766]
I think it will be good to port some widely-used UNIX tool to ape, such as vi  
I found a repo [awesome-cosmopolitan](https://github.com/shmup/awesome-cosmopolitan)  
seems there's nothing that uses ncurses, but jart's nesemu blinkenlights etc. are terminal application.  

So, ncurses can't work with ape?  
What's the alternative?  

(I'm a noob to C...)

**Comment by jart** [comment]
You don't need ncurses. It's so much easier to just emit the VT100 codes. See .examples and code such as:

- https://github.com/jart/cosmopolitan/blob/master/examples/ttyinfo.c
- https://github.com/jart/cosmopolitan/blob/master/examples/linenoise.c
- https://github.com/jart/cosmopolitan/blob/master/examples/panels.c
- https://github.com/jart/cosmopolitan/blob/master/libc/calls/readansi.c

Here are your ANSI codes:

https://github.com/jart/cosmopolitan/blob/893703a07b1590c02c84a5b02bb4968e4f03522a/tool/build/lib/pty.c#L34-L147

Enjoy Cosmopolitan!

**Comment by stianhoiland** [comment]
Doesn't ncurses have a cell cache to avoid emitting bytes for unchanged cells? Also, I'm not sure the desire here is to use ncurses directly, but that many tools have it as a dependency.
