### ISSUE TITLE
redbean -* error

### ISSUE THREAD

**Issue by johnmuhl** [jart/cosmopolitan#800]
I'm trying to write a file to the zip of the running redbean but it doesn't seem to work. Am I misunderstanding or misusing the feature?

``` sh
./redbean.com -*
>: Barf("help.txt", "test") -- writing outside the zip works
>: Barf("/zip/help.txt", "test")
nil	"open() failed: EINVAL/22/Invalid argument"
```

**Comment by G4Vi** [comment]
`/zip/` is read only right now.  From outside of redbean you can can add and replace files inside of it: `zip -r redbean.com help.txt`

**Comment by pkulchenko** [comment]
`StoreAsset` is the way to do it on those systems that support it.

**Comment by johnmuhl** [comment]
> `StoreAsset` is the way to do it on those systems that support it.

Thanks that's what I was missing. Do you think a note near `-*` pointing to `StoreAsset` would be useful? I see `StoreAsset` refers to `-*` so maybe not that important.

**Comment by johnmuhl** [comment]
Looks like it might have regressed between 2.2 and master. I'll get more information later but if no one minds I'd like to re-open for now.

**Comment by pkulchenko** [comment]
I looked at Barf documentation to see if anything needs to be added *there*, but it does explicitly says "This function writes to the local file system.", so we should be good from that side too.

Yes, please post any details on the regression you found.

**Comment by johnmuhl** [comment]
No regression. I was using an assimilated version of master and the normal 2.2. An assimilated 2.2 doesn't work either. Is that a planned feature for `StoreAsset`?

**Comment by pkulchenko** [comment]
> Is that a planned feature for StoreAsset?

What does "that" refer to hear? `StoreAsset` works for me on Linux (including when called with (-A file) and doesn't work on Windows, as the feature is not supported there. This is all on a day/two old master branch. Is that not the result you see?

**Comment by johnmuhl** [comment]
"that" meant having `StoreAsset` work after running `redbean.com --assimilate` or when using an `m=optlinux` build. Currently I get an `(srvr) can't place write lock on file descriptor 3: EBADF/9/Bad file number` error in those cases.

**Comment by pkulchenko** [comment]
It works for me if -* is specified, but only on the non-assimilated build. It looks like fcntl call fails:

```
SYS  96639      3'276'019'158 fcntl(3, F_SETLKW, {.l_type=F_WRLCK}) → -1 EBADF/9/Bad file number
```

I suspect it fails because the file descriptor is only opened for reading, so F_SETLKW is a "bad" descriptor for that purpose. The reason *why* it's only opened for reading is more difficult to discern, but judging by the strace output, I don't see it going through the logic in openexecutable.S, as it's supposed to open in RDWR mode, which I don't see happening. Maybe @jart knows the reason.

**Comment by bstro** [comment]
I'm running into something similar with my attempts to get a working local TiddlyWiki/redbean working. When my [index.lua](https://github.com/amreus/tiddly-bean/blob/main/index.lua#L25) calls `StoreAsset`, I see the following in the terminal: 
```
I2023-04-10T09:26:20+001915:tool/net/redbean.c:3604:wiki:10606] (srvr) storing asset "wiki.html"
W2023-04-10T09:26:20+031377:tool/net/redbean.c:3631:wiki:10606] (srvr) can't place write lock on file descriptor 3: EBADF/9/Bad file number
```

macOS 11.6.7

**Comment by pkulchenko** [comment]
StoreAsset has been disabled, as it's not in a fully workable state. See this comment in __open_executable, which StoreAsset depends on: https://github.com/jart/cosmopolitan/blob/5c358635249616157b1e02c603ceb852dfc33ef7/libc/runtime/openexecutable.c#L24.
