### ISSUE TITLE
`unveil()` failing when landlock is unimplemented

### ISSUE THREAD

**Issue by notwa** [jart/cosmopolitan#808]
Since commit d5b8b644c27fa7c05618ffb4072b1f35849ba527, unveil may fail unexpectedly. For instance, rebuilding `build/bootstrap/make.com` and then attempting to use within podman it may result in something like this:

```
make.com: /tmp/.ape: unveil() failed EUNKNOWN/0/No error information
make.com: /tmp/.ape: unveil() failed EUNKNOWN/0/No error information
make.com: *** [build/rules.mk:55: o//third_party/unzip/api.o] Error 127
make.com: *** Waiting for unfinished jobs....
make.com: *** [build/rules.mk:55: o//third_party/unzip/apihelp.o] Error 127
```

I scattered some `STRACE`s for debugging and eventually noticed this:
```
SYS      6            323'986 landlock_abi_version → -1 ENOSYS/38/Function not implemented
SYS     13      1'065'657'589 landlock_abi_version → -1
```

The first trace comes from the `__constructor__`. The second comes from this branch: `errno` is no longer set correctly! https://github.com/jart/cosmopolitan/blob/b31ba86ace4fe8605bb0fa06fbfd5b7781ca6f88/libc/calls/unveil.c#L147-L152

So I suppose the value of `errno` needs to be cached somewhere too?

**Comment by meowthink** [comment]
Checkout commit ba49e86

**Comment by notwa** [comment]
Thanks!
