### ISSUE TITLE
Weird error message when running the default hello.com

### ISSUE THREAD

**Issue by Anonymous3-a** [jart/cosmopolitan#809]
I'm running Arch Linux.
I have disabled the `/proc/sys/fs/binfmt_misc/DOSWin` thing that was previously running `hello.com` with wine, but it doesn't work now, giving the error message `Cannot open assembly './hello.com': File does not contain a valid CIL image.` for some reason.  
`uname -a` tells me I am running on x86_64.  
For some reason, running `hello.com.dbg` works, but `hello.com` doesn't.

**Comment by pkulchenko** [comment]
Most likely the same issue as in #719, #674, or #356. Try disabling binfmt_misc by running `sudo sh -c 'echo -1 >/proc/sys/fs/binfmt_misc/status'`.

**Comment by Anonymous3-a** [comment]
Nope, still doesn't. (I already disabled the specific one that was causing the problem)

**Comment by Anonymous3-a** [comment]
I have followed 3 links or so to find someone suggesting I add APE to binfmt_misc, but doesn't that defeat the purpose of a portable executable? (I did it earlier, and it worked though, but it's still technically not portable)

**Comment by Anonymous3-a** [comment]
Nevermind, for some reason I just disabled binfmt_misc *again* and it actually works now? Huh. For any future people that come across this, run ***EXACTLY*** the command `sudo sh -c 'echo -1 >/proc/sys/fs/binfmt_misc/status'`
