### ISSUE TITLE
Redbean - Getting it to work on Win 64

### ISSUE THREAD

**Issue by mercurial-moon** [jart/cosmopolitan#811]
I'm currently win 7 x64
I downloaded Readbean 2.2 for windows from here [Redbean2.2](https://redbean.dev/redbean-2.2.com)
However when running it from command line using 
`redbean2.2.com`
I get this error
![image](https://user-images.githubusercontent.com/117296073/236668848-a6c46674-cb23-4694-b23b-67ce0d6777cb.png)
 Is there any recommended way to get it running on Windows?

**Comment by pkulchenko** [comment]
You can use the [Vista](https://github.com/jart/cosmopolitan/tree/vista) branch to build and run redbean on Windows Vista and Windows 7. The master branch (and the prebuilt binaries) require Windows 8+ to run.
