### ISSUE TITLE
exec format error on mac 10.15.7

### ISSUE THREAD

**Issue by iwater** [jart/cosmopolitan#82]
just compile hello.c on linux, and the output hello.com run on Linux works well
after scp hello.com to local mac and run it, fail with "exec format error: ./hello.com"

but the redbean dl from website works well on mac, so how to compile the correct binary file?

**Comment by alisonatwork** [comment]
After you ran it the first time on Linux, the file overwrites itself to be a Linux-specific version.

You can see which kind of version you have by inspecting the header:

```
$ xxd ./hello.com.original | head -1
00000000: 4d5a 7146 7044 3d27 0a00 0010 00f8 0000  MZqFpD='........
$ xxd ./hello.com.linux | head -1
00000000: 7f45 4c46 0201 0109 0000 0000 0000 0000  .ELF............
```

I guess running on Mac will produce a slightly different header as well.

For scp to other computer, you should send only the original version.

**Comment by Qix-** [comment]
> After you ran it the first time on Linux, the file overwrites itself to be a Linux-specific version.

This is explained somewhere? After looking at the docs a bit, this is the first I've heard of it. It makes sense though.

**Comment by alisonatwork** [comment]
It is described here: https://justine.lol/ape.html

Basically the trick is to have a standard Windows "MZ" header executable that immeditely jumps to some later point in the file on Windows. But on Linux, BSD or Mac, it interprets the `MZqFpD='` as the start of a shell script variable definition, then later on it uses `printf` to print the platform-specific header back to the original file and re-execute itself. Justine said on Hacker News that you can see it a bit like a tiny bundled installer, which is a good way of thinking about it.

I don't understand how the bare metal version works 😅

**Comment by alisonatwork** [comment]
Here is a little script you can use to put the header back:

```
test -f "$1" -a -w "$1" || exit 1
printf "MZqFpD='\n\0\0\x10\0\xf8\0\0\0\0\0\0\0\x01\0\x08@\0\0\0\0\0\0\0\0\0\0\0\x4a\x54\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\
xd8\x0b\0\0" \
| dd of="$1" bs=1 conv=notrunc
```

Example:

```
$ xxd ./hello.com | head -4
00000000: 4d5a 7146 7044 3d27 0a00 0010 00f8 0000  MZqFpD='........
00000010: 0000 0000 0001 0008 4000 0000 0000 0000  ........@.......
00000020: 0000 0000 4a54 0000 0000 0000 0000 0000  ....JT..........
00000030: 0000 0000 0000 0000 0000 0000 d80b 0000  ................
$ ./hello.com
hello world
$ xxd ./hello.com | head -4
00000000: 7f45 4c46 0201 0109 0000 0000 0000 0000  .ELF............
00000010: 0200 3e00 0100 0000 0a11 4000 0000 0000  ..>.......@.....
00000020: c80a 0000 0000 0000 0000 0000 0000 0000  ................
00000030: 0000 0000 4000 3800 0400 0000 0000 0000  ....@.8.........
$ ./restore-header.sh ./hello.com
64+0 records in
64+0 records out
$ xxd ./hello.com | head -4
00000000: 4d5a 7146 7044 3d27 0a00 0010 00f8 0000  MZqFpD='........
00000010: 0000 0000 0001 0008 4000 0000 0000 0000  ........@.......
00000020: 0000 0000 4a54 0000 0000 0000 0000 0000  ....JT..........
00000030: 0000 0000 0000 0000 0000 0000 d80b 0000  ................
$
```

**Comment by Qix-** [comment]
Neat! This is good to know, and makes sense. Thanks for the explanation.

**Comment by jart** [comment]
Thanks for supporting our friend @alisonatwork! Everything she said is accurate. Your APE binaries assimilate themselves as conventional residents of your platform after the first run, so they can be fast and efficient. It's a little bit of a hiccup since it's such a new concept. Please feel free to leave feedback on how we might improve our documentation to explain it better.

**Comment by iwater** [comment]
Great, thank you, that's very helpful

**Comment by niutech** [comment]
Is it possible to skip overwriting the header in APE binaries at build time, e.g. by using `gcc -D` flag?

**Comment by jart** [comment]
I gave it some more thought and I intend to implement a compile flag that changes APE behavior to do a slow copy instead. Please follow #146 for updates.

**Comment by niutech** [comment]
@jart Thank you!

**Comment by jart** [comment]
I've updated the website so you now have a choice between `ape.o` and `ape-no-modify-self.o` which may be downloaded from https://justine.lol/cosmopolitan/download.html Please note, this alternative APE bootloader has its caveats of its own, which are documented by the following comment. Feedback is welcome. Enjoy!

https://github.com/jart/cosmopolitan/blob/da8a08fd58324a87f6ac673b7774512e861fe477/ape/ape.S#L549-L561
