### ISSUE TITLE
Problems with limits.h

### ISSUE THREAD

**Issue by feeley** [jart/cosmopolitan#84]
First of all thank you for cosmopolitan... a very interesting approach to portability and program longevity.  Great hack value!

I've been trying to use cosmopolitan to compile Gambit (http://github.com/gambit/gambit) which is a very portable Scheme to C compiler.  I've encountered a few issues with limits.h .  Gambit uses the definitions in that file to determine at compile time the sizes of the various integer types.

The first problem is that the definitions of `CHAR_MIN`, `CHAR_MAX`, and `UCHAR_MAX` are missing.

Secondly, the C preprocessor doesn't seem to compute some integer expressions the same way as the compiler.  Here's sample code and the output generated (I'm on Ubuntu 19.10 if that matters):

```
printf("((((UINT_MAX >> 8) >> 8) >> 8) >> 8) == %u (when executed)\n",
       (((UINT_MAX >> 8) >> 8) >> 8) >> 8);

#if ((((UINT_MAX >> 8) >> 8) >> 8) >> 8) == 0
printf("%s\n", "((((UINT_MAX >> 8) >> 8) >> 8) >> 8) == 0");
#else
printf("%s\n", "((((UINT_MAX >> 8) >> 8) >> 8) >> 8) != 0");
#endif

#if ((((UINT_MAX >> 8) >> 8) >> 8) >> 8) == 4294967295U
printf("%s\n", "((((UINT_MAX >> 8) >> 8) >> 8) >> 8) == 4294967295U");
#else
printf("%s\n", "((((UINT_MAX >> 8) >> 8) >> 8) >> 8) != 4294967295U");
#endif

/* output:

((((UINT_MAX >> 8) >> 8) >> 8) >> 8) == 0 (when executed)
((((UINT_MAX >> 8) >> 8) >> 8) >> 8) != 0
((((UINT_MAX >> 8) >> 8) >> 8) >> 8) == 4294967295U
*/
```

It seems the C preprocessor thinks that `UINT_MAX` is a 64 bit unsigned long but the compiler thinks it is a 32 bit unsigned long.

**Comment by jart** [comment]
It seems what's happening here is:

> C 2011 (N1570) 6.10.1 4, integer expressions evaluated in the preprocessor use the widest types in the implementation

So basically we can't define `UINT_MAX` as `~0u` because cpp promotes types to long, unlike cc only promotes to int.

**Comment by feeley** [comment]
While it is true that the C preprocessor evaluates with the widest type, it is still possible to define `UINT_MAX` and similar values so that the C preprocessor will have the correct numerical value.  Here's a small shell script that reveals the trick used by the native gcc (this was tested on Ubuntu 19.10)

```
cat <<EOF | gcc -E -P -
#include <limits.h>
INT_MAX
UINT_MAX
EOF

# output:
#
# 0x7fffffff
# (0x7fffffff * 2U + 1U)

cat <<EOF | cosmopolitan/o/third_party/gcc/bin/x86_64-linux-musl-gcc -I cosmopolitan/libc -E -P -
#include <limits.h>
INT_MAX
UINT_MAX
EOF

# output
#
# 0x7fffffff
# (~0U)
```

So the trick is to use the expression `(type_MAX * 2U + 1U)` as the definition of the `Utype_MAX` macro.
