### ISSUE TITLE
Windows: recvfrom() support broken

### ISSUE THREAD

**Issue by jtru** [jart/cosmopolitan#841]
As originally discovered/reported in #839, `recvfrom()` appears broken on Windows hosts, and any code calling it on a UDP socket results in an error like this:

```
C:\Users\QEMU\Downloads>echoserver.com udp server 0 6000
udp server 0.0.0.0 6000
error:examples/echoserver.c:64:echoserver.com: check failed on DESKTOP-2485S1V pid 8860
        CHECK_NE(-1, (rc = recvfrom(sock, buf, sizeof(buf), 0, (struct sockaddr *)&addr2, &addrsize2)));
                 → -1 (-1)
                != -1 ((rc = recvfrom(sock, buf, sizeof(buf), 0, (struct sockaddr *)&addr2, &addrsize2)))
        EFAULT/487/Bad address/10014/The system detected an invalid pointer address in attempting to use a pointer argument in a call
        echoserver.com udp server 0 6000
note: won't print addr2line backtrace because no debug binary
70000003fe90 4048c5 NULL+0
70000003ff50 40456d NULL+0
70000003ffa0 403a4b NULL+0
70000003ffd0 403cb1 NULL+0
70000003ffe0 44e5ae NULL+0
```

Furthermore, I think the [`recvfrom()` API/spec](https://justine.lol/cosmopolitan/documentation.html#recvfrom) should explicitly support and document having both `struct sa* opt_out_srcaddr` and `unsigned int* opt_inout_srcaddrsize ` assume `NULL`, since `recvfrom(3p)` does that, too:

```man
[...]

SYNOPSIS
       #include <sys/socket.h>

       ssize_t recvfrom(int socket, void *restrict buffer, size_t length,
           int flags, struct sockaddr *restrict address,
           socklen_t *restrict address_len);

DESCRIPTION
[...]
       address     A  null  pointer,  or points to a sockaddr structure in which the sending address is to be stored.
                   The length and format of the address depend on the address family of the socket.

       address_len Either a null pointer, if address is a null pointer, or a pointer to a socklen_t object  which  on
                   input  specifies the length of the supplied sockaddr structure, and on output specifies the length
                   of the stored address.
[...]
```

**Comment by pkulchenko** [comment]
@jtru, just to confirm, based on the discussion in #839, using `recv` instead of `recvfrom` works for you: "Switching to recv() instead of recvfrom() makes the application behave as I would expect it to even under Windows (11 for x86_64, as this is the only OS/machine I have right now that can properly use multicast in my LAN at this time)".

**Comment by pkulchenko** [comment]
> Furthermore, I think the [recvfrom() API/spec](https://justine.lol/cosmopolitan/documentation.html#recvfrom) should explicitly support and document having both struct sa* opt_out_srcaddr and unsigned int* opt_inout_srcaddrsize assume NULL, since recvfrom(3p) does that, too:

I think this is a reasonable suggestion, but I don't see anywhere that [WSARecvFrom](https://learn.microsoft.com/en-us/windows/win32/api/winsock2/nf-winsock2-wsarecvfrom) (which is used on Windows to implement `recvfrom`) allows those values to be NULL. Am I missing it in the description?

**Comment by pkulchenko** [comment]
@jtru, is it possible that access to the port is blocked by something local (as described [here](https://www.codeproject.com/Questions/434187/C-socket-error-10014))? I realize that the port is different and it's not likely, but just want to exclude some of the scenarios.

**Comment by jtru** [comment]
> @jtru, just to confirm, based on the discussion in #839, using `recv` instead of `recvfrom` works for you: "Switching to recv() instead of recvfrom() makes the application behave as I would expect it to even under Windows (11 for x86_64, as this is the only OS/machine I have right now that can properly use multicast in my LAN at this time)".

Yes, that is the case. Using `recv()` (with fewer arguments) instead of `recvfrom()` in the same place makes the application work correctly.



> @jtru, is it possible that access to the port is blocked by something local (as described [here](https://www.codeproject.com/Questions/434187/C-socket-error-10014))? I realize that the port is different and it's not likely, but just want to exclude some of the scenarios.

When I first start the application, Windows' firewall prompt pops up and asks me whether I would like to allow it "accessing the network" (or some such question to similar effect). Behavior (= the crash) of the application does not change before or after I have put it on the allowlist using that prompt, so I don't think that's a relevant difference.

**Comment by pkulchenko** [comment]
@jtru, submitted a patch in #844.
