### ISSUE TITLE
M1 Ventura 13.4.1 zsh bus error

### ISSUE THREAD

**Issue by xet7** [jart/cosmopolitan#847]
Hi,
Darkest Hour is halloween text adventure made with C89.
https://github.com/xet7/darkesthour

I added only this one line to source code for Cosmopolitan support:
```
#include <cosmo.h>
```
- https://github.com/xet7/darkesthour/blob/main/Source/darkest-hour-cosmo.c#L41

All various changes related to added Cosmopolitan to build scripts, readme etc:
- https://github.com/xet7/darkesthour/commit/3f4e475162a20b3b5ce11ddcd74db2a05b34dd91

Here is binary. It work on Linux and Windows, but not at M1.
- https://github.com/xet7/darkesthour/tree/main/Original/Cosmopolitan

I built it like this at Ubuntu 23.04 64bit:
```
cosmocc -o build/Cosmopolitan/darkest-hour-cosmo.com darkest-hour-cosmo.c
```
https://github.com/xet7/darkesthour/blob/main/Source/menu.sh#L127-L135

I installed Rosetta to M1 Ventura 13.4.1 and rebooted:
```
softwareupdate --install-rosetta --agree-to-license
```
But I get this error at M1:
```
$ arch -x86_64 ./darkest-hour-cosmo.com
zsh: bus error  arch -x86_64 ./darkest-hour-cosmo.com
```

**Comment by michaellenaghan** [comment]
I don't have an M1 Mac, but I did see this in the [README](https://github.com/jart/cosmopolitan#arm):

> The second catch is that MacOS needs a little bit of help understanding the ELF format. To solve that, we provide a tiny APE loader you can use on M1 machines.

I understand that you're actually trying to run `x86_64` on your M1 via Rosetta, but maybe native `arm` will work?

Another thought: assimilate the build. There's a pre-built `assimilate.com` executable on the [Redbean](https://redbean.dev/#tools) page.

I don't know, of course, if any of this will help…

**Comment by michaellenaghan** [comment]
For what it's worth, I was able to use the [README](https://github.com/jart/cosmopolitan#arm) instructions to cross-compile `redbean.com` for `aarch64` on an `x86_64` machine, and then execute it on an M1 using `ape`.

Aside from that, #429 describes a patch that was made a year ago to support running x86 executables on M1 Macs using Rosetta. One difference, maybe, compared to what you tried: they assimilated their executables. (I don't have access to the M1 anymore, so I can't try that myself.)

**Comment by xet7** [comment]
@michaellenaghan 

After assimilate, redbean does run on M1.

I'll try those various compile options.

**Comment by xet7** [comment]
that sixOS example does run on Linux arm64. It also runs on Win11 arm64, because Win11 arm64 can also run Win11 amd64 executeables.

<img width="1273" alt="sixos" src="https://github.com/jart/cosmopolitan/assets/15545/f2c9abba-218d-4cad-887f-eb9e814e1af7">

![sixos2](https://github.com/jart/cosmopolitan/assets/15545/1d6ae5b8-2429-4ab4-bee9-123396f19a56)

**Comment by michaellenaghan** [comment]
I spun up a brand new Mac instance on AWS. These were the steps to get `redbean-demo-2.2.com` running:

* Open Terminal
* `softwareupdate --install-rosetta --agree-to-license`
* `curl "https://redbean.dev/redbean-demo-2.2.com" -o redbean-demo-2.2.com`
* `chmod +x redbean-demo-2.2.com`
* `./redbean-demo-2.2.com`

That was it; no `--assimilate` step. (Though, of course, it still works if you do that.) 

Excellent.

Not sure why it didn't work for you immediately. (I'm only a few days into learning about redbean. I don't even know what I don't know. :-)

**Comment by xet7** [comment]
@michaellenaghan 

I'll try newest redbean.

**Comment by xet7** [comment]
@michaellenaghan 

Redbean 2.2 does not work on M1 without assimilate.

```
 % ./redbean-2.2.com 
./redbean-2.2.com: line 7: /usr/local/bin/ape: cannot execute binary file
./redbean-2.2.com: line 7: /usr/local/bin/ape: Undefined error: 0

% ./redbean-2.2.com --assimilate
% ./redbean-2.2.com             
I2023-07-24T13:26:47.463510:tool/net/redbean.c:7057:redbean-2:5638] (srvr) listen http://127.0.0.1:8080
```

**Comment by xet7** [comment]
After removing broken ape, redbean does run.

I'll try to figure out how to get my C code built correctly.

**Comment by michaellenaghan** [comment]
> After removing broken ape, redbean does run.

Do you mean "without assimilate", or something else?

And was the broken `ape` installed by a previous run, or something else? Maybe `apeinstall.sh`?

> I'll try to figure out how to get my C code built correctly.

I'm interested in hearing how it goes!

**Comment by xet7** [comment]
@michaellenaghan 

> > After removing broken ape, redbean does run.
> 
> Do you mean "without assimilate", or something else?

Yes.

**Comment by xet7** [comment]
I can build my C code to version that runs on M1, but not on Linux aarch64, I don't know where is that apelink at https://github.com/jart/cosmopolitan/issues/847#issuecomment-1648393327

**Comment by michaellenaghan** [comment]
I don't know if we're talking about the same thing, but according to the README you only have to prefix `ape` (e.g., `ape ./redbean.com`) on macOS. I think that an aarch64 build is supposed to "just work" on Linux aarch64?

Also, just in case (given that it isn't obvious): the `./` in `ape ./redbean.com` is required. `ape` does a search, and `.` isn't included in the search by default.

**Comment by xet7** [comment]
@michaellenaghan 

What does this mean on Linux arm64 ?

```
$ ./darkest-hour.com 
./darkest-hour.com: line 55: /home/wekan/.ape-blink-1.0.0: Success
```

**Comment by michaellenaghan** [comment]
`blink` is the "blink virtual machine" described [here](https://github.com/jart/cosmopolitan/tree/e0c2b91b3ec6f88d060d6059210a993a0ef46b08#arm). According to that description, `blink` is what's used to build executables that run on both `aarch64` and `x86_64` — by JITing `aarch64` to `x86_64`.

If you want native `aarch64`, you have to say that (and then, I think, you get *only* that):

    make m=aarch64 …

Are you doing that, or something else? (And, again, just to be clear: I'm new around here!)

P.S.  The output you're seeing seems to be coming from [here](https://github.com/jart/cosmopolitan/blob/e0c2b91b3ec6f88d060d6059210a993a0ef46b08/ape/ape.S#L716); there are some interesting comments:

https://github.com/jart/cosmopolitan/blob/e0c2b91b3ec6f88d060d6059210a993a0ef46b08/ape/ape.S#L711-L714

I'm not sure they actually help, but at least they give you a sense of what's going on.

**Comment by xet7** [comment]
Redbean nightly works at M1 and Linux arm64.
