### ISSUE TITLE
Document support vector

### ISSUE THREAD

**Issue by rubyFeedback** [jart/cosmopolitan#87]
I found the project indirectly via reddit, where someone made lua work via cosmopolitan on both linux
and windows. This was interesting, so I wondered whether python and ruby (mruby) may already work
too.

Would it be possible to perhaps extend the main README with software projects that currently work?
I understand this is all far away from a stable release but it would be interesting to see every some weeks
or months how things progress. Also it adds a bit competition now that it has been shown that lua does
work via cosmopolitan too, so the other "scripting" languages may have some catching up to do - but
mostly I am interesting in like a markdown table or something, noteworthy projects using cosmopolitan
and such. Thanks for reading, please feel free to close this issue at any moment in time.

**Comment by jart** [comment]
We can't make promises about which software supports Cosmopolitan. What we can promise is what hardware and software Cosmopolitan supports. Right now that's:

| Platform | Min Version | Circa |
| :--- | ---: | ---: |
| AMD | K8 Venus | 2005 |
| Intel | Core | 2006 |
| New Technology | Vista | 2006 |
| GNU/Systemd | 2.6.18 | 2007 |
| XNU's Not UNIX! | 15.6 | 2018 |
| FreeBSD | 12 | 2018 |
| OpenBSD | 6.4 | 2018 |
| NetBSD | 9.1 | 2020 |

**Comment by zzo38** [comment]
Can it be used on GNU/Linux systems that do not have systemd?

**Comment by jart** [comment]
Cosmopolitan can be run on any Linux system. Systemd is not a requirement.

**Comment by zzo38** [comment]
Then you should fix it, because the current list is confusing.

**Comment by jonahharris** [comment]
How is it confusing? Where is the confusion?

**Comment by jart** [comment]
As you wish. https://github.com/jart/cosmopolitan/commit/92cb144fff67c0a4879577278ba56121944d92d6

**Comment by Cons-Cat** [comment]
I was confused by this on the page [howfat](https://justine.lol/cosmopolitan/howfat.html) as well.
