### ISSUE TITLE
Fish shell can't launch APE binaries

### ISSUE THREAD

**Issue by kazimuth** [jart/cosmopolitan#88]
running an example in the fish shell fails, but it works in bash. Then, after running in bash, it works in fish shell as well:

```
radical@phenocryst ~/d/cosmopolitan (master)> make
♥cosmo
make: Nothing to be done for 'all'.
radical@phenocryst ~/d/cosmopolitan (master)> o//examples/hello.com
Failed to execute process 'o//examples/hello.com'. Reason:
exec: Exec format error
The file 'o//examples/hello.com' is marked as an executable but could not be run by the operating system.
radical@phenocryst ~/d/cosmopolitan (master) [125]> bash
radical@phenocryst:~/dev/cosmopolitan> o//examples/hello.com # now in bash
hello world
radical@phenocryst:~/dev/cosmopolitan> o//examples/hello.com
hello world
radical@phenocryst:~/dev/cosmopolitan> exit # back to fish
radical@phenocryst ~/d/cosmopolitan (master)> o//examples/hello.com
hello world
radical@phenocryst ~/d/cosmopolitan (master)> # now it works??
```

i suspect this is due to fish not respecting whatever shell trickery you're using for the cross-platform ABI chicanery.

OS / Version notes:
1. the "Tumbleweed" distro is rolling, i am... about 4.5Gb out of date. Doing a dist-upgrade now to double-check the issue still occurs.
2. cosmopolitan: commit `3c24c120` from this repo.
3. shell versions:
```
Information for package fish:
-----------------------------
Repository     : openSUSE:Tumbleweed
Name           : fish
Version        : 3.1.2-3.1
Arch           : x86_64
Vendor         : openSUSE

Information for package bash:
-----------------------------
Repository     : openSUSE:Tumbleweed
Name           : bash
Version        : 5.1.4-1.2
Arch           : x86_64
Vendor         : openSUSE
```

(this is a super neat project btw, big fan :)

**Comment by jart** [comment]
Thank you for reporting this. As discussed on Lobsters earlier, I intend to upstream a patch with the Fish shell that'll restore its support for sixth edition shell scripts, since that's required by POSIX. I recently upstreamed a similar patch with Zsh. https://github.com/zsh-users/zsh/commit/326d9c203b3980c0f841bc62b06e37134c6e51ea

**Comment by kazimuth** [comment]
huh, so it's actually a POSIX compatibility issue on their end, cool. Thanks!

**Comment by jart** [comment]
Fish now supports Actually Portable Executables! https://github.com/fish-shell/fish-shell/commit/0048730a67a5e70cafce1fb725a4b28001d924ac. If you're a Fish user then be sure to thank the Fish developer team for changing their policies to enable this!

**Comment by mika76** [comment]
Any news on the zsh patch?

**Comment by gizlu** [comment]
> Thank you for reporting this. As discussed on Lobsters earlier, I intend to upstream a patch with the Fish shell that'll restore its support for sixth edition shell scripts, since that's required by POSIX. I recently upstreamed a similar patch with Zsh. [zsh-users/zsh@326d9c2](https://github.com/zsh-users/zsh/commit/326d9c203b3980c0f841bc62b06e37134c6e51ea)

It seems that zsh patch didn't fix issue. Tested on [awk-2022-08-22.com](https://justine.lol/awk/awk-2022-08-22.com) and [zsh 5.9 builded from source](https://github.com/zsh-users/zsh/releases/tag/zsh-5.9)
![image](https://user-images.githubusercontent.com/46008403/188154214-38dad90d-c54a-415f-bd31-2ec772ccb42e.png)
