### ISSUE TITLE
APE binary giving virus alert 

### ISSUE THREAD

**Issue by umairsiddiqui-digitek** [jart/cosmopolitan#90]
hi, 

i downloaded the `hello.com` from @jart [blog](https://storage.googleapis.com/justine/ape.html) 

```
8bdc483f9da32830f7ff0dec1fbd2d16066438af *hello.com
```
tried to run on windows. the Avast anti virus give virus alert.

![ape_hello](https://user-images.githubusercontent.com/41374313/109481836-183d6e80-7a9f-11eb-988c-df35259cfd02.PNG)

it is a false alarm, but it kind of limit the usefulness of portable executable. I got this problem with [other APE binaries as well](https://storage.googleapis.com/justine/printimage.html) 

regards

**Comment by jart** [comment]
Here's what's likely happening. I've been experiencing a lot of online harassment over the last two days, over things I can't change like my gender. It's most likely that those individuals have been filing false reports with antivirus companies about the executables I've distributed. For more context see the [talk page of my wikipedia profile](https://en.wikipedia.org/wiki/Talk:Justine_Tunney#Personal_Life) since the people who've been harassing me have edited that too and I go into more detail about what happened on Hacker News.

Here's how we're going to solve the antivirus issue. I'm going to publish a PGP key and digitally sign all the executables I've distributed so far, to attest to their authenticity. Then we're all going to join VirusTotal and click the check mark to let the antivirus algorithms know they're OK.

I'll keep this thread updated in real time as we organize our supporters.

**Comment by jart** [comment]
OK my username on VirusTotal is [howishexeasier](https://www.virustotal.com/gui/user/howishexeasier). I just went through my binary release history and upvoted them all. So you can use this website to check if a binary came from me. That's going to continue to be the case going forward. Here is the list of release binaries so you can upvote them too:

- [virustotal/af3afff7b7462968db5aac57864f587b91d76d471071aa091eeb40fda6411893](https://www.virustotal.com/gui/file/af3afff7b7462968db5aac57864f587b91d76d471071aa091eeb40fda6411893/detection)
- [virustotal/62fa6037d9b83a465b0c2e78688783632344ac10882f0d75eed8f66c5e690066](https://www.virustotal.com/gui/file/62fa6037d9b83a465b0c2e78688783632344ac10882f0d75eed8f66c5e690066/detection)
- [virustotal/62c49db21f9740523c890faac972e146cacf97aa13c7d34cd2efe1ee721701ac](https://www.virustotal.com/gui/file/62c49db21f9740523c890faac972e146cacf97aa13c7d34cd2efe1ee721701ac/detection)
- [virustotal/3a8d18a1ffa08620d30ce4d484302fc3b183da208390d888065bf9585b8b024c](https://www.virustotal.com/gui/file/3a8d18a1ffa08620d30ce4d484302fc3b183da208390d888065bf9585b8b024c/detection)
- [virustotal/30360e3177165e813bfeb3c9e26db418515ef2b07e64acd875e7768f8d48bfc5](https://www.virustotal.com/gui/file/30360e3177165e813bfeb3c9e26db418515ef2b07e64acd875e7768f8d48bfc5/detection)
- [virustotal/ca6d01434f6a3a1c9fc373771385cff2d761ef26198bbd7fad1f81ca1589eaaa](https://www.virustotal.com/gui/file/ca6d01434f6a3a1c9fc373771385cff2d761ef26198bbd7fad1f81ca1589eaaa/detection)
- [virustotal/c11aac2c62adbc0f30ac732b063e0bfacce0885666ac8936038cf5857777eab9](https://www.virustotal.com/gui/file/c11aac2c62adbc0f30ac732b063e0bfacce0885666ac8936038cf5857777eab9/detection)
- [virustotal/0e837ab4fad653fb9162228ac2e59a1f14e7079641588c004c7e18b2d7405261](https://www.virustotal.com/gui/file/0e837ab4fad653fb9162228ac2e59a1f14e7079641588c004c7e18b2d7405261/detection)
- [virustotal/1bb4123c2329acb7983e616e7e253b27d4f166e40bef10934dba92938ac0e6a1](https://www.virustotal.com/gui/file/1bb4123c2329acb7983e616e7e253b27d4f166e40bef10934dba92938ac0e6a1/detection)
- [virustotal/0c4ab5de1e267d2352b6d59bea0ffa0c7b293310970b5fc4dcfe918b856e59eb](https://www.virustotal.com/gui/file/0c4ab5de1e267d2352b6d59bea0ffa0c7b293310970b5fc4dcfe918b856e59eb/detection)
- [virustotal/4c41593697f1f73ab81cd4d9d5efce04302ec3f809ab49ac44c2ab26e3c0bd64](https://www.virustotal.com/gui/file/4c41593697f1f73ab81cd4d9d5efce04302ec3f809ab49ac44c2ab26e3c0bd64/detection)
- [virustotal/22858b21cbd94abe1d7b16d0776bb027c2cb046d028b0ee8a1fe9a73bfeba778](https://www.virustotal.com/gui/file/22858b21cbd94abe1d7b16d0776bb027c2cb046d028b0ee8a1fe9a73bfeba778/detection)
- [virustotal/3220d4afdfa3a509f8dad1573812b62c304fe8b9bcaf0dee22c2b5831c6f3ddd](https://www.virustotal.com/gui/file/3220d4afdfa3a509f8dad1573812b62c304fe8b9bcaf0dee22c2b5831c6f3ddd/detection)
- [virustotal/d36f960d2ae4df6bd3eff5fe7d3ffdd40eac9cfe95e7f492f77e7c9c2379c1ab](https://www.virustotal.com/gui/file/d36f960d2ae4df6bd3eff5fe7d3ffdd40eac9cfe95e7f492f77e7c9c2379c1ab/detection)
- [virustotal/414cd3207174111d6dcb163eff417b25525eb238d47309877bd843a781ad7cc1](https://www.virustotal.com/gui/file/414cd3207174111d6dcb163eff417b25525eb238d47309877bd843a781ad7cc1/detection)
- [virustotal/536bce06907ef45b4ace5e24886ec68ad1efb8ed2cdeef0d89f2b9d30e83a794](https://www.virustotal.com/gui/file/536bce06907ef45b4ace5e24886ec68ad1efb8ed2cdeef0d89f2b9d30e83a794/detection)
- [virustotal/120327a5591627a565b2d407dcfe97093a0ed9fec9fd2f8c8f5d0a36cd8956db](https://www.virustotal.com/gui/file/120327a5591627a565b2d407dcfe97093a0ed9fec9fd2f8c8f5d0a36cd8956db/detection)
- [virustotal/bb70835d1bd6a25c56379fe0e90c9f9b124634b937e8b371eb80c670ad015266](https://www.virustotal.com/gui/file/bb70835d1bd6a25c56379fe0e90c9f9b124634b937e8b371eb80c670ad015266/detection)
- [virustotal/b637d7435a2fbf8dbfb220081daf89781d03980d11592d57cccc49d4588d3009](https://www.virustotal.com/gui/file/b637d7435a2fbf8dbfb220081daf89781d03980d11592d57cccc49d4588d3009/detection)
- [virustotal/0699e24f8d87807acbeea7551af7117af85c3ce4c94a2a51fbc9c0c836a904d9](https://www.virustotal.com/gui/file/0699e24f8d87807acbeea7551af7117af85c3ce4c94a2a51fbc9c0c836a904d9/detection)
- [virustotal/85a59414695a1a927e7fb2ed1964db3594f70dbab663196ed491738c965efc69](https://www.virustotal.com/gui/file/85a59414695a1a927e7fb2ed1964db3594f70dbab663196ed491738c965efc69/detection)
- [virustotal/bf4cc81af151416e3d36603cc640b0c7b6c4e8e45d7bdb5491a226151822266c](https://www.virustotal.com/gui/file/bf4cc81af151416e3d36603cc640b0c7b6c4e8e45d7bdb5491a226151822266c/detection)
- [virustotal/8f78b43a1fd8f048ca843e863e6d927f3357aa86519359ca73c4d866167d7e0f](https://www.virustotal.com/gui/file/8f78b43a1fd8f048ca843e863e6d927f3357aa86519359ca73c4d866167d7e0f/detection)
- [virustotal/a946864654f6ed04f3a5c4aff7c3a25411ad1c0a013eff5bfc32076a246761c4](https://www.virustotal.com/gui/file/a946864654f6ed04f3a5c4aff7c3a25411ad1c0a013eff5bfc32076a246761c4/detection)
- [virustotal/909550b511d514fdc457fe369047e1efb603cd0354c3cf6d9ce3d0781213838a](https://www.virustotal.com/gui/file/909550b511d514fdc457fe369047e1efb603cd0354c3cf6d9ce3d0781213838a/detection)
- [virustotal/a946864654f6ed04f3a5c4aff7c3a25411ad1c0a013eff5bfc32076a246761c4](https://www.virustotal.com/gui/file/a946864654f6ed04f3a5c4aff7c3a25411ad1c0a013eff5bfc32076a246761c4/detection)
- [virustotal/fdf3ca28f07d3308dcb2a35cd20781439a1a4d539727c8bdd016835e76bdb925](https://www.virustotal.com/gui/file/fdf3ca28f07d3308dcb2a35cd20781439a1a4d539727c8bdd016835e76bdb925/detection)
- [virustotal/d5231b8b27b59c240268eaf916ddaff22fe65655fee8059aff801f4aba37daa5](https://www.virustotal.com/gui/file/d5231b8b27b59c240268eaf916ddaff22fe65655fee8059aff801f4aba37daa5/detection)
- [virustotal/1e86413f9f10286703d6ac93c5751e55869b6637f213c7d5a811ff89fee8aa04](https://www.virustotal.com/gui/file/1e86413f9f10286703d6ac93c5751e55869b6637f213c7d5a811ff89fee8aa04/detection)
- [virustotal/0897a3df5979466fc98312eb1cc1383f2ea053e122e7ac433754d89f6021a34a](https://www.virustotal.com/gui/file/0897a3df5979466fc98312eb1cc1383f2ea053e122e7ac433754d89f6021a34a/detection)
- [virustotal/bfeeeccd6238b9bfe86a5d434e9048bd8748534af47f0c38cd15e8ee0cf2b10a](https://www.virustotal.com/gui/file/bfeeeccd6238b9bfe86a5d434e9048bd8748534af47f0c38cd15e8ee0cf2b10a/detection)
- [virustotal/57432144ef2cf0a98d353d72e345438465848e4429accaa176afe70c81960952](https://www.virustotal.com/gui/file/57432144ef2cf0a98d353d72e345438465848e4429accaa176afe70c81960952/detection)
- [virustotal/7b499bf4408b38cb5ebc5dd92737f03ec9b1affcad0555da2de47a29d05eb873](https://www.virustotal.com/gui/file/7b499bf4408b38cb5ebc5dd92737f03ec9b1affcad0555da2de47a29d05eb873/detection)
- [virustotal/8f55953c75e9c4d3f8affb28718b72afda47ac809f7adbbcba1d7b266fedeb2b](https://www.virustotal.com/gui/file/8f55953c75e9c4d3f8affb28718b72afda47ac809f7adbbcba1d7b266fedeb2b/detection)
- [virustotal/058c5cd420825a50f6fe002a2c0c199e7f5bc60c88e68c6dc6283ea6ae59aa54](https://www.virustotal.com/gui/file/058c5cd420825a50f6fe002a2c0c199e7f5bc60c88e68c6dc6283ea6ae59aa54/detection)


Please note that if you edit the ZIP contents in RedBean then the checksum changes and it no longer is tied to me. The same applies to any programs you build with Cosmopolitan Libc. You are responsible for distributing them responsibly. I recommend you do that by using the VirusTotal service. It's what's going to protect us from the bad guys.

**Comment by jart** [comment]
It seems Chrome safebrowsing is impacted. This is going to be more difficult than I thought.

**Comment by jart** [comment]
We're now impacted by Windows Defender.

**Comment by Skywalker13** [comment]
Anti-Virus (and Avast is one of the worse), even for signed software is an endless battle. IMO, you should not spend too much time of that.

**Comment by jart** [comment]
Normally there's an incredible culture of trust in open source, which is great, provided we can get the open source code to actually compile. Fixing binary distribution for foss developers is going to solve that. However it runs the risk of attracting people with bad intentions. So while scanners are full of false positives, they're not something we should ignore.

VirusTotal makes fighting that battle easy. It only took me two seconds to drag and drop and click the checkmark for the latest Redbean release binary: [virustotal/2bb60052e0e2ec27c5e5733360862d07cd9a4396c6e865ce56a5c0b956211937](https://www.virustotal.com/gui/file/2bb60052e0e2ec27c5e5733360862d07cd9a4396c6e865ce56a5c0b956211937/detection). 

It also looks like we're back in the good graces of SafeBrowsing and Windows Defender too.

Code signing is something that would be nice in the future. Automation for checksum registration too. The reason why we don't have it already is because each APE binary has three valid forms: PE, ELF, and Mach-O. The current infrastructure for offering binary security isn't equipped to handle the idea that a program can have a many to one mapping of known sha256sums.
