### ISSUE TITLE
Issue with hello world on Windows 8

### ISSUE THREAD

**Issue by novicearts** [jart/cosmopolitan#906]
Hello there,

I recently installed cosmocc on my linux machine. It works almost perfectly! I tested it out with the hello world example in the readme, which worked on my mac OSX and Ubuntu machines exactly.

My Windows 8 machine almost works, but it has a problem.

On Unix, if I run `./hello.com`, I just get:
```
$> ./hello.com
hello world!
$>
```

But on Windows 8 I get:
```
$>hello.com
hello world!
hello world!
hello world!
hello world!
hello world!
hello world!
hello world!
...
```

And it goes on in an infinite loop.

Not sure why this is happening.

Steps to reproduce:
1. Install cosmocc per the readme.
2. Create hello.c based on existing hello world example, and compile hello.com accordingly
3. Run on Windows

I installed cosmocc on Ubuntu 22.04 LTS in case that's important.

**Comment by novicearts** [comment]
Update:
I did some further investigation and realized I was running into an issue with my terminal of choice.

If I run the program from command prompt (or cmd.exe specifically), there are no issues. If I run it from Cmder, that's when the infinite loop happens.

I'll close the issue but hopefully this serves as useful reference for anyone else running into this on windows.

**Comment by liudonghua123** [comment]
It seems I can only build from linux, then run on linux, windows and macos.

```
[root@localhost tmp]# export PATH=/opt/cosmocc/bin/:$PATH
[root@localhost tmp]# cosmocc -o hello hello.c
[root@localhost tmp]# ./hello
hello world
[root@localhost tmp]# file hello
hello: DOS/MBR boot sector; partition 1 : ID=0x7f, active, start-CHS (0x0,0,1), end-CHS (0x3ff,255,63), startsector 0, 4294967295 sectors
[root@localhost tmp]# ./hello
hello world
[root@localhost tmp]# 
[root@localhost tmp]# file hello-gcc
hello-gcc: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, BuildID[sha1]=4038f62f46a93447dcc3f95bbb98b7342f25ef85, for GNU/Linux 3.2.0, not stripped
[root@localhost tmp]# 

```

On cmd of window:

![image](https://github.com/jart/cosmopolitan/assets/2276718/dbcd8d28-38ce-4994-8193-e84b1d675904)

**Comment by jart** [comment]
I'm able to use cosmocc just fine on Windows thanks to cosmos bash. https://justine.lol/cosmo3/
