### ISSUE TITLE
How to compile for Windows 32 bit

### ISSUE THREAD

**Issue by novicearts** [jart/cosmopolitan#907]
Hello,

I am able to compile executables for 64 bit machines, but if I try to test on Windows XP, the format is incompatible. I wanted to ask if cosmocc supports 32-bit executables, or if that's out of scope

**Comment by jart** [comment]
Cosmopolitan only supports 64-bit platforms. If you want to run your Cosmo binaries on 32-bit platforms, you might consider trying [Blink](https://github.com/jart/blink) on Cygwin. If you do that, you're on your own. This project can't help you if you're using end-of-life Windows environments.
