### ISSUE TITLE
Unsupported 16-Bit application error for most examples and redbean

### ISSUE THREAD

**Issue by vladkosarev** [jart/cosmopolitan#92]
First of all, thank you for this project! If this does end up working then I can finally have cross-platform or 'no-platform' Forth :)

The issue is that I get Unsupported 16-bit Application error on most things. I am using wsl2 to compile cosmopolitan. Here's the error image -

![image](https://user-images.githubusercontent.com/1223487/109520091-da7a1f00-7a79-11eb-8f76-9779d37182ad.png)

At first cosmopolitan didn't compile at all (make -j8 -O) because sanitycheck2 would throw that 16bit error in wsl2 and crash build. That issue was solved with binfmt_misc trick.

Once I had cosmo building I was able to run all of the examples in wsl2. I also downloaded redbean and that ran just fine in wsl2 linux.

In windows 10 though most (!) things do throw that 16bit error. Redbean does the same. What's interesting is that hello.com will throw but hello4.com works fine.

Any ideas on how to fix this or if I'm doing something wrong with compilation?

Thank you!

**Comment by ahgamut** [comment]
This happened to me as well. Compiled on Linux, runs on linux, and then same executable fails on Windows.
The fix is: compile and run the resulting file on Windows *first* (without trying on Linux). Now `hello.com` will work on Windows.

If I understand correctly, the executable modifies itself when run the first time.
So after running `hello.com` on Linux once, it will have modified itself and thus will not work on Windows.

**Comment by jart** [comment]
It's possible that this might be related to https://github.com/jart/cosmopolitan/issues/90

**Comment by vladkosarev** [comment]
@ahgamut you are correct! I did not realize that executable modifies itself on the first run. I recompiled everything and ran it on windows first. In that scenario I was able to execute hello on both windows and then on wsl2 linux afterwards. We can close this if this is a known limitation (you can't send an executable to a windows box once you ran it on linux).

Thank you.

**Comment by jart** [comment]
Thanks @ahgamut for helping our friend. See also #82.
