### ISSUE TITLE
Cosmocc won't update on first run

### ISSUE THREAD

**Issue by kapstok** [jart/cosmopolitan#927]
Hello!

I tried to install cosmopolitian using the instructions in the [README.md](https://github.com/jart/cosmopolitan/blob/aa106c9356114b0dbb95db20e79f00ba48987adc/README.md).

At least two commands won't run:

```bash
$ ape-install
Actually Portable Executable (APE) Installer
Author:  Justine Tunney <jtunney@gmail.com>
using ape loader you compiled earlier

installing o//ape/ape.elf to /usr/bin/ape
sudo mv -f o//ape/ape.elf /usr/bin/ape
cp: /usr/bin/ape: Operation not permitted

$ cosmocc --update
building cosmo host toolchain...
Makefile:81: *** please use build/bootstrap/make.com.  Stop.
```

I am running this on a Macbook (Apple silicon). I presume that the fact that the first command won't isn't much of an issue. However, the second command should run. Could anyone help me out with this?
Many thanks in advance!

**Comment by h4sh5** [comment]
I am having the same problem. 

```
cp: /usr/bin/ape: Operation not permitted
```

that can be solved by manually copying `o//ape/ape.macho` (which is the mac version of ape) to /usr/local/bin/ape instead of /usr/bin/ape, because `/usr/bin/` might be protected by SIP and not writable even by root.

**Comment by h4sh5** [comment]
that should put `ape` on your path, then if you re-run `build/bootstrap/make.com` it will hopefully work. It does take a while..

**Comment by xorgol** [comment]
I have copied ape.macho to usr/local/bin/ape, and I have also attempted to modify the apeinstall.sh script by replacing every instance of /usr/bin/ape with /usr/local/bin/ape, and that completes the install procedure without error messages. However if I try to run the ape command or to run `build/bootstrap/make.com` I get a segmentation fault. 

In order to run `build/bootstrap/make.com` I'm just putting `./` in front of it, is that correct?

**Comment by kapstok** [comment]
So I tried to solve the problem with your suggestions. Unfortunately, I get a segfault as well:

```bash
$ sudo ln -sv /opt/cosmo/o/ape/ape.macho /usr/local/bin/ape
/usr/local/bin/ape -> /opt/cosmo/o/ape/ape.macho
$ cosmocc --update
building cosmo host toolchain...
Makefile:81: *** please use build/bootstrap/make.com.  Stop.
$ /opt/cosmo/build/bootstrap/make.com
Segmentation fault: 11
```

Could this be due to using Apple Silicon?

**Comment by kapstok** [comment]
Small update: I can install `Cosmopolitian` on my Linux computer.
I'd like to run it on my Mac, but at least I have a device on which I can run it now.

Maybe it's true that I cannot install it on my Mac because of the aarch64 architecture.

**Comment by kassiansun** [comment]
This is caused by `make` version check, the MacOS comes with a very old `make` tool,  I would suggest use a latest version of `make` instead:
- `brew install make`
- `ln -s /opt/homebrew/bin/gmake /opt/cosmo/bin/make` <- Ideally `/opt/cosmo/bin` should have a higher priority than `/usr/bin/make`

Now you should be able to run `cosmocc --update`, but it still fails to build.

**Comment by jart** [comment]
We provide a modern GNU `make` command in the cosmocc ZIP archive. https://cosmo.zip/pub/cosmocc/cosmocc.zip Please note you don't have to say `cosmocc --update` anymore. If you use `ape.macho` *be sure* you're on an x86-64 system only. If you're on Arm64 MacOS then you need to compile `ape-m1.c` which is also in cosmocc.zip. Furthermore, `/usr/bin/ape` should be preferred on all platforms *except* MacOS Arm64, which forces us to use `/usr/local/bin/ape`. These paths are hard-coded into `execve()` so it's important that APE be in the correct place on your system. If you're not sure, put it at both paths. Just make sure it's the right APE loader for your architecture.

**Comment by kapstok** [comment]
It seems that the problem is solved. First I executed this code:

```bash
git clone https://github.com/jart/cosmopolitan /opt/cosmo
cd /opt/cosmo
sudo ape/apeinstall.sh
./third_party/cosmocc/bin/make -j8
```

I tried

```bash
curl https://cosmo.zip/pub/comocc/cosmocc.zip -o cosmocc.zip
unzip cosmocc.zip
```

after going into `/opt/cosmo/`, unzipping it with `unzip` gave an error. By extracting the zip file by double-clicking it in Finder, I got a `cosmocc` directory. Afterwards, it didn't seem to be necessary.

Makefile threw an error because `o` was missing. So I downloaded and extracted the zip file that was suggested in the terminal after running Makefile. After that, I re-executed:

```bash
./third_party/cosmocc/bin/make -j8
```

Then I manged to compile and execute a c source file with cosmocc:

```bash
export PATH="/opt/cosmo/cosmocc/bin/:$PATH"
./cosmocc/bin/cosmocc examples/hello.c
./a.out
```

Thanks for the help everyone!
