### ISSUE TITLE
printf("% 10.10s", "string") prints garbage

### ISSUE THREAD

**Issue by tavianator** [jart/cosmopolitan#943]
```console
tavianator@tachyon $ cat foo.c
#include <stdio.h>

int main(void) {
        printf("|% 10.10s|\n", "string");
        return 0;
}
tavianator@tachyon $ gcc foo.c -o foo && ./foo
|    string|
tavianator@tachyon $ cosmocc foo.c -o foo && ./foo
|    string\000|% |
```

**Comment by mrdomino** [comment]
```console
% clang foo.c -o foo
foo.c:4:13: warning: flag ' ' results in undefined behavior with 's' conversion specifier [-Wformat]
  printf("|% 10.10s|\n", "string");
           ~^~~~~~~
1 warning generated.
```

If there is a repro of this that doesn't depend on undefined behavior, or you can make an argument that we should handle this particular case of undefined behavior differently, please say so.

**Comment by tavianator** [comment]
This was nonobvious to me because the C standard description of the *space* flag does not include the words "For other conversions, the behavior is undefined" whereas it does for the `#` and `0` flags.  However, I trust the interpretations of GCC and Clang which both agree on this.
