### ISSUE TITLE
older cosmocc doesn't handle certain switch rewrites

### ISSUE THREAD

**Issue by tavianator** [jart/cosmopolitan#945]
Reduced from https://github.com/tavianator/bfs/blob/main/tests/xtouch.c

```console
tavianator@tachyon $ cat foo.c
#include <errno.h>
#include <stdlib.h>

struct {
  enum { a } b;
} c;
char d;

void e() {
        size_t f;
        switch (errno) {
        case ENOENT:
                if (c.b) {
                        break;
                        goto err;
                }
        }
 err:
}
tavianator@tachyon $ cosmocc -c foo.c
foo.c: In function 'e':
foo.c:19:1: internal compiler error: in get_bc_label, at c-family/c-gimplify.c:187
   19 | }
      | ^
Please submit a full bug report,
with preprocessed source if appropriate.
See <https://gcc.gnu.org/bugs/> for instructions.
```

**Comment by ahgamut** [comment]
Can you try this with the updated `cosmocc` https://github.com/jart/cosmopolitan/releases/download/3.0.2/cosmocc-0.0.18.zip ?

I fixed this particular error in my patch with https://github.com/ahgamut/gcc/commit/c583ef7d39113ae96dc1dad9c0515302046ca888 but it may be that this is an edge case I haven't handled before.

**Comment by tavianator** [comment]
I was trying this with cdbd10c9d0b02d2c3ca9544eb5fbe52794d2a6c0, but I can try with that release too

**Comment by tavianator** [comment]
Oh, your cosmocc-0.0.18.zip works.  I assumed `cosmocc --update` would build the latest version of everything.  How do I get it to do that?

**Comment by ahgamut** [comment]
IIRC `cosmocc --update` builds the latest version of Cosmopolitan Libc, but it doesn't re-build the GCC compilers in `o/third_party/gcc` becaues that would take a long time. I'd recommend using the latest `cosmocc.zip` to make building software easier -- for example I use the updated `gcc` binaries to build GNU tar.

**Comment by tavianator** [comment]
> becaues that would take a long time

A full GCC build takes about 45 seconds for me :)

Just to write it down somewhere, it seems this is how to build everything including gcc:

```console
$ umask 022 # Otherwise a test fails
$ make
$ tool/cosmocc/package.sh
```

I bumped `-j8` to `-j48` in the script.  Might be nice to auto-detect that.

**Comment by ahgamut** [comment]
`tool/cosmocc/package.sh` doesn't build GCC from source, it downloads GCC binaries that are built similar to https://github.com/ahgamut/superconfigure. Then again with `make -j48` GCC might build from source in 45 seconds, I've never tried.

Anyway, I think this issue can be closed, because the problem is avoided when using the latest cosmocc.

**Comment by tavianator** [comment]
Oh you're right, I didn't read the whole script.  What *is* the way to build a patched GCC if I want to?

**Comment by ahgamut** [comment]
Use the GCC source with my patch from https://github.com/ahgamut/gcc/tree/portcosmo-11.2
an entire build config is available at https://github.com/ahgamut/superconfigure/blob/main/.github/scripts/build/x86_64-gcc
