### ISSUE TITLE
select() doesn't work with stdin in windows

### ISSUE THREAD

**Issue by edubart** [jart/cosmopolitan#953]
I've been trying to use cosmopolitan compile a cli application that needs to wait for stdin inputs in non-blocking manner. The following test case works as expected on Linux, but fails on Windows (it blocks).

```c
#include <stdbool.h>
#include <stdio.h>
#include <sys/select.h>
#include <sys/time.h>
#include <sys/types.h>
#include <termios.h>
#include <unistd.h>

static struct termios oldtty;

bool wait_stdin(int millis) {
  struct timeval tv = {.tv_sec = millis / 1000,
                       .tv_usec = 1000 * (millis % 1000)};
  fd_set rfds;
  FD_ZERO(&rfds);
  FD_SET(STDIN_FILENO, &rfds);
  return select(1, &rfds, NULL, NULL, &tv) > 0 && FD_ISSET(0, &rfds);
}

void init_tty() {
  tcgetattr(STDIN_FILENO, &oldtty);
  struct termios newtty = oldtty;
  newtty.c_lflag &= ~(ICANON | ECHO);
  newtty.c_cc[VMIN] = 1;
  newtty.c_cc[VTIME] = 0;
  tcsetattr(STDIN_FILENO, TCSAFLUSH, &newtty);
}

void deinit_tty() { tcsetattr(STDIN_FILENO, TCSAFLUSH, &oldtty); }

int main() {
  if (!isatty(STDIN_FILENO)) {
    printf("not a tty\n");
    return 0;
  }
  init_tty();
  if (wait_stdin(10 * 1000)) {
    char buf[1024];
    int len = read(STDIN_FILENO, buf, sizeof(buf));
    if (len > 0) {
      printf("got: %.*s\n", len, buf);
    } else {
      printf("no input\n");
    }
  } else {
    printf("timed out\n");
  }
  deinit_tty();
  return 0;
}
```

Output:
```
$ cosmocc t.c -o t.com
$ ./t.com
got: a
$ wine ./t.com
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
timed out
```

In this example I typed `a` in the terminal while `t.com` is running. In the linux version the `select()` stop and prints back the `got: a` message as expected. However in the windows version, `select()` doesn't stop when typing. I think this happens because Windows does not support `select()` on STDIN, but perhaps Comopolitan could emulate this.

This feature is interesting for making portable cli apps that needs to wait for inputs for a limited time, to continue do some work in the background.

A second issue, seems like disabling terminal `ECHO` with `tcsetattr` did not work as expected also, because typing `a` "echoed" it back in stdout. Disabling the echo is interesting for some cli apps such as terminal emulators.

I think both issues are relevant for making portable interactive cli apps.

PS: I tested only with `wine`, not in a real Windows though. I tested with Cosmopolitan 3.0.2.

**Comment by jart** [comment]
Cosmopolitan does support poll() and select() on Windows. Cosmopolitan also supports `tcsetattr()`, `ECHO`, `ICANON`, etc. See [libc/calls/read-nt.c](https://github.com/jart/cosmopolitan/blob/master/libc/calls/read-nt.c) to read our fabulous termios driver. On my Windows 10 machine, your example behaves exactly the same way it does on Linux.

![image](https://github.com/jart/cosmopolitan/assets/49262/498d832d-4976-496e-b744-9c798ac1a7bf)

Last time I checked, the WINE project hasn't been funded for at least a decade. If you want a first-class terminal experience with Cosmopolitan on Windows, then I recommend using Windows 10+.
