### ISSUE TITLE
Where is `fatcosmocc`?

### ISSUE THREAD

**Issue by tachyonicbytes** [jart/cosmopolitan#963]
The [announcement](https://justine.lol/cosmo3/) mentions a new `fatcosmocc` util that can be used to build fat binaries seamlessly. But I cannot find it anywhere. I searched the archives, I tried building from source.

There are some mentions in the source code, but I couldn't find a way to produce `fatcosmocc`.

Sorry if I am missing something obvious, but can someone tell me how to get it?

**Comment by iulian-birlica** [comment]
I investigated a bit and found this [commit](https://github.com/jart/cosmopolitan/commit/291103ad8d9fec59a7d59d395d02cefadb834332) where `fatcosmocc` was renamed to `cosmocc`. I hope this issue will help others that are looking for this, if there are any.

**Comment by tachyonicbytes** [comment]
I found that `fatcosmocc` was renamed to `cosmocc` in this [commit](https://github.com/jart/cosmopolitan/commit/291103ad8d9fec59a7d59d395d02cefadb834332). I hope this issue helps others with the same question as me.
