### ISSUE TITLE
Suggestion: Launch browser when opening binary

### ISSUE THREAD

**Issue by rovashan** [jart/cosmopolitan#98]
If this is possible then it would add to the portability of redbean and minimize distribution issues with end users.

**Comment by jart** [comment]
That's a really good suggestion.

**Comment by Rotario** [comment]
Hi All,
I've just bumped into this, and am thinking the following should work for Windows and Linux right?

```
if (IsWindows()){
  system("explorer http://127.0.0.1:8080");
} else {
  system("xdg-open http://127.0.0.1:8080");
}
```

**Comment by jart** [comment]
Nice that would actually be the perfect way to do it. I can implement that sometime in the next few days, unless you'd like to send a pull request @Rotario since it was after all your idea.

**Comment by Rotario** [comment]
Yeah - I'd love to contribute!
Am just testing, will open PR soon

**Comment by jart** [comment]
Awesome! See also [CONTRIBUTING.md](https://github.com/jart/cosmopolitan/blob/master/CONTRIBUTING.md).

I did some more research. It looks like we'll want to use the `open` command if `IsXnu()`.

Also, for what it's worth, Cosmopolitan Libc lets you do this too (even though it might be overkill)

```c
  const char *prog;
  if (!vfork()) {
    prog = "xdg-open";
    if (IsXnu()) prog = "open";
    if (IsWindows()) prog = "explorer";
    execvp(prog, (char *const[]){prog, "https://google.com", 0});
    _exit(127);
  }
  wait(0);
```

**Comment by Rotario** [comment]
Sorry to re-open this, but now I've distributed a couple of redbeans to colleagues, it's annoying that the root / just shows the redbean listing? I feel maybe an optional argument to LaunchBrowser specifying index.html or something would be nice? Then it "just works" without some lobster showing up and someone thinking you've sent them a virus!

**Comment by jart** [comment]
Thanks! Glad you like the cute lobster. I might try to make it the file icon on Windows if I can figure out how to embed it in PE. Earning trust is something I think a lot about. If you have any feedback on how we could be doing a better job, let me know!
