### ISSUE TITLE
When using cosmo_dlopen, functions with a lot of parameters fail

### ISSUE THREAD

**Issue by mundusnine** [jart/cosmopolitan#982]
When using functions with more then 4 parameters, the other parameters don't get passed to the function or some odd behavior happens. The fifth parameter doesn't change and the sixth becomes a garbage value.

I initially encountered the issue when trying to use the XCreateImage function from X11.

Here is a [repo](https://github.com/mundusnine/cosmo-test/tree/7723ad0cf49e67be85fa59b23caa69b8b9e7e3d7) to repro the issue. I added multiple test cases to validate other potential causes, but only the last test is the offender. 

On another note, when we use the malloc from the dll, no system call is outputted when using strace, I have no idea if that is normal behavior. It's probably because we use the --strace from the executable maybe ?

**Comment by mundusnine** [comment]
For now, I can work around this caveat. X11 isn't the end goal, I am actually just trying to get fenster running as a light gui framework.

I can compile fenster as a dll easily.

**Comment by jart** [comment]
Glad to hear you're not blocked on this one. I'm going to keep this issue open for more feedback, until eventually myself or someone else has time to tackle this.

**Comment by jart** [comment]
This issue has been fixed by 0e49bed66.
